Shopify/ui-extensions

packages/argo-checkout/src/components/Layout/Layout.ts, packages/argo-checkout/src/components/View/View.ts
Following [2070](https://github.com/Shopify/checkout-web/pull/2070) on Checkout-web
=> Update props for View and Layout

packages/argo-checkout-react/src/index.ts, packages/argo-checkout/src/components/Layout/Layout.ts, packages/argo-checkout/src/components/Layout/index.ts, packages/argo-checkout/src/components/index.ts, packages/argo-checkout/src/index.ts
=> Layout: export Media and Size props

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Second PR (first was https://github.com/Shopify/shopify/pull/258246) to fix https://github.com/Shopify/cross-sell-app/issues/177
Fixes https://github.com/Shopify/cross-sell-app/issues/177
Just updating to expose the new attributes that were added.
=> [Cross Sells] Add missing post purchase attributes

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Relates to: https://github.com/Shopify/cross-sell-app/issues/219
Next step after https://github.com/Shopify/shopify/pull/259486 ships.
=> Rename discountedPriceSet to totalPriceSet

packages/argo-checkout/src/components/Text/Text.ts, packages/argo-checkout/src/components/TextBlock/TextBlock.ts
Those props were recently introduced to the checkout components.
This PR aims to make those props available to argo-checkout consumers 
I will later change our internal implementation to use the argo-checkout props as well.
=> add text appearance props

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Closes: https://github.com/Shopify/cross-sell-app/issues/279
=> [Cross Sell] Introduce SetMetafield as a change type

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
For the sake of consistency with other change types...
=> [Cross Sell] Rename SetMetafield to SetMetafieldChange

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Compatibility update for https://github.com/Shopify/shopify/pull/262422
=> [Post Purchase] Add InputData type

packages/argo-webpack-hot-client/src/worker.ts
This changes the hot reloading client code a bit to make it more reliable. Previously, the first compilation was always "ignored" because we used that to signal the socket was open. The main change here is using the `open` event to determine that instead, and to cleanup on refresh a bit better since I was noticing extra websockets hanging around.
cc/ @henrytao-me @vividviolet your version of this also suffers from the same issue I think: https://github.com/Shopify/argo-admin/blob/main/packages/argo-admin-cli/src/server/hot-client.ts
=> Make hot reloading more reliable

packages/argo-checkout-react/package.json, packages/argo-checkout/package.json, yarn.lock
This upgrades to the latest version of remote-ui, which fixes compatibility with React 17.
=> Update to latest remote-ui

packages/argo-run/src/dev.ts
Just noticed this typo while top-hatting some other PR.
Fix the typo 😉
=> fix typo in a user-facing message

shipit.yml
=> chore: remove custom shipit deploy

packages/post-purchase-ui-extensions/src/components/CalloutBanner/CalloutBanner.ts, packages/post-purchase-ui-extensions/src/components/CalloutBanner/README.md, packages/post-purchase-ui-extensions/src/components/Checkbox/content/guidelines.md, packages/post-purchase-ui-extensions/src/components/Image/Image.ts, packages/post-purchase-ui-extensions/src/components/Image/README.md, packages/post-purchase-ui-extensions/src/components/Separator/README.md, packages/post-purchase-ui-extensions/src/components/Separator/Separator.ts, scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/extension-points.ts, scripts/typedoc/shopify-dev-renderer/getting-started.ts
Makes changes to what content outputs in the docs and some front matter changes.
`ChoiceList` is not a component for post-purchase so I removed the link.
- ...
=> updates for pp

packages/post-purchase-ui-extensions-react/package.json, packages/post-purchase-ui-extensions/package.json
=> Bump post-purchase-ui-extensions versions

packages/admin-ui-extensions-react/src/components/Form/Form.ts, packages/admin-ui-extensions-react/src/components/Form/examples/Form.example.jsx, packages/admin-ui-extensions-react/src/components/Form/index.ts, packages/admin-ui-extensions-react/src/components/TextField/examples/TextField.example.tsx, packages/admin-ui-extensions-react/src/components/index.ts, packages/admin-ui-extensions/src/components/Button/Button.ts, packages/admin-ui-extensions/src/components/Form/Form.ts, packages/admin-ui-extensions/src/components/Form/content/guidelines.md, packages/admin-ui-extensions/src/components/Form/examples/Form.example.ts, packages/admin-ui-extensions/src/components/Form/index.ts, packages/admin-ui-extensions/src/components/TextField/examples/TextField.example.ts, packages/admin-ui-extensions/src/components/index.ts, packages/admin-ui-extensions/src/index.ts
Ticket: https://github.com/Shopify/ui-extensions-private/issues/1623
Adding a new Form component
- ...
=> feature: form component

shipit.yml
=> fix shipit.yml

shipit.admin-rc.yml
=> Shipit test 3

packages/checkout-ui-extensions/src/components/Button/README.md, packages/checkout-ui-extensions/src/components/Image/README.md, packages/checkout-ui-extensions/src/components/Layout/README.md, packages/checkout-ui-extensions/src/components/View/README.md, scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/api-admin.ts, scripts/typedoc/shopify-dev-renderer/components.ts, scripts/typedoc/shopify-dev-renderer/shared/index.ts
- remove `post_unite` flag from checkout
- build indexes as arrays
- remove last highlight tags
=> [Docs script] tweaks

scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/extension-points.ts, scripts/typedoc/shopify-dev-renderer/getting-started.ts
#179 [didn’t merge correctly for some reason](https://github.com/Shopify/ui-extensions/commit/6747ca93b96d01ea22d3a8762a30c63d1aebeb7e). I’ve rebased it and am trying again.
=> copy of #179

documentation/error-handling.md
This PR adds document for error handling. 
See https://github.com/Shopify/checkout-web/issues/5252#issuecomment-864227636
=> Add documentation for error handling

packages/admin-ui-extensions-react/package.json, packages/admin-ui-extensions/package.json, packages/ui-extensions/package.json
Version bumps admin-rc for heading update
- ...
=> version 0.13.0-alpha.7

packages/admin-ui-extensions-react/package.json, packages/admin-ui-extensions-react/src/components/BlockStack/BlockStack.ts, packages/admin-ui-extensions-react/src/components/BlockStack/examples/BlockStack.example.tsx, packages/admin-ui-extensions-react/src/components/BlockStack/index.ts, packages/admin-ui-extensions-react/src/components/InlineStack/InlineStack.ts, packages/admin-ui-extensions-react/src/components/InlineStack/examples/InlineStack.example.tsx, packages/admin-ui-extensions-react/src/components/InlineStack/index.ts, packages/admin-ui-extensions-react/src/components/index.ts, packages/admin-ui-extensions/package.json, packages/admin-ui-extensions/src/component-sets/Basic.ts, packages/admin-ui-extensions/src/components/BlockStack/BlockStack.ts, packages/admin-ui-extensions/src/components/BlockStack/content/guidelines.md, packages/admin-ui-extensions/src/components/BlockStack/examples/BlockStack.example.ts, packages/admin-ui-extensions/src/components/BlockStack/index.ts, packages/admin-ui-extensions/src/components/InlineStack/InlineStack.ts, packages/admin-ui-extensions/src/components/InlineStack/content/guidelines.md, packages/admin-ui-extensions/src/components/InlineStack/examples/InlineStack.example.tsx, packages/admin-ui-extensions/src/components/InlineStack/index.ts, packages/admin-ui-extensions/src/components/index.ts, packages/admin-ui-extensions/src/index.ts, packages/ui-extensions/package.json, packages/ui-extensions/src/index.ts, packages/ui-extensions/src/types/BlockStack.ts, packages/ui-extensions/src/types/InlineStack.ts, packages/ui-extensions/src/types/shared/BlockAlignment.ts, packages/ui-extensions/src/types/shared/InlineAlignment.ts, packages/ui-extensions/src/types/shared/index.ts
Release candidate for:
- @shopify/admin-ui-extensions-react@0.14.0
- @shopify/admin-ui-extensions@0.14.0
- @shopify/ui-extensions@0.3.0
- Create BlockStack in Argo client and hosts (https://github.com/Shopify/ui-extensions/pull/196)
- Create InlineStack in Argo client and hosts (https://github.com/Shopify/ui-extensions/pull/212)
=> [RELEASE] Admin UI Extensions - v0.14.0

packages/post-purchase-ui-extensions-react/package.json, packages/post-purchase-ui-extensions/package.json
Bumping up 2 patch versions because I didn't understand the process and pushed the tags with PR #236.
=> Bump post purchase v0.13.2

packages/checkout-ui-extensions-react/package.json, packages/checkout-ui-extensions/package.json
- @shopify/checkout-ui-extensions-react@0.13.0
- @shopify/checkout-ui-extensions@0.13.0
=> Prepare to publish checkout ui extensions and checkout ui extensions react 0.13.0

packages/admin-ui-extensions/src/extension-api/ContextualSaveBarApi/examples/contextualSaveBar.example.ts, packages/admin-ui-extensions/src/extension-api/ContextualSaveBarApi/index.ts, packages/admin-ui-extensions/src/extension-api/index.ts, packages/admin-ui-extensions/src/extension-points/identifiers/discounts.ts, packages/admin-ui-extensions/src/extension-points/index.ts, packages/admin-ui-extensions/src/extension-points/types.ts, packages/admin-ui-extensions/src/index.ts
Fixes https://github.com/Shopify/discounts-prototype/issues/17
- ...
=> Add Discounts extension API

packages/retail-ui-extensions-react/tsconfig.json, packages/retail-ui-extensions/.gitignore, packages/retail-ui-extensions/package.json
This PR removes a `gitignore` file that is not needed, and reorganizes the package.json (adds a description) so that it matches the other packages in this repo.
We're having some build issues, so we're trying to replicate the other packages as closely as possible.
=> Removed gitignore and reorganized package.json

packages/retail-ui-extensions/src/components/TextField/TextField.ts
I have added inputType as one of the TextFieldProps.
I was told there a version number I have to update somewhere for these changes? Not sure about the process for that.
=> Add inputType to TextFieldProps

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.6.0
- @shopify/retail-ui-extensions@0.6.0
- ...
=> Bump retail-ui-extensions to 0.6.0

packages/retail-ui-extensions/src/components/FormattedTextField/FormattedTextField.ts, packages/retail-ui-extensions/src/components/TextField/TextField.ts, packages/retail-ui-extensions/src/components/shared/index.ts
Made these import folder changes and the type-check test passed on the POS branch.
- ...
=> Fix imports for text fields

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.7.0
- @shopify/retail-ui-extensions@0.7.0
- ...
=> Bump retail-ui-extensions 0.7.0 

packages/checkout-ui-extensions/documentation/globals.md
https://github.com/Shopify/shopify-dev/issues/20451
https://github.com/Shopify/checkout-web/pull/10971
Fix note syntax
Apply some edits for Shopify.dev style
=> Copy over changes fixing Note block syntax in `globals.md`

packages/checkout-ui-extensions/documentation/conditional-props.md, scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/components/components.ts, scripts/typedoc/shopify-dev-renderer/shared/index.ts
Relates to https://github.com/Shopify/shopify-dev/issues/20468..
Shows how the `MaybeConditionalStyle` prop will be handled and how it can also inject a static markdown file that expands on conditional props.
**Note**: this PR should *NOT* be merged with changes to the `checkout-ui-extensions` packages because they are not from `checkout-web@master`. This is using some test code. Changes to packages should be removed prior to merging but are here only for tophatting purposes.
- Copied over the `checkout-ui-extensions` package from https://github.com/Shopify/checkout-web/pull/10995 which has an example of a dummy conditional prop within the `View` component.
- Ran into an infinite loop due to https://github.com/Shopify/docs-tools/issues/26, added some code to kick-out in this scenario
- …
=> Handle Conditional Props in Components Pages

scripts/consumer-helper.sh
add customer account packages to builder
=> add customer account packages to builder

packages/checkout-ui-extensions-react/package.json, packages/checkout-ui-extensions/package.json, packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
- @shopify/checkout-ui-extensions-react@0.16.0
- @shopify/checkout-ui-extensions@0.16.0
- @shopify/customer-account-ui-extensions-react@0.0.3
- @shopify/customer-account-ui-extensions@0.0.3
=> checkout-ui-extensions v0.16.0 --- customer-account-extensions v0.03

packages/web-pixels-extension/package.json
Initial publish of @shopify/web-pixels-extension@0.1.0
`yarn version-bump:web-pixels`
=> Publish @shopify/web-pixels-extension@0.1.0

packages/web-pixels-extension/src/types/web-pixel-api.ts
Add localStorage and sessionStorage to the browser API
=> Add localStorage and sessionStorage to the browser API

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
Also serves as a test for our shipit stack.
Please note that this does **not** merge into `main`, but `customer-account-rc`
=> Release customer beta

package.json, scripts/typedoc/shopify-dev-renderer/components/components.ts, scripts/typedoc/shopify-dev-renderer/shared/index.ts, yarn.lock
The script is missing comments for values in some unions.
Make script work with local non-imported unions as well.
=> Bring back union comments

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
- @shopify/customer-account-ui-extensions-react@0.0.15
- @shopify/customer-account-ui-extensions@0.0.15
=> Publish customer-account

packages/web-pixels-extension/package.json
@shopify/web-pixels-extension@0.1.6
=> update to 0.1.6

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.12.0
- @shopify/retail-ui-extensions@0.12.0
Forgot to create the tags in my previous PR so bumping again 😅 
- ...
=> Bump retail and create tags

packages/web-pixels-extension/package.json
- @shopify/web-pixels-extension@0.1.8-alpha.0
- ...
=> Publish `@shopify/web-pixels-extension@0.1.8-alpha.0`

packages/web-pixels-extension/src/schemas/event.jtd.json, packages/web-pixels-extension/src/types/Event/index.ts
Added the Checkout object to the InitData type for Web Pixels
- ...
=> Add checkout object to InitData

packages/web-pixels-extension/package.json
- @shopify/web-pixels-extension@0.1.9-alpha.0
Pushed with `--follow-tags`
Publishing the latest version of the web pixels extension types
- ...
=> Publish `@shopify/web-pixels-extension@0.1.9-alpha.0`

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
publish new version after merging changes to cart_api calls
- ...
=> pusblish changes in retail-ui-extensions

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.17.0
- @shopify/retail-ui-extensions@0.17.0
New version that contains fixes to the react renderer.
- ...
=> Publishing retail-ui-extensions 0.17.0

packages/post-purchase-ui-extensions/src/extension-points/api/post-purchase/post-purchase.ts
- Updates a few links to the docs on Shopify.dev
- Relates to https://github.com/Shopify/shopify-dev/pull/26563 and https://github.com/Shopify/shopify/pull/379643
- Partially fixes https://github.com/Shopify/shopify-dev/issues/26264
=> [IA changes: `api/examples`]: Update links

packages/retail-ui-extensions/src/extension-api/types/cart.ts
https://github.com/Shopify/pos-next-react-native/issues/17446
Added the parameters to the models. Will create a separate PR to bump the version and then another one to implement the changes on the POS side. 
- ...
=> Added sku, vendor, properties for LineItem and properties for Cart

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.20.0
- @shopify/retail-ui-extensions@0.20.0
Bump for adding the List component
Bump it.
- ...
=> Publish retail 0.20.0

packages/admin-ui-extensions-react/package.json, packages/admin-ui-extensions/package.json
- @shopify/admin-ui-extensions-react@1.0.4
- @shopify/admin-ui-extensions@1.0.4
=> Publish admin libraries

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
- @shopify/customer-account-ui-extensions-react@0.0.20
- @shopify/customer-account-ui-extensions@0.0.20
Includes new `i18n` API for `customer-account-ui-extensions`.
=> Publish customer-account-ui-extensions

packages/ui-extensions/package.json
This publishes the fixes done in https://github.com/Shopify/ui-extensions/pull/582.
=> Bump @shopify/ui-extension alpha version

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.26.0
- @shopify/retail-ui-extensions@0.26.0
This provides a fix to the Stack components, as well as the BasicComponents component set.
- ...
=> Publish version 0.26.0 of retail-ui-extensions

packages/retail-ui-extensions-react/src/components/Navigator/Navigator.ts, packages/retail-ui-extensions-react/src/components/Navigator/index.ts, packages/retail-ui-extensions-react/src/components/Screen/Screen.ts, packages/retail-ui-extensions-react/src/components/Screen/index.ts, packages/retail-ui-extensions-react/src/components/index.ts, packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions/src/component-sets/Basic.ts, packages/retail-ui-extensions/src/components/Navigator/Navigator.ts, packages/retail-ui-extensions/src/components/Navigator/index.ts, packages/retail-ui-extensions/src/components/Screen/Screen.ts, packages/retail-ui-extensions/src/components/Screen/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Testing out the changes with Navigator and Screen components because `yalc` doesn't build. 
- ...
=> Testing the changes with Navigator and Screens

packages/retail-ui-extensions-react/src/index.ts
Export was incorrect for the react package. 
- ...
=> Export fix

packages/retail-ui-extensions-react/src/components/Dialog/Dialog.ts
Fixing Dialog component in react package to inherit from Dialog component from main package. Previously it was inherited from SearchBar.
Fix import
- ...
=> Fixing props for Dialog React package

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json, packages/retail-ui-extensions/src/components/Screen/Screen.ts
Params currently are broken for push navigation. Testing a new approach. 
- ...
=> Navigations params test

packages/retail-ui-extensions/src/components/Dialog/Dialog.ts, packages/retail-ui-extensions/src/components/FormattedTextField/FormattedTextField.ts, packages/retail-ui-extensions/src/components/List/List.ts, packages/retail-ui-extensions/src/components/RadioButtonList/RadioButtonList.ts, packages/retail-ui-extensions/src/components/SearchBar/SearchBar.ts, packages/retail-ui-extensions/src/components/Section/Section.ts, packages/retail-ui-extensions/src/components/Tile/Tile.ts, packages/retail-ui-extensions/src/components/shared/BaseTextField.ts
The team had a meeting on Friday to discuss with UI/UX team and the Polaris for Retail team the components we will expose. The feedback was written down and this ticket for created: https://github.com/Shopify/pos-next-react-native/issues/20038. 
These changes will implement the suggestions proposed at that meeting. 
- ...
=> Component changes to align with UI/UX guidelines

packages/retail-ui-extensions/src/components/Dialog/Dialog.ts
Actions got fixed up during the recent changes. 
Primary action shouldn't be optional. 
- ...
=> Dialog fix

packages/admin-ui-extensions-react/package.json, packages/admin-ui-extensions/package.json
- @shopify/admin-ui-extensions-react@1.1.0
- @shopify/admin-ui-extensions@1.1.0
- ...
=> Publish Admin packages

packages/customer-account-ui-extensions/src/extension-points/standard-api/localization.ts
Close https://github.com/Shopify/core-issues/issues/45813
- ...
=> feat(Customer Account): add `formatCurrency` to standard api

packages/post-purchase-ui-extensions/documentation/extension-points.md, packages/post-purchase-ui-extensions/src/extension-points/extension-points.ts
- Updates a few links to the developer docs, to align with the changes in https://github.com/Shopify/shopify-dev/pull/31441
- Relates to [this proposal](https://docs.google.com/document/d/1V5r4K3rkI7xwIUMA0XMxyLGMTEyj6PAq70_ZJBY2JPw/edit)
- Partially fixes https://github.com/Shopify/shopify-dev/issues/31268
=> [Extension points]: Update links

packages/web-pixels-extension/src/types/EventBus.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts, packages/web-pixels-extension/src/types/index.ts
Update types introduced [this PP ](https://github.com/Shopify/web-pixels-manager/pull/277)
- ...
=> Update Web Pixels Extension types

packages/web-pixels-extension/src/types/PixelEvents/index.ts
Update to match new customer attributes.
=> add firstName and lastName to Customer

packages/retail-ui-extensions/src/components/List/List.ts
The previous name doesn't explain the behavior well.
Renamed
- ...
=> Renamed showDisclosureIndicator into a chevron

packages/web-pixels-extension/src/types/PixelEvents/index.ts, packages/web-pixels-extension/src/types/index.ts
https://github.com/Shopify/ce-customer-behaviour/issues/1719
https://screenshot.click/30-07-o51xz-ljydp.mp4
=> include address1, address2, zip in mailingaddress

packages/web-pixels-extension/src/types/PixelEvents/index.ts
copy changes following suggestions https://github.com/Shopify/shopify-dev/pull/32646
- ...
=> copy changes following suggestions

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@1.0.0
- @shopify/retail-ui-extensions@1.0.0
Made the final changes for GA and bumped the version to 1.0.0.
Version bump. 
- ...
=> Publish GA POS UI Extensions

packages/customer-account-ui-extensions-react/src/render.tsx
This PR does exactly the same as @lemonmade PR (https://github.com/Shopify/ui-extensions/pull/823) but for the **customer-account-ui-extensions-react** package. Credits go to @lemonmade.
Currently we are only able to return React elements synchronously inside of our Extensions, which has the downside that we always have to return an element inside extensions when mounting them, even though they might not be available straightaway (e.g. they need to fetch some data first, before they can render something meaningful).
Having the ability to asynchronously return elements would enable us to do delay the mounting of extensions and thus being able to control when they should be initially displayed (will be of great value for our upcoming MenuAction implementation). 
<br/>
**Sync extension**
1. …
=> [#53923] Allow React extensions to return element asynchrounously (customer-account-ui-extensions-react)

packages/customer-account-ui-extensions-react/package.json
**Publishes a new version**
- @shopify/customer-account-ui-extensions-react@0.0.40
**Includes**
- Allow React extensions to return element asynchrounously
=> Publish [customer-account-ui-extensions-react@0.0.40] - #53923 Allow React extensions to return element asynchrounously

packages/customer-account-ui-extensions/src/extension-points/extension-points.ts
Uses new naming scheme. We'll adjust the other extension points soon as well.
https://www.figma.com/file/rEv6iMXEo2uhtZOndFnG4c/%F0%9F%91%A4-Self-Serve-%7C-Customer-Account-Hub?node-id=6158-177766&t=BHgbTZtgTXG49tAA-0
- ...
=> add dynamic customer account render extension point

packages/web-pixels-extension/src/schemas/pixel-events.jtd.js, packages/web-pixels-extension/src/types/PixelEvents/index.ts
follows https://github.com/Shopify/web-pixels-manager/pull/331
- ...
=> Web pixels export schema to js

packages/customer-account-ui-extensions-react/src/components/shared-components.ts, packages/customer-account-ui-extensions/src/components/shared-components.ts
Accompanying customer account web PR: https://github.com/Shopify/customer-account-web/pull/2038
Resolves https://github.com/Shopify/core-issues/issues/48993
- ...
=> chore(extensibility): expose tooltip & scroll view

packages/checkout-ui-extensions/src/extension-points/api/standard/index.ts
closes: https://github.com/Shopify/ui-extensions/issues/709
relates to: https://github.com/Shopify/ui-extensions/issues/408
relates to: https://github.com/Shopify/checkout-web/issues/20338
docs: https://shopify-dev.checkout-web-api-docs-zc6z.chris-peddecord.us.spin.dev/docs/api/checkout-ui-extensions/unstable/react-hooks/cart/useapplycartlineschange
=> adding selling ID interface to line item add/update

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@1.1.3-rc.1
- @shopify/retail-ui-extensions@1.1.3-rc.1
- ...
=> Publish second candidate for 1.2.0

packages/retail-ui-extensions/src/extension-api/cart-api/cart-api.ts
=> Made staff id optional in staff functions

packages/retail-ui-extensions-react/src/index.ts
=> Removed models from react package export

packages/retail-ui-extensions/src/extension-api/product-search-api/product-search-api.ts
=> Updated product search in line docs

packages/web-pixels-extension/src/types/PixelEvents/index.ts, packages/web-pixels-extension/src/types/index.ts
Quick update of discount application description.
Simple Update!
=> update discount application description

.changeset/two-zebras-protect.md, packages/ui-extensions-react/src/surfaces/admin/components.ts, packages/ui-extensions-react/src/surfaces/admin/components/Text/Text.ts, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/Text/README.md, packages/ui-extensions/src/surfaces/admin/components/Text/Text.ts
Add Text component to the admin surface.
- ...
=> [Admin] Add Text component

.changeset/forty-parrots-hang.md, packages/ui-extensions-react/src/surfaces/admin/components.ts, packages/ui-extensions-react/src/surfaces/admin/components/Button/Button.ts, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/Button/Button.ts, packages/ui-extensions/src/surfaces/admin/components/Button/README.md, packages/ui-extensions/src/surfaces/admin/components/shared.ts
The API and components for the Admin surface are being reviewed as we aim to unify and standardize our APIs.
This PR adds the Button component with the aligned API to the admin surface.
=> [Admin] Add Button component

packages/checkout-ui-extensions-react/src/components/DateField/examples/basic-datefield.example.tsx, packages/checkout-ui-extensions/docs/staticPages/extension-overview.doc.ts
Small tweaks that were done when reviewing the docs PR on shopify.dev.
- ...
=> Doc fixes from PR review

.changeset/proud-readers-drive.md, packages/ui-extensions-react/src/surfaces/admin/components.ts, packages/ui-extensions-react/src/surfaces/admin/components/AppAction/AppAction.ts, packages/ui-extensions-react/src/surfaces/admin/components/AppAction/examples/AppAction.example.jsx, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/AppAction/AppAction.ts, packages/ui-extensions/src/surfaces/admin/components/AppAction/examples/appAction.example.ts
In support of https://github.com/Shopify/app-ui/issues/162
The solution was chosen as a result of [the AppAction RFC](https://github.com/Shopify/ui-api-design/pull/87/files).
- See Tophat instructions in the web PR: https://github.com/Shopify/web/pull/96131
=> Add AppAction component

packages/ui-extensions-react/src/surfaces/admin/components.ts, packages/ui-extensions-react/src/surfaces/admin/components/AppBlock/AppBlock.ts, packages/ui-extensions-react/src/surfaces/admin/components/AppBlock/examples/AppBlock.example.jsx, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/AppBlock/AppBlock.ts, packages/ui-extensions/src/surfaces/admin/components/AppBlock/examples/AppBlock.example.ts
Implements the AppBlock component see [PR in app-ui-design repo](https://github.com/Shopify/ui-api-design/pull/107)
Builds according to the logic chosen for the solution chosen as a result of [the AppAction RFC](https://github.com/Shopify/ui-api-design/pull/87/files).
- See Tophat instructions in the web PR: https://github.com/Shopify/web/pull/96612
=> Add AppBlock component

packages/ui-extensions/src/surfaces/admin/components/Divider/Divider.ts
=> Update `Divider`'s `direction` values from `horizontal`/`vertical` to `block`/`inline`

packages/retail-ui-extensions-react/tsconfig.json, packages/retail-ui-extensions/tsconfig.json
=> Added more fixes to ts config for retail ui 

packages/retail-ui-extensions-react/src/components/index.ts
Missed the react export for NumberField
=> Add react export for NumberField

packages/retail-ui-extensions-react/src/components/TextField/TextField.ts, packages/retail-ui-extensions/src/component-sets/Basic.ts, packages/retail-ui-extensions/src/components/TextField/TextField.ts
TextField comment is more clear now
=> Fix text field deprecation comment

packages/ui-extensions/src/surfaces/admin/components/Checkbox/Checkbox.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Form/Form.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Select/Select.doc.ts
Some links in the doc were pointing to a component that doesn't exist. 
Remove references to said component
=> Remove reference to ChoiceList from docs

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
Part of this: https://github.com/Shopify/ui-extensions/pull/1202
"@shopify/customer-account-ui-extensions-react": "^0.0.57"
"@shopify/customer-account-ui-extensions": "^0.0.55"
=> Publish a new version

packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions/src/components/Badge/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Missed an export chain for the new BadgeStatus
Add it
=> fix(retail): add exports for BadgeStatus

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/authenticated-fetch.jsx
=> docs(admin-extensions): add details about fetch auto-auth and improve example

.changeset/hungry-terms-hunt.md, .changeset/itchy-gifts-collect.md
Originally these changes were added as a minor version, changing them to a patch.
Original changes: https://github.com/Shopify/ui-extensions/pull/1241
re-ran `yarn changeset` to add patch update and removed changeset with minor update
See linked PR above to tophat
=> 2023-07 patch (redo)

packages/ui-extensions/docs/surfaces/checkout/staticPages/versioning-migration.doc.ts
fixes the docs to have the migration table match the Types. 
resolves: [#24408](https://github.com/Shopify/checkout-web/issues/24408)
Finding the extension targets in the table that don't exist in the [targets.ts](https://github.com/Shopify/checkout-web/blob/main/packages/ui-extensions/src/surfaces/checkout/targets.ts) file and replace them. 
I do wonder if there is a way we want to keep track of any changes and be able to rebuild the table though the CLI? instead of manually replacing them? Do we know if there will be any upcoming changes to the types? If so, how do we want to make sure that its being captured in all the documents? 
@aledalgrande I believe you built this [original file](https://github.com/Shopify/checkout-web/pull/23743). What did you use to build the table? 
<details> …
=> fix: correct Target Name

packages/customer-account-ui-extensions/src/extension-points/extension-points.ts, packages/customer-account-ui-extensions/src/extension-points/standard-api/index.ts, packages/customer-account-ui-extensions/src/extension-points/standard-api/navigation.ts
Supporting PR for https://github.com/Shopify/customer-account-web/pull/2723
Tophat https://github.com/Shopify/customer-account-web/pull/2723
=> Navigation events

.changeset/warm-phones-dream.md, packages/ui-extensions/src/surfaces/checkout/components/LoginWithShop/LoginWithShop.ts
Addresses shopify/shop-pay-issues#253 by exposing additional properties for the LoginWithShop component.
=> Expose additional properties for LoginWithShop component

packages/ui-extensions/docs/surfaces/checkout/reference/examples/order-status/default.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/order-status/default.example.tsx
Copy of https://github.com/Shopify/ui-extensions/pull/1322
- ...
=> Fix osp examples for 2023-07

packages/ui-extensions-react/src/surfaces/checkout/hooks/checkout-token.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
checkoutToken description updates for docs.
=> Updates to checkoutToken descriptions for docs

packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
This change was forgotten to be added in the unstable version
https://github.com/Shopify/ui-extensions/pull/1233/files
- ...
=> FullExtensionNavigation

packages/ui-extensions/src/surfaces/admin/components/Form/Form.doc.ts
* https://github.com/Shopify/app-ui/issues/319
=> docs: specify Form integration with CSB

packages/web-pixels-extension/src/schemas/pixel-events.ts
Adding changes resulting from https://github.com/Shopify/web-pixels-manager/pull/451
Just updating the jtd schema
- ...
=> Updating pixel-events.ts file

.changeset/great-pigs-give.md
=> Update changeset to state react 18 dependency

packages/ui-extensions/src/surfaces/customer-account/api.ts, packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Moving hardcoded typings into an api interface
Needed for the dev docs
No need to tophat
=> Add order api

packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Issue: https://github.com/Shopify/core-issues/issues/60457
=> Return and fulfillment ids 

.changeset/nasty-planets-smash.md, packages/ui-extensions/src/surfaces/checkout/components/LoginWithShop/LoginWithShop.ts
Add an additional `onStatusChange` callback to LWS component.
=> Add onStatusChange callback to LWS

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
=> New 1.5.0 RC for POS

.github/workflows/cla.yml
Adds Contributor License Agreement (CLA) to repo.
=> Add CLA to github workflows

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts
Updating a broken figma link in the docs
=> update figma link

packages/ui-extensions/src/surfaces/customer-account/api/docs.ts
Part of https://github.com/Shopify/core-issues/issues/60110 
Please also have a review of this PR: https://github.com/Shopify/customer-account-web/pull/3221 
added order status api storefront api doc type.
Please follow the tophat instructions here: 
https://github.com/Shopify/customer-account-web/pull/3221
=> add customer account configuration doc types

.changeset/clever-parents-beam.md, packages/ui-extensions/src/surfaces/checkout/components/LoginWithShop/LoginWithShop.ts
Update `unstable` with latest LWS props.
=> Add additional props to LWS component

packages/ui-extensions/src/surfaces/customer-account/targets.ts
Fixes https://github.com/Shopify/core-issues/issues/62776
=> Make customer-account.profile.payment.render-after experimental

packages/ui-extensions/src/surfaces/customer-account/api/docs.ts
Part of https://github.com/Shopify/core-issues/issues/62930
Related to https://github.com/Shopify/customer-account-web/pull/3374
Related to https://github.com/Shopify/customer-account-web/pull/3379
See https://github.com/Shopify/customer-account-web/pull/3374 for details
=> Add docs for special CustomerAccountAction buttons

packages/ui-extensions/src/surfaces/admin/components/Icon/Icon.doc.ts
Removed duplicate item in Related content
https://github.com/Shopify/shopify-dev/pull/39351
closes https://github.com/Shopify/app-ui/issues/586
=> removed duplicated related item

packages/ui-extensions/src/surfaces/admin/components/AdminAction/AdminAction.ts, packages/ui-extensions/src/surfaces/admin/components/Banner/Banner.ts, packages/ui-extensions/src/surfaces/customer-account/components/CustomerAccountAction/CustomerAccountAction.ts
Fixed a typo in a few locations of primaryAction & secondaryAction. 
https://github.com/Shopify/shopify-dev/pull/39346
=> fixed typo for a few primaryAction & secondaryAction

packages/ui-extensions/src/surfaces/admin/components/ColorPicker/ColorPicker.ts
=> chore: copy ColorPicker docs from 2024-01

packages/ui-extensions/docs/surfaces/checkout/build-docs.sh
Same change as https://github.com/Shopify/ui-extensions/pull/1709.
=> 2024-01 Update build-docs.sh

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
=> Publish retail-ui-extensions 1.7-rc.2

packages/ui-extensions/src/surfaces/point-of-sale/api/action-api/action-api.ts, packages/ui-extensions/src/surfaces/point-of-sale/targets.ts
=> Adds new configuration for pos

packages/ui-extensions/src/surfaces/admin/api/action/action.doc.ts, packages/ui-extensions/src/surfaces/admin/components/AdminAction/AdminAction.doc.ts
Closes https://github.com/Shopify/app-ui/issues/811
- ...
=> chore: clarify that AdminAction component is required

packages/ui-extensions/src/surfaces/point-of-sale/components/Actiontem/ActionItem.ts
=> Make badgeValue optional on ActionItem

packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts
=> fix remote ui link 2023 10 (2)

packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts
=> fix remote ui link 2024 01 (2)

packages/ui-extensions/src/surfaces/checkout/components/Sheet/Sheet.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/Sheet/Sheet.ts
- Removing wrong docs for the component
- Enhancing defaultOpen description
- ...
=> [Ui components]: Adding latest docs for sheet

packages/ui-extensions/src/surfaces/admin/components/Image/Image.ts
Relates to https://github.com/Shopify/app-ui/issues/935
- https://shopify-dev.ui-extensions-j1vw.mitch-lillie.us.spin.dev/docs/api/admin-extensions/unstable/components/media/image
=> Clarify that blobs are not currently supported

.changeset/twelve-otters-think.md, packages/ui-extensions-react/src/surfaces/checkout/hooks/api.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/api.test.tsx, packages/ui-extensions-react/src/surfaces/customer-account/hooks/api.ts, packages/ui-extensions-react/src/surfaces/customer-account/hooks/tests/api.test.tsx
Apply [patch](https://github.com/Shopify/ui-extensions/pull/1942) already merged to unstable.
=> 2023-10: improve hook error message

.changeset/twelve-otters-think.md, packages/ui-extensions-react/src/surfaces/checkout/hooks/api.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/api.test.tsx, packages/ui-extensions-react/src/surfaces/customer-account/hooks/api.ts, packages/ui-extensions-react/src/surfaces/customer-account/hooks/tests/api.test.tsx, packages/ui-extensions-react/src/surfaces/point-of-sale/hooks/api.ts
Apply [patch](https://github.com/Shopify/ui-extensions/pull/1942) already merged to unstable.
=> 2024-01: improve hook error message

.changeset/twelve-otters-think.md, packages/ui-extensions-react/src/surfaces/checkout/hooks/api.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/api.test.tsx, packages/ui-extensions-react/src/surfaces/customer-account/hooks/api.ts, packages/ui-extensions-react/src/surfaces/customer-account/hooks/tests/api.test.tsx, packages/ui-extensions-react/src/surfaces/point-of-sale/hooks/api.ts
Apply [patch](https://github.com/Shopify/ui-extensions/pull/1942) already merged to unstable.
=> 2024-04: improve hook error message

packages/web-pixels-extension/src/types/EventBus.ts, packages/web-pixels-extension/src/types/ExtensionApi.ts, packages/web-pixels-extension/src/types/PublicApi.ts, packages/web-pixels-extension/src/types/WebPixelsManager.ts, packages/web-pixels-extension/src/types/index.ts
Updating wpm types
Result of updates from: https://github.com/Shopify/web-pixels-manager/pull/729
- ...
=> Renamed EventBus to WebPixelsManager

.changeset/swift-cherries-prove.md, packages/ui-extensions/src/surfaces/admin/api/block/block.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/metafields.ts, packages/ui-extensions/src/surfaces/admin/api/order-routing-rule/metafields.ts, packages/ui-extensions/src/surfaces/admin/api/resource-picker/resource-picker.ts, yarn.lock
Allow Admin Block extensions to access the App Bridge Resource Picker.
=> Add resource picker api to block extensions

packages/ui-extensions/src/surfaces/point-of-sale/api.ts
The StandardAPI is not being exported properly from the package
- ...
=> Exporting standard API from POS

packages/web-pixels-extension/package.json
updating pixels package version
ran yarn version-bump:web-pixels  
- ...
=> Update pixels version

packages/web-pixels-extension/package.json
updating pixels package version
ran yarn version-bump:web-pixels  
- ...
=> Version bump wpm

packages/ui-extensions-react/src/surfaces/customer-account/hooks/index.ts
=> add missing useI18n export

packages/ui-extensions/src/surfaces/admin/components/AdminPrintAction/AdminPrintAction.ts
Relates to https://github.com/Shopify/app-ui/issues/1344
- Docs here - https://shopify-dev.docs.mitch-lillie.us.spin.dev/docs/api/admin-extensions/unstable/components/other/adminprintaction
=> Explain support for pdf and images

packages/ui-extensions/src/surfaces/point-of-sale/api.ts
=> Fix device api import

.changeset/odd-avocados-sip.md
- Removing unwanted changeset. to avoid the angry bot to keep creating a package version for a simple docs change
- ...
=> [Docs]: remove changeset

packages/ui-extensions/docs/surfaces/admin/build-docs.sh, packages/ui-extensions/docs/surfaces/checkout/build-docs.sh, packages/ui-extensions/docs/surfaces/customer-account/build-docs.sh, packages/ui-extensions/docs/surfaces/point-of-sale/build-docs.sh
The 2024-07 version of https://github.com/Shopify/ui-extensions/pull/2289
Copied it. Got some additional fixes for some React types etc, which seem fine to pull in from unstable.
=> [2024-07] Fix doc generation on localdev

packages/ui-extensions/docs/surfaces/admin/build-docs.sh, packages/ui-extensions/docs/surfaces/checkout/build-docs.sh, packages/ui-extensions/docs/surfaces/customer-account/build-docs.sh, packages/ui-extensions/docs/surfaces/point-of-sale/build-docs.sh
reverting the bug that was introduced. 
Following this PR's solution: https://github.com/Shopify/ui-extensions/commit/94cd85dfa33b2a4bf82d95fa0d7f91a1130131d9
- ...
=> fix build-docs file to run gh action

packages/web-pixels-extension/package.json
Epic https://github.com/Shopify/core-issues/issues/73165
Closes https://github.com/Shopify/core-issues/issues/76304
- ...
=> Publish web-pixels-extension@2.13.0

.github/workflows/ci.yml
Backporting https://github.com/Shopify/ui-extensions/pull/2319 to `2024-07`
=> Fix docs building in CI

packages/ui-extensions/src/surfaces/customer-account/api/shared.ts
Part of Shopify/core-issues#74679
Docs and comments will follow later.
=> add forceDataRefresh api

packages/ui-extensions/package.json
=> Fix docs building in Spin [2024-07]

packages/ui-extensions/src/surfaces/point-of-sale/api/draft-order-api/draft-order-api.ts
=> Fixed inline docs for draft order interface

.changeset/tasty-trainers-lick.md, packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/form-default-value.jsx, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/form-implicit-default.jsx, packages/ui-extensions/src/surfaces/admin/components/Box/Box.ts, packages/ui-extensions/src/surfaces/admin/components/shared/display.ts
[Docs Spin link](https://shopify-dev.ui-extensions-h8u9.phiroze-noble.us.spin.dev/docs/api/admin-extensions/unstable#using-forms)
=> Add display:none on Box and add Form guidance docs

packages/ui-extensions/docs/surfaces/customer-account/reference/targets/customer-account.order.page.render.doc.ts, packages/ui-extensions/docs/surfaces/customer-account/reference/targets/customer-account.page.render.doc.ts, packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/custom-protocols/extension-link.example.tsx
- Update target name style
- Update Sample code
=> Fix code style of customer account doc

.changeset/brave-rivers-crash.md, .changeset/breezy-mangos-fry.md, .changeset/eight-peas-buy.md, .changeset/fast-crabs-act.md, .changeset/fast-geckos-double.md, .changeset/gold-pillows-protect.md, .changeset/light-dancers-pump.md, .changeset/lucky-beds-shout.md, .changeset/many-houses-build.md, .changeset/mean-trains-fly.md, .changeset/new-badgers-mix.md, .changeset/proud-baboons-work.md, .changeset/shiny-frogs-reflect.md, .changeset/silly-balloons-turn.md, .changeset/tall-bees-scream.md, .changeset/tasty-coats-shave.md, .changeset/tasty-trainers-lick.md, .changeset/violet-lamps-relate.md, .changeset/warm-tigers-sin.md, .changeset/young-buckets-punch.md
removes `2024-10` changeset logs from unstable
- ...
=> remove 2024-10 changeset logs

packages/ui-extensions/docs/surfaces/checkout/staticPages/instructions-update.doc.ts
Updates the title to the correct version
- ...
=> update title to new verision

.changeset/kind-flowers-dress.md
This updates the changeset so the changes introduced here will be published: https://github.com/Shopify/ui-extensions/pull/2407
Add the changeset entry
=> Add changeset for PrintApi and PrintPreview

packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/print-preview/default.example.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/print-preview/default.example.tsx
=> update examples to use closures

.github/workflows/create-stable-version.yml, documentation/versions-and-deploys.md
=> Add stable version action

.changeset/unlucky-cycles-invite.md, packages/ui-extensions/src/surfaces/admin/registration.ts
=> Fix render extension return type

.changeset/twenty-ravens-leave.md
changeset didn't get nixed during my git adventure
=> changeset didn't get nixed

.changeset/gorgeous-zebras-trade.md, packages/ui-extensions-react/src/surfaces/customer-account/components/shared-checkout-components.ts, packages/ui-extensions/src/surfaces/customer-account/components/shared-checkout-components.ts
Part of https://github.com/Shopify/core-issues/issues/82152
=> expose clipboard item to customer-accounts

packages/web-pixels-extension/package.json
- @shopify/web-pixels-extension@2.16.0
Publishes:
- https://github.com/Shopify/ui-extensions/pull/2532
Checklist
=> Publish @shopify/web-pixels-extension@2.16.0

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
Related to this issue https://github.com/Shopify/ui-extensions/issues/2305 
- ...
=> [unstable]Update payment options documentation

packages/ui-extensions/docs/surfaces/customer-account/reference/apis/order-status-api/address.doc.ts
=> Add useBillingAddress documentation to customer accounts

packages/ui-extensions/docs/surfaces/customer-account/staticPages/overview.doc.ts
See https://github.com/Shopify/shopify-dev/pull/53417
=> [Customer Account][2024-10] fix broken link
