Shopify/ui-extensions

packages/argo-checkout-react/src/index.ts, packages/argo-checkout/src/components/Layout/Layout.ts, packages/argo-checkout/src/components/Layout/index.ts, packages/argo-checkout/src/components/index.ts, packages/argo-checkout/src/index.ts
Reverts Shopify/argo-checkout#24
Found a better way to access those from LayoutProps
=> Revert "Layout: export Media and Size props"

packages/argo-checkout-react/src/components/index.ts
🎩 
In this repo on this branch
```
yarn
yarn build
cd packages/yarn-checkout-react
yarn link
cd ../..
cd packages/yarn-checkout
yarn link
```
Create a new project based on our template.
Run
```
yarn
yarn link "@shopify/argo-checkout" && yarn link "@shopify/argo-checkout-react"
yarn server
```
Put `Spinner` somewhere
Finish checkout to post purchase page, see the spinner working
=> fix missing spinner

packages/argo-checkout/src/extension-points/api/post-purchase/index.ts, packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
1. Add shipping lines
1. Split calculate and apply outputs into their own types
1. Updated output of `calculate` to remove partial option, and remove `updatedPurchase` on error
1. Updated output of `apply` to remove purchase response.
1. Remove `changesetProcessingStatus` export - it's inline now
1. Add new `add_shipping_line` operation in `ChangeType`
1. Add new `ShippingLineChange` etc.
Edit on Aug 18:
> I just pushed another change:
> 
> `updatedPurchase` -> `calculatedPurchase`
> `UpdatedPurchase` -> `CalculatedPurchase`
=> [Cross sells] Update postpurchase types to latest

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
issue h/t @jared-dykstra 
When you used TS autocomplete on a `CalculateChangesetResult`, it would never show `calculatedPurchase` unless you type-guarded it with a `status === 'processed'`
This PR changes it so that if you don't check the status, `calculatedPurchase` is available, but optional. So you'd still have to manually ensure that it exists.
if you check for `status === 'processed'`, `calculatedPurchase` is available and not-optional.
if you check for `status === 'unprocessed'` and try to access `calculatedPurchase` TS will produce an error.
=> improve autocompletion for CalculateChangesetResult.calculatedPurchase

packages/argo-run/package.json, packages/argo-run/src/dev.ts
fixes https://github.com/Shopify/cross-sell-app/issues/188
Reads `config.extension.yml` and prints the content as copy/pastable query string to the terminal. 
Partners can copy paste this to apply metafields during development. (not implemented in core yet)
This also exposes a `/config` endpoint which responds with the config as json.
The endpoint is going to be used by our extension to automatically append the config, just like we're doing for the script_url itself. (PR for that will follow)
🎩 
We'll use a test branch in the `argo-checkout-template` repo with a locally built and linked argo-run (package in this repo) version. 
Make sure, you have all the repos:
```
dev clone argo-checkout
dev clone argo-checkout-template
```
prepare this branch and build all the things™
```
dev cd …
```
=> read config and provide query string

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Doing this so we can get rid of the `ShopWithDomain` hack in https://github.com/Shopify/post-purchase-reference-extension/pull/27.
=> Add domain to shop

packages/argo-checkout/src/components/Banner/Banner.ts, packages/argo-checkout/src/components/Banner/README.md, packages/argo-checkout/src/components/Banner/index.ts, packages/argo-checkout/src/components/index.ts
This PR adds a Banner component (from checkout-web-ui)
```jsx
<Banner title="This is an informative message" />
<Banner status="success" title="This is a success message" />
<Banner status="warning" title="This is a warning message" />
<Banner status="critical" title="This is an error message" />
<Banner title="This is a message with content">
<Text>
Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolores
commodi, vitae explicabo, laudantium consequatur eaque dignissimos
dolorem optio minus porro nesciunt magni reprehenderit accusamus quasi
sit architecto sequi nihil.
</Text>
</Banner>
```
=> Adding Banner component

packages/argo-checkout-react/src/components/Banner.ts, packages/argo-checkout-react/src/components/index.ts, packages/argo-checkout-react/src/index.ts, packages/argo-checkout/src/components/index.ts, yarn.lock
Banner was added to `argo-checkout` in #36 but not yet to `argo-checkout-react`
Also updates yarn.lock which I missed prior.
🎩  by running a locally built and linked version of argo-checkout-react:
=> Add banner to argo-checkout-react

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Depends on https://github.com/Shopify/shopify/pull/258829
Part 2/2 of https://github.com/Shopify/cross-sell-app/issues/231
Fixes https://github.com/Shopify/cross-sell-app/issues/231
---
This PR changes the expected input type for `calculateChangeset` to either be a `Changeset` (array of changes) or a string (assumed to be a JWT).
=> [Cross Sells] Support JWT/string input on calculateChangeset JS

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Only works once https://github.com/Shopify/shopify/pull/259794 is merged, but can be shipped early and such.
Related to https://github.com/Shopify/cross-sell-app/issues/232
This PR changes the expected input type for `applyChangeset` to be a string (assumed to be a JWT).
This is intended to be a breaking change as this API will stop supporting non-JWT payloads after partners migrate to this.
=> [Cross Sells] Support JWT/string input on applyChangeset JS

packages/argo-run/src/dev.ts, packages/argo-run/src/utilities.ts
Reads `SHOPIFY_API_KEY` from `.env` file and prints it as part of the copy/pastable query parameter string and exposes it on a new new `/data` endpoint.
The current `/config` endpoint was too restricted as it only returned the user defined config. 
I kept the endpoint to allow older versions of the browser extension to still function. We will remove it later.
The new endpoint exposes `config` only as one key of many, which keeps it open for potential later extension.
A new version of the browser extension that automatically appends the `api_key` follows after this PR is merged. 
We'll use a test branch in the `argo-checkout-template` repo with a locally built and linked argo-run (package in this repo) version. 
Make sure, you have all the repos:
```
dev clone argo-checkout
dev clone …
```
=> expose api key for extension / printed query string

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Relates to: https://github.com/Shopify/cross-sell-app/issues/258
Follow-up for: https://github.com/Shopify/shopify/pull/260807
Adding `orderMetafield` to apply changeset action.
=> [Cross Sell] Add metafield on apply

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Reverts Shopify/argo-checkout#43 in favour of moving metafield input into `changes` content as another change type.
=> Revert "[Cross Sell] Add metafield on apply"

packages/argo-checkout-react/package.json, packages/argo-checkout-react/src/render.ts, packages/argo-checkout/package.json, yarn.lock
This PR updates the remote-ui dependencies. I made one breaking change to `@remote-ui/react` that needs to be accounted for: `render()` no longer calls `root.mount()` automatically, but does allow a callback where we can call that method at the same point it was previously being called. This change was made to allow `render` to support more use cases, most notably "taking over" a remote root object that is already mounted.
cc/ @henrytao-me @vividviolet @alanthai the same change will be needed on the admin library.
=> Update remote-ui dependencies

packages/argo-run/src/webpack-config.ts
It optimized objects to use shorthand property syntax.
`{setTimeout: setTimeout}` to `{setTimeout}`
Which isn't supported in IE(11).
Changed ecma version to 5 to avoid even more potential surprises. 😬
=> ensure terser does not produce IE 11 incompatible bundles

packages/argo-checkout/src/extension-points/api/post-purchase/post-purchase.ts
Compatibility update for https://github.com/Shopify/shopify/pull/265637
Resolves https://github.com/Shopify/cross-sell-app/issues/83
=> [Post-Purchase] Remove 'phone' field from 'AddShippingLineChange'

packages/argo-checkout-react/package.json, packages/argo-checkout/package.json, yarn.lock
This PR updates `@remote-ui` dependencies. Importantly, this brings in some fixes I made that help avoid some sneaky timing issues with function references changing in some cases (https://github.com/Shopify/remote-ui/pull/32).
=> Upgrade remote-ui

packages/argo-checkout/README.md, packages/argo-checkout/documentation/globals.md, packages/argo-checkout/documentation/rendering.md, packages/argo-checkout/documentation/testing.md
@mdarveau pointed out that `mount()` seemed weird/ unnecessary. I've always felt a little uncomfortable about it as well; it serves a purpose in preventing remote-ui from sending all the initial UI updates individually, but feels like boilerplate from the perspective of the developer. Manuel suggested just doing the `mount()` implicitly once the function finishes (or resolves, if it's a promise), so I've done the extension side of that change here. Extensions could still call `mount()` explicitly if they want to flush their initial UI before the render function resolves, as there is no penalty to calling `mount()` multiple times.
There will be a follow-up change to the checkout sandbox that actually does the calling of `mount()` at the necessary time that I will open once I have merged …
=> Remove need to explicitly mount UI

packages/argo-run/src/webpack-config.ts
Fixes issues where required modules weren't probably transpiled to work with our browser matrix.
Usually packages are supposed to produce proper ES5 builds, but not all of them do :( 
E.g. `@lightspeed/i18n-number-format` contains rest and spread.
Will come at the expense of slower builds.
🎩 dev and prod build locally with newly created argo-checkout-template project. 
Installed and used `@lightspeed/i18n-number-format` (as this package is known to cause issues) and checked that no rest or spread was to be found anymore.
🎩 prod
```
yarn build
cd build 
npx http-serve -c-1 -p 39351
```
use http://localhost:39351/main.js as script_url
We can always go back to another solution (like allowing consumers to allowlist packages) later.
=> include node_modules when transpiling

packages/argo-checkout-react/package.json, packages/argo-run/src/utilities.ts, yarn.lock
We were having issues with some extensions on the new 0.9 version of argo-checkout, which uses mini-react by default. This PR reverts using mini-react by default until we know the cause of the issues we are seeing. For partners, this change is completely transparent, but under the hood their extensions will go back up in size a bit now that we are using the "real" React again.
=> Revert back to default to "regular" React

packages/argo-run/package.json, packages/argo-run/src/dev.ts, packages/argo-run/src/utilities.ts, yarn.lock
This PR updates the local development experience for extensions that are detected as being checkout extensions (this detection will rely on the new template being introduced in https://github.com/Shopify/argo-checkout-template/pull/40):
- A new endpoint, `/query` exists. This endpoint fetches the metadata of your extension "workspace". Right now, it will just be a listing of one extension, because that's all our CLI supports. That metadata includes the asset URL and socket URL
- We print instructions for running these new checkout extensions, which goes through the whole "start a tunnel, make a checkout, paste this query param" flow that the developer needs to do next.
cc/ @henrytao-me @vividviolet
=> Update local development for checkout extensions

scripts/generate-docs.ts, scripts/typedoc/typedoc.ts
tldr the script now takes a `paths` object to allow for usage in multiple repos. I've only implemented this in `components()` for now (need to do some additional thinking about how we want to output extension point docs for Admin, as it looks a bit different than Checkout).
You should be able to merge this in without breaking anything. There should be no changes to the output: running `yarn run:ts scripts/generate-docs.ts` in this branch should create the same output as the exact same as the existing docs script (actually there’s one `\n` added to the `argo-checkout/index.md` file 😂).
=> Add `paths` arg to components renderer

packages/argo-run/src/utilities.ts
We are currently detecting whether we should apply React transformations on the basis of whether the developer uses the `@shopify/argo-checkout-react` package. When I added the new `argo-post-purchase-react` package, I forgot to also check for it. This PR fixes that :)
=> Fix React builds for post-purchase

packages/argo-admin/src/components/index.ts
When removing the `VisuallyHidden` component, I missed an import.
Remove `VisuallyHidden` import from `argo-admin` package
=> fix: remove stray visuallyhidden import

package.json
Improve `yarn clean` and `yarn clear-cache` commands to remove all relevant files
Related files were not cleaned up in the current commands so I made some improvements
1. Run `yarn build` and verify that built files (*.d.ts, *.esnext, *.js, *.mjs, anything inside `/build`) are created
2. Run `yarn clean` and verify that all built files are removed
3. Run `yarn clear-cache` and verify that the the `.sewing-kit` directory is delete
=> Clean up root build folder when running yarn clean

packages/argo-run/src/dev.ts
This PR change log level to show error message including port conflict. Note that, this PR doesn't not terminate the server, it just allow error message goes through. I think it's sufficient enough and generic. 
Resolves https://github.com/Shopify/checkout-web/issues/5067
Change log level
- Create new checkout extension `shopify create extension`
- Run the extension via `shopify serve`, note the port
- In this PR run, `yarn && yarn build && cp -R ./packages/* ../your-extension-prodject/node_modules/@shopify/`
- Run the extension in different terminal using same port `yarn start --port <some-port-number>`
- Verify that the error message about port conflict appear
```
yarn start --port 8910
yarn run v1.22.4
$ argo-run dev --port 8910
🔭 > Starting dev server on http://localhost:8910
✖ ｢wds｣: …
```
=> Change log level to show port conflict error

packages/argo-run/src/dev.ts, packages/argo-run/src/utilities.ts
Resolves https://github.com/Shopify/checkout-web/issues/5036
Currently the `appMetafields` API is returning mock values for local development argo extensions. However, we want developers to have a better experience when working with this API and return actual metafield values from Core which is what should be expected when the extension is registered and running on production. 
To do this, we need to expose the metafields config when querying for an extension data through the `/query` endpoint. This will allow us to return specific metafields rather than exposing metafields that are not needed by an extension.
- On this branch, run `yarn && yarn build && yarn link`
- Clone `argo-checkout-template` and run `yarn && yarn generate --type=CHECKOUT_ARGO_EXTENSION --template=react-typescript`
- …
=> Expose metafields from an argo extension config file

scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/components.ts, scripts/typedoc/types.ts
We are including static images for component examples until we have a live sandbox. This will include the markdown image if it exists.
Also, needed newlines between the props table and additional content.
=> Doc images and table spacing

packages/argo-run/src/dev.ts, packages/argo-run/src/utilities.ts, scripts/consumer-helper.sh
Enable argo-run to receive a  `--publicUrl` from the `shopify-app-cli`.  Presence of the flag signals that a tunnel has already been started and that the only step left to do for the developer is to create a checkout.
* Enable argo-run to take a new `namedArgument` called `publicUrl`.
* Adjust log output based on the presence of `publicUrl` when telling the developer what to do next.
* shopify create extension (Post Purchase)
* _In argo project,_ `yarn build-consumer ../../local/cli-specification-experiment/tunnel-and-serve-cpp-test argo-run`
* _In extension project,_ update extension.config.yml:
```
---
extensionPoints: []
```
* _In extension project,_ `yarn start --publicUrl http://1234.ngrok.io/`
* Expect output
```
🔭 > Starting dev server on port 39351
🔭 > Your extension is available …
```
=> New flag: publicUrl

scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/components.ts
Generally, the script can now:
- Generate component READMEs for the input package (see #108)
- Skip components
- Map subcomponent content to parent component content
For checkout specifically:
- Making use of the above features
- Now generating the docs from this repo
- Replacing checkout component GitHub links with the shopify.dev link
Closes #112
=> readme generation, subcomponent docs, and build docs from argo

packages/argo-run/src/dev.ts
This PR fixes webSocket for liveReload in Safari. Currently, argo-run hardcode localhost for webSocket. It works in Chrome but Safari doesn't like it due to insecure connection. 
Resolves https://github.com/Shopify/checkout-web/issues/5179
Shopify cli already pass `publicUrl` argument. It's used to construct the scriptUrl. We can use it to construct webSocket url too. 
- Download latest shopify-app-cli
- Create new checkout extension with shopify cli
- Run `shopify serve`
- Open ngrok url, ex: https://fd1df9e54b46.ngrok.io/query. Verify that socket url looks like `"socketUrl":"wss://fd1df9e54b46.ngrok.io/build"`
- Run `yarn start`
- Open localhost url, ex http://localhost:8910/query. Verify that socket url looks like `"socketUrl":"ws://localhost:8910/build"`
- Add a product and checkout …
=> Fix webSocket for liveReload in Safari

packages/argo-admin-react/package.json, yarn.lock
Bump the version of remote-ui/react to ^4.0.3
This consumes the https://github.com/Shopify/remote-ui/pull/85 fix for exporting the RemoteReceiver type in the esnext build of remote-ui/react.
=> argo-admin: update to remote-ui/react@^4.0.3

packages/argo-admin-react/src/components/Badge/index.ts, packages/argo-admin-react/src/components/Banner/index.ts, packages/argo-admin-react/src/components/Button/index.ts, packages/argo-admin-react/src/components/Card/index.ts, packages/argo-admin-react/src/components/CardSection/index.ts, packages/argo-admin-react/src/components/Checkbox/index.ts, packages/argo-admin-react/src/components/Icon/Icon.ts, packages/argo-admin-react/src/components/Icon/index.ts, packages/argo-admin-react/src/components/Link/index.ts, packages/argo-admin-react/src/components/Modal/index.ts, packages/argo-admin-react/src/components/OptionList/index.ts, packages/argo-admin-react/src/components/Pressable/index.ts, packages/argo-admin-react/src/components/Radio/index.ts, packages/argo-admin-react/src/components/ResourceItem/index.ts, packages/argo-admin-react/src/components/ResourceList/index.ts, packages/argo-admin-react/src/components/Select/Select.ts, packages/argo-admin-react/src/components/Select/index.ts, packages/argo-admin-react/src/components/Spinner/index.ts, packages/argo-admin-react/src/components/Stack/index.ts, packages/argo-admin-react/src/components/StackItem/index.ts, packages/argo-admin-react/src/components/Text/index.ts, packages/argo-admin-react/src/components/TextField/index.ts, packages/argo-admin-react/src/components/Thumbnail/index.ts
Related to esnext issue https://github.com/Shopify/argo-private/issues/1524#issuecomment-852318742
TS is very strict when it comes to exporting from another package. argo-admin-react re-exports component props from argo-admin so we need to explicitly set these as a type export
1. Run `yarn build` and verify that both argo-admin-react and argo-admin compiles
=> argo-admin-react: fix component props exports

packages/argo-admin-react/src/index.ts, packages/argo-admin/src/extension-points/index.ts, packages/argo-admin/src/index.ts
In the `main` branch, run `yarn clean; yarn clear-cache; yarn build`. In `packages/argo-admin/build/esm`, you’ll see import statements referencing empty files. This prevents argo-admin from being used with skypack: <https://cdn.skypack.dev/@shopify/argo-admin>.
Always use `export type` when exporting types, so the bundler knows to strip them out.
Run `yarn clean; yarn clear-cache; yarn build` on this branch and you should see no references to types in `build/esm`. ie `build/esm/index.mjs` shouldn't reference `extension-points` at all, as only types are exported from there.
=> Use 'export type' in argo-admin

scripts/typedoc/shopify-dev-renderer/shared.ts, scripts/typedoc/utilities/dependency-graph.ts
Currently we strip newlines from jsdoc comments in a way that makes it impossible to render markdown lists, ie
```
/** Represents an error occurred while calculating or applying a changeset.
*
* **Possible values for `code`:** 
*
* - `payment_required` - The original payment method couldn't be charged.
* - `insufficient_inventory` - An item requested to be added is out of stock.
* - `changeset_already_applied` - Indicates if the changeset has been applied. Changesets can only be applied once.
* - `unsupported_payment_method` - Indicates that the payment method was unsupported. The payment method used to pay for the initial purchase can't be used to pay for changesets.
* - `invalid_request` - The request is invalid. It shouldn't be re-sent without modifications.
* - `server_error` - An …
```
=> Render markdown lists in docs builder

packages/argo-post-purchase/src/components/TextField/TextField.ts, packages/argo-post-purchase/src/extension-points/render-extension.ts, packages/argo-post-purchase/src/extension-points/types.ts
The brand _App Bridge_ is publicly facing, but the library code should stay unbranded.
Removing all mentions of _App Bridge_ from the code (these were added in #136 )
=> remove the brand 'App Bridge' from .ts files

packages/ui-extensions/src/types/Button.ts, packages/ui-extensions/src/types/index.ts
Closes: https://github.com/Shopify/argo-private/issues/1487
Relates to: https://github.com/Shopify/argo-rfcs/issues/2
This adds the `BaseButtonProps` decided on in this RFC discussion. These props are not yet consumed by either ui-extensions library. 
- This API is not yet consumed and has no impact on the ui-extensions libraries.
=> add BaseButtonProps

packages/ui-extensions/package.json
Admin client package need to reference `@shopify/ui-extensions` and it has to be public so our partners can access it
Update publish settings to be public
- ...
=> Update @shopify/ui-extensions publish settings to be public

packages/argo-admin/package.json
`@shopify/ui-extensions` should be a dependency since we are re-exporting types from this package
=> Update admin dependency

packages/ui-extensions/src/types/Heading.ts, packages/ui-extensions/src/types/index.ts
Closes: Shopify/argo-private#1498
Relates to: Shopify/argo-rfcs#9
This adds the `BaseHeadingProps` to the shared `ui-extensions` package. These props are not yet consumed by either ui-extensions library.
This is a pretty straightforward addition to the shared APIs, considering that it is a new component for Admin and matches Checkout's current implementation. 
I do have one question for the Admin team that I overlooked during the RFC discussion.
What should the default heading level be?
In Checkout, the heading will use its “automatic” heading level, which is determined by the level of nesting within ancestor `HeadingGroup`. At this point, we have not discussed creating a `HeadingGroup` in Admin. Is it reasonable to make the default level `1`? (I know this is an implementation detail, but …
=> Add BaseHeadingProps to shared types

packages/checkout-ui-extensions/src/components/Text/README.md, packages/checkout-ui-extensions/src/components/Text/Text.ts, packages/post-purchase-ui-extensions/src/components/Text/README.md, packages/post-purchase-ui-extensions/src/components/Text/Text.ts, packages/post-purchase-ui-extensions/src/extension-points/api/post-purchase/post-purchase.ts, scripts/typedoc/shopify-dev-renderer/shared.ts, scripts/typedoc/types.ts, scripts/typedoc/utilities/dependency-graph.ts
Union of TSTypeLiteral is not parsed correctly.
```ts
type CalculateChangesetResult =
| {
errors: ChangesetError[];
status: 'unprocessed';
calculatedPurchase?: never;
}
| {
errors: ChangesetError[];
status: 'processed';
calculatedPurchase: CalculatedPurchase;
};
```
is rendered like this
A similar issue is encountered in the `Text` component docs:
Refactor the problematic union types by extracting `TSTypeLiteral`s into separate types that can be handled just fine by the current script.
=> Refactor complex union types

packages/post-purchase-ui-extensions/src/extension-points/api/post-purchase/post-purchase.ts
Following the implementation in core (see https://github.com/Shopify/shopify/pull/298195), we're now updating the post-purchase types to include the `changesetApplicationsRemaining` attribute.
You can see more information on the PR liked above, but in summary, it returns how many changesets a partner can still apply to an initial purchase. This is important for payment gateways that only support one changeset per initial purchase, like PayPal express.
Just adding the type, along with a brief description.
=> Add changesetApplicationsRemaining to post-purchase types

packages/checkout-ui-extensions-run/package.json, packages/checkout-ui-extensions-run/src/dev.ts, packages/checkout-ui-extensions-run/src/utilities.test.ts, packages/checkout-ui-extensions-run/src/utilities.ts, packages/checkout-ui-extensions-run/src/webpack-config.ts, yarn.lock
Today's checkout extension developer experience isn't ideal because developers have to manually assemble checkout links to test their extension.
To improve this experience, Shopify CLI will pass `--resourceUrl` and `--store` in future, which can be used to assemble a cart permalink as follows:
```
https://<store>/<resourceUrl>?dev=<publicUrl>/query
```
Outputting this link instead of just the query parameters will enable developers to create a new checkout with just one click.
**Setup**
1. Create a new Checkout or Post Purchase extension using the CLI
2. In this repo, run after `yarn build-consumer <relative-path-to-checkout-extension> checkout-ui-extensions-run`
Running 
```
❯ yarn start --port=39351 --publicUrl=https://809671a3c94f.ngrok.io --store=t6d-dev.myshopify.io …
```
=> Support for Checkout One Deeplinks

packages/ui-extensions/src/index.ts, packages/ui-extensions/src/types/index.ts, scripts/typedoc/types.ts, scripts/typedoc/utilities/dependency-graph.ts
Closes https://github.com/Shopify/ui-extensions/issues/132
:warning: based on https://github.com/Shopify/ui-extensions/pull/166
We’re starting to store types in a shared package (`ui-extensions`) and extend them to produce our public interfaces. The doc generation script isn’t capable of following those imports, therefore the generated docs are missing information.
[`Banner`](https://github.com/Shopify/ui-extensions/blob/main/packages/admin-ui-extensions/src/components/Banner/Banner.ts#L12) is the only component consuming a remotely imported type at the time of this PR.
[`PostPurchaseShouldRenderApi`](https://github.com/Shopify/ui-extensions/blob/38e3adacc084152591126acf89e1094db94be568/packages/post-purchase-ui-extensions/src/extension-points/api/post-purchase/post-purchase.ts#L5-L11) …
=> [Docs script] Resolve imported types

package.json
Add a command to publish new versions for post-purchase packages.
Copy the same command from admin and checkout and filter out checkout-ui-extensions.
- ...
=> Add post-purchase version bump command

scripts/generate-docs-checkout.ts, scripts/typedoc/shopify-dev-renderer/extension-points.ts, scripts/typedoc/shopify-dev-renderer/getting-started.ts
The docs generation for Post-purchase extensions docs and `beta` Checkout extensions docs are using the same template, so there's no way to show different heading depending on the docs subject.
Use a `title` variable instead of the hardcoded title and pass it as an argument to the docs generator function.
=> Extract title variable

packages/admin-ui-extensions/src/components/Button/Button.ts
Mobile does not have a clean way to handle `Button.submit`, so we will remove it for the time being.
- ...
=> feat: remove button submit

scripts/build-consumer-spin.sh, scripts/consumer-helper.sh, scripts/restore-consumer-spin.sh
Improve build-consumer and restore-consumer scripts for Spin so you don't have to type out the full workspace names
- Create a spin instance for Web
- Run `yarn build-consumer-spin web admin-ui-extensions`
- Open the Web spin instance and inspect the node modules to ensure the package content was copied over
=> chore: update build-consumer and restore-consumer for spin to work with short form workspace name

.github/workflows/admin-rc.yml
Ticket https://github.com/Shopify/ui-extensions-private/issues/1635
This is a GitHub Action task to rebase admin-rc everytime something merges into main. There is no error handling until we get permissions to add environment variables.
- Check out `rebase-test-main`. This will have the auto-rebase from `rebase-test-main` to `rebase-test-admin-rc`
- Create a new branch off it called `rebase-test-admin-rc` and push it up.
- Make a change on `rebase-test-main` and push force push it up (or do a PR merge if that doesn't work).
- Go to the [github workflows](https://github.com/Shopify/ui-extensions/actions/workflows/admin-rc.yml) and make sure it  pushes up the task. If it green-lights then it means rebase is complete.
- Pull latest `rebase-test-admin-rc` and see the rebase works.
- Clean up: …
=> add admin-rc.yml

packages/admin-ui-extensions-react/src/components/InlineStack/InlineStack.ts, packages/admin-ui-extensions-react/src/components/InlineStack/examples/InlineStack.example.tsx, packages/admin-ui-extensions-react/src/components/InlineStack/index.ts, packages/admin-ui-extensions-react/src/components/index.ts, packages/admin-ui-extensions/src/component-sets/Basic.ts, packages/admin-ui-extensions/src/components/InlineStack/InlineStack.ts, packages/admin-ui-extensions/src/components/InlineStack/content/guidelines.md, packages/admin-ui-extensions/src/components/InlineStack/examples/InlineStack.example.tsx, packages/admin-ui-extensions/src/components/InlineStack/index.ts, packages/admin-ui-extensions/src/components/index.ts, packages/admin-ui-extensions/src/index.ts
As part of the [Argo API Alignment project](https://docs.google.com/document/d/1LeZmHDT1Tr-XT5Xj-uwjRFlwis-asmM5zwp2VTj-oOw/edit#heading=h.vkiyv6kr3azd) we need update and/or add the following components to the library.
This PR adds the `InlineStack` component to the `admin-ui-extensions` and to the `admin-ui-extensions-react` packages.
- Checkout the `feat/ui-extensions/1493/block-stack-web` branch on [shopify/ui-extensions](https://github.com/Shopify/ui-extensions), [shopify/admin-ui-extensions](https://github.com/Shopify/admin-ui-extensions) and [shopify/web](https://github.com/Shopify/web)
- In `ui-extensions`, run `yarn build-consumer web` and `yarn build-consumer admin-ui-extensions/packages/admin-ui-extensions-playground`. This will make the local changes available in both …
=> Create InlineStack in Argo client and hosts

packages/checkout-ui-extensions-run/src/dev.ts
In certain situations, `checkout-ui-extensions-run serve` will explain how to start a tunnel. The command was for pre-2.0 `shopify` CLIs so it is now outdated.
I updated the command.
Run `checkout-ui-extensions-run serve`
=> Update shopify CLI instructions for shopify 2.x

README.md, packages/admin-ui-extensions-react/README.md
There is a small typo in the `README.md` when linking back to the "I want to build an extension" section, as well as in `packages/admin-ui-extensions-react/README.md` when clicking into the components directory.
Fix the anchor.
- [Render the `README.md` change as Markdown and click the link](https://github.com/Shopify/ui-extensions/blob/update-link-anchor-in-readme/README.md). It should take you to the appropriate heading.
- [Render the `admin-ui-extensions-react/README.md` change as Markdown and click the link](https://github.com/Shopify/ui-extensions/blob/update-link-anchor-in-readme/packages/admin-ui-extensions-react/README.md)
=> Update link anchor in README

packages/checkout-ui-extensions-run/src/dev.ts
The post-purchase browser extension has a feature where partners can update their `extension.config.yml` file and every 30 seconds or when partners click a `Refresh` button, the browser extension will query the `/data` endpoint and collect the metafields information.
At the moment, this is broken since the `extension.config.yml` file is read once on startup and we reuse the value for every subsequent requests.
Instead of using the value queried when the server starts, read the file every time for the post-purchase endpoint only.
I've tophatted this with both the refresh button and the 30 second delay succesfully.
The simples way to tophat is to edit the file in the node_modules of the reference extension to add the new line :
`node_modules/@shopify/checkout-ui-extensions-run/build/node/dev …
=> Fix checkout-ui-extensions-run /data endpoint to reflect the latest values in the config file

packages/post-purchase-ui-extensions/src/extension-points/api/post-purchase/post-purchase.ts
- Updates a few anchor links in the metafields documentation
- Relates to https://github.com/Shopify/shopify-dev/pull/16261 and https://github.com/Shopify/shopify-dev/issues/15878
=> Updates anchor links to metafields documentation

packages/retail-ui-extensions/.gitignore, packages/retail-ui-extensions/.npmignore, packages/retail-ui-extensions/package.json, packages/retail-ui-extensions/sewing-kit.config.ts, packages/retail-ui-extensions/tsconfig.json
We're starting to move our UI components from our private repo to this one. This PR is to start setting up the project, however we don't want to publish anything just yet.
I've copied the layout for admin-ui-extensions as the way we've set it up in our private repo has been heavily inspired by this.
=> Added retail-ui-extensions package

packages/post-purchase-ui-extensions/src/extension-points/api/post-purchase/post-purchase.ts
_(Draft until https://github.com/Shopify/shopify/pull/339101 is shipped)_
I introduced a new error code on this PR: https://github.com/Shopify/shopify/pull/339101
Add new error code to post purchase `ChangesetErrorCode` type.
- ...
=> Add new changeset post purchase error code

package.json
Adds a new command to bump the retail package versions so we can release new versions.
Same command as for the other packages, except for the retail packages.
Try out the new command!
=> Added command to bump retail packages

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.5.0
- @shopify/retail-ui-extensions@0.5.0
This adds globalThis instead of self which resolves compatibility issues with POS.
globalThis is more modern, and is suppored by POS.
- ...
=> Bump retail packages to 0.5.0 to solve build issues (again)

packages/checkout-ui-extensions/documentation/components.md, packages/checkout-ui-extensions/src/components/Choice/Choice.ts, packages/checkout-ui-extensions/src/components/Choice/README.md, packages/checkout-ui-extensions/src/components/Choice/content/guidelines.md, packages/checkout-ui-extensions/src/components/ChoiceList/content/guidelines.md, packages/checkout-ui-extensions/src/components/Grid/content/guidelines.md, packages/checkout-ui-extensions/src/components/GridItem/content/guidelines.md, packages/checkout-ui-extensions/src/components/List/content/guidelines.md, packages/checkout-ui-extensions/src/components/ListItem/ListItem.ts, packages/checkout-ui-extensions/src/components/ListItem/README.md, packages/checkout-ui-extensions/src/components/ListItem/content/guidelines.md, scripts/generate-docs-checkout.ts
Closes https://github.com/Shopify/checkout-web/issues/11053
=> Checkout: give subcomponents their own docs page

packages/checkout-ui-extensions/documentation/components.md
https://github.com/Shopify/checkout-web/issues/11127
- port changes from `checkout-web` to `ui-extensions`
=> Checkout UI components overview: Port changes from 11173 in checkout-web

packages/checkout-ui-extensions/documentation/components.md, packages/checkout-ui-extensions/documentation/extension-points.md
https://github.com/Shopify/checkout-web/issues/10972
Add calls in Liquid to the partial files in `shopify-dev` for the checkout UI ext. dev preview and shopify plus callouts.
`/api/checkout-extensions/checkout/extension-points`
`/api/checkout-extensions/checkout/components`
=> Update pages with calls to partials in `shopify-dev`

scripts/typedoc/shopify-dev-renderer/components/components.ts
My bad. A mistake I made in this [PR](https://github.com/Shopify/ui-extensions/pull/353/files#diff-1a9d5deedb03802d52931231bad2116a381e9bf41777211186a80df0a09eac74R351-R356) that I only noticed now that we have mp4+webm files in shopify-dev.
=> [Checkout Docs] Update path for fs.existsSync when searching for webm files

packages/checkout-ui-extensions/src/components/Stepper/Stepper.ts, packages/checkout-ui-extensions/src/components/TextField/TextField.ts
The Stepper component now returns `undefined` as callback value when the field is cleared by the user.
PR for the implementation in Checkout:
https://github.com/Shopify/checkout-web/pull/11577
=> [Checkout Extensions] Accept undefined as callback value in Stepper

packages/checkout-ui-extensions-react/src/render.tsx, packages/customer-account-ui-extensions-react/src/render.tsx
Address issue https://github.com/Shopify/ui-extensions/issues/325
This PR is a port of @marvinhagemeister done at the source.
https://github.com/Shopify/checkout-web/pull/11674
I've also set the same logs in the `customer-account-ui-extensions-react` which is a recent copy of the Checkout render function.
=> Workaround for extension errors not shown during initial render

packages/checkout-ui-extensions/src/components/SkeletonText/SkeletonText.ts, packages/checkout-ui-extensions/src/components/SkeletonTextBlock/SkeletonTextBlock.ts
Port over fix created by @ncardeli  https://github.com/Shopify/checkout-web/pull/11649
=> [Checkout Extensions] Pick size and redefine emphasis in Skeletons

scripts/generate-docs-checkout.ts
The `checkout_extensions` feature flag for Shopify.dev is no longer needed.
To generate reference docs without the `feature_flag` key/value in frontmatter, rm `visibility: 'betaCheckoutExtensions'` from `generate-docs-checkout.ts`
Companion PR to https://github.com/Shopify/shopify-dev/pull/23161
Can't currently tophat due to type resolution errors and a RangeError (Maximum call stack size exceeded)
=> Remove the `checkout_extensions` feature flag from generated checkout UI pages

packages/customer-account-ui-extensions-react/src/render.tsx, packages/customer-account-ui-extensions/src/extension-points/extension-points.ts, packages/customer-account-ui-extensions/src/extension-points/index.ts, packages/customer-account-ui-extensions/src/extension-points/standard-api.ts
Part of https://github.com/Shopify/core-issues/issues/39405. We now expose the `customerApi` property with 2 methods, which allows the extension to call the Customer API themselves.
Implemented both as asynchronous methods instead of a `RemoteSubscribable` as initially planned, because obtaining the first access token is asynchronous in Self-Serve itself, and we don't want to block the initial rendering while we obtain it.
The Customer API only supports the `unstable` version for now, which is fine for internal use. We'll add more versions as the Customer API actually becomes versioned.
I've had to add the `CustomerAccount::KitchenSink` extension point, similar to the one they have in Checkout, because having a second extension point with a different API was making our typing fail. Adding …
=> Add GraphQL endpoint to extension API

packages/customer-account-ui-extensions-react/src/index.ts, packages/customer-account-ui-extensions/src/index.ts, packages/customer-account-ui-extensions/src/style/index.ts
This PR exposes `checkout-ui-extensions`'s `Style` helper, which allows for conditional styles ([example](https://shopify.dev/api/checkout-extensions/checkout/components/grid#getting-started)) on a number of checkout components. The Shopify Returns extension will make use of `Style` to achieve mobile/desktop layouts.
- Import `Style` helper from `checkout-ui-extensions`
- Export `Style` helper from both React and vanilla `customer-account-ui-extensions` packages
🍋 **[My Spin instance](https://mobile-layout.kim-hawthorne.us.spin.dev/)**
In this Spin instance, the Shopify Returns app is using the `Style` helper to render conditional layouts based on viewport size. To test, ensure that the two main content containers are stack in mobile and are side-by-side in desktop.
**Desktop**
**Mobile** …
=> expose `Style` helper to customer-account-ui-extensions packages

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions-react/src/hooks/index.ts, packages/customer-account-ui-extensions-react/src/hooks/subscription.ts, packages/customer-account-ui-extensions-react/src/hooks/tests/subscription.test.ts, packages/customer-account-ui-extensions-react/src/index.ts, packages/customer-account-ui-extensions/package.json, packages/customer-account-ui-extensions/src/extension-points/extension-points.ts, yarn.lock
Part of https://github.com/Shopify/core-issues/issues/42207. Exposes the current route data to full page extensions so they can do internal routing themselves.
In addition to adding the `location` property in the API, this PR also adds a new hook called `useSubscription` that extensions can use in order to unwrap a `StatefulRemoteSubscribable` from the API. The hook simply transforms the subscribable into a reactive value within React's lifecycle.
Added our first test for the newly introduced hook.
=> Expose location to full page extensions

packages/customer-account-ui-extensions-react/tsconfig.json, packages/customer-account-ui-extensions/tsconfig.json
I added a test in https://github.com/Shopify/ui-extensions/pull/428, and these files are not excluded from our tsconfig.json as they should be.
Excluded tests from both `tsconfig.json`
=> [Customer Account] Exclude tests from tsconfig.json

yarn.lock
Seems like yarn.lock wasn't checked in with a recent change in dependencies.
Running yarn on a fresh main produces a diff in yarn.lock
=> add missing yarn.lock

packages/customer-account-ui-extensions/src/extension-points/standard-api.ts
Part of 
- https://github.com/Shopify/core-issues/issues/39485.
2 new methods have been added to the `StandardApi`, under the `router` property.
`getExtensionFullPageUrl` accepts a relative path and returns a path leading to the full page extension of the calling app. This can be used by extensions to generate links to their full page extension to start a flow.
`navigate` accepts a URL and navigates the browser to it. It can be an absolute URL, in which case the customer leaves Customer Account. Or it can be a relative URL, in which case the customer goes to that page within Self-Serve.
1. Spin instance: https://buyer-returns-gsq3.mathieu-lagace.us.spin.dev
1. Authenticate to Customer Account
1. Register the app locally by using the first link to Customer Account.
1. In the console, you …
=> [Customer Account] Add navigate and getExtensionFullPageUrl methods to StandardApi

packages/web-pixels-extension/src/types/web-pixel-api.ts
ISSUE: https://github.com/Shopify/ce-customer-behaviour/issues/1461
we must rename `configuration` to `settings` in the Runtime API.
Adding in an optional `settings` property to support the transition until we are confident in the solution downstream
- ...
=> added optional field  to web pixel RuntimeAPI

packages/retail-ui-extensions-react/src/context.ts, packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions-react/src/render.tsx
There are still a few places in our react package where we specify `src` in imports from packages. Since the imports are coming from the vanilla package, we should just import it directly as everything in that package is exported properly. 
Just removes the src from paths and import from the package.
Everything should build normally. It's still importing the same thing, but from the correct path (which points to the correct build output)
=> Removed src from file imports

packages/ui-extensions/src/types/Button.ts
The default value of kind in the Button is `secondary` and not `primary` [more details in the issue here](https://github.com/Shopify/ui-extensions-private/issues/1674)
Change the documentation to `secondary`
=> Change kind's @default value to secondary in documentation

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions-react/src/index.ts
Need to reexport the CountryCode type so the React index looks the same as the vanilla one
Reexport!
- ...
=> Reexport CountryCode in retail-ui-extensions-react

packages/retail-ui-extensions/src/extension-api/cart-api/cart-api.ts
While working on implementation of cart API calls in POS, I noticed that `setLineItemDiscount` takes uuid as number. However all other calls uses uuid as string which also matched how redux state stores the lineItem uuid
This PR is a tiny change to change the type to string to match all other calls
- ...
=> Change uuid type to match other api calls and POS redux state

packages/admin-ui-extensions/package.json
Fixes: https://github.com/Shopify/shopify-cli-extensions/issues/383
Missing exports in the package.json had extensions build failing
Added missing exports
=> Add missing exports to package.json for admin-ui-extensions to fix build issue

packages/checkout-ui-extensions-react/package.json, packages/checkout-ui-extensions/package.json, packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
- @shopify/checkout-ui-extensions-react@0.20.0
- @shopify/checkout-ui-extensions@0.20.0
- @shopify/customer-account-ui-extensions-react@0.0.19
- @shopify/customer-account-ui-extensions@0.0.19
This PR bumps the versions and will be used to publish the packages. It is a follow-up to https://github.com/Shopify/ui-extensions/pull/520.
Followed [package release steps](https://github.com/Shopify/ui-extensions-private/wiki/Release-steps:-Admin-and-Checkout-ui-extensions).
=> Publish checkout-ui-extensions `0.20.0`

packages/retail-ui-extensions-react/src/extension-api/cart-api/cart-api.ts, packages/retail-ui-extensions-react/src/extension-api/cart-api/index.ts, packages/retail-ui-extensions-react/src/extension-api/index.ts, packages/retail-ui-extensions-react/src/extension-api/locale-api/index.ts, packages/retail-ui-extensions-react/src/extension-api/locale-api/locale-api.ts, packages/retail-ui-extensions-react/src/extension-api/utils.ts, packages/retail-ui-extensions-react/src/index.ts
This PR adds three new hooks: 
1. useExtensionApi - Allows the developer to access the different API functions on the Cart, navigation etc.
2. useCart - Is a wrapper around the setOnChange handler, that acts as a subscription to Cart updates.
3. useLocale - Is a wrapper around the setOnChange handler, that acts as a subscription to Locale updates.
This is following the same standard pattern as set in admin-ui-extensions-react
You'll need to be running a POS UI extension project using React. Make sure your index file is a `tsx` file.
1. You can use yalc to publish this dependency locally on your machine. Then add the dependency to your CLI project.
2 Alternatively (easier) you can copy all the files in this PR, and add them to your local project (this should work). Then call the hooks! …
=> Wrapped Retail on changes in hooks

packages/retail-ui-extensions/src/extension-api/navigation-api/navigation-api.ts, packages/retail-ui-extensions/src/extension-api/smartgrid-api/smartgrid-api.ts
This is the API we are providing for UI extensions to be able to navigate to other screens. It's not a great API, but we just need something that will work for beta, so Stocky can internally build and test out our features.
This API does not resemble anything like what is available in react-native such as react-navigation. To be honest, those libraries are full of clutter in my opinion, and having to define stacks and routes is not only a waste of code, but it doesn't feel native and it's confusing.
The advantage to this solution is that: 
1. The developer only needs to call one function. It feels very similar to native navigation APIs, think of `navigationController.push(detailsViewController)` in UIKit, or `NavigationLink(destination: DetailView` in SwiftUI.
2. State is preserved across …
=> Created experimental nav API for beta

packages/retail-ui-extensions/src/extension-api/types/session.ts
I'm connecting the new `SessionApi` to POS and `staffMemberId` can be `undefined`. 
Made the parameter optional in `SessionApiContext`. 
- ...
=> Made staff member id optional because it may not exist on POS

packages/retail-ui-extensions-react/src/components/Icon/Icon.ts, packages/retail-ui-extensions-react/src/components/Icon/index.ts, packages/retail-ui-extensions-react/src/components/index.ts, packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions/src/components/Icon/Icon.ts, packages/retail-ui-extensions/src/components/Icon/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Adds an icon component that will allow third party apps to render an Icon. I selected icons that I believe will be useful for third party apps.
Since POS defines the size and color of icons, I've decided only to expose the icon name.
=> Added an Icon component

packages/retail-ui-extensions/src/extension-api/navigation-api/navigation-api.ts
https://github.com/Shopify/pos-next-react-native/issues/17742
Added `params` variable to `NavigationApiContent`. Currently the type is `any` to not overcomplicate things, in the future we modify the function to accept interfaces. 
- ...
=> Added params to the API

packages/retail-ui-extensions/src/components/Stack/Stack.ts
Added import type to horizontal and vertical spacing that the linter didn't catch.
=> Fix import typo in Stack

packages/retail-ui-extensions/src/extension-api/navigation-api/navigation-api.ts
Partners should have to provide params when pushing a new screen. 
Made the params optional. 
- ...
=> Made the params optional for navigation

packages/web-pixels-extension/package.json
- @shopify/web-pixels-extension@0.3.0
Recently updated the web pixels extension types. This PR publishes the changes under a new version.
Should ship after https://github.com/Shopify/web-pixels-manager/pull/161
- `yarn version-bump:web-pixels`
- pushed branch with `--follow-tags`
- ...
=> Publish `@shopify/web-pixels-extension@0.3.0`

packages/retail-ui-extensions/src/component-sets/Basic.ts, packages/retail-ui-extensions/src/components/Section/Section.ts
I realized there's no enabled prop on the POS side for the header action. I also made the hideSeparator optional so we can implement a default value of false.
=> Fixed a couple things for Section

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
- @shopify/customer-account-ui-extensions-react@0.0.22
- @shopify/customer-account-ui-extensions@0.0.22
Contains the following change:
[authenticatedRedirect.getStartUrl](https://github.com/Shopify/ui-extensions/pull/598)
=> Publish [customer-account-ui-extensions@0.0.22] - Add 'authenticatedRedirect.getStartUrl' to the StandardApi

packages/retail-ui-extensions/src/extension-api/navigation-api/navigation-api.ts, packages/retail-ui-extensions/src/extension-api/smartgrid-api/smartgrid-api.ts
https://github.com/Shopify/pos-next-react-native/issues/17783
Added an interface to show a modal from NavitationAPI. 
- ...
=> Navigation API modal support

packages/retail-ui-extensions/src/extension-api/navigation-api/navigation-api.ts
I was working on https://github.com/Shopify/pos-next-react-native/issues/17783 and it makes sense to include a `pop` function in our navigation, even if the navigation itself ends up being temporary. Having the option to only dismiss the whole modal doesn't make much sense. 
Added the interface for the `pop` function. 
- ...
=> Navigation API pop function

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
version bump for
`retail-ui-extensions` and `retail-ui-extensions-react` to 0.33.
- ...
=> upgrading retail-ui-extensions version

packages/admin-ui-extensions-react/package.json, packages/admin-ui-extensions/package.json, packages/checkout-ui-extensions-react/package.json, packages/checkout-ui-extensions/package.json, packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json, packages/post-purchase-ui-extensions-react/package.json, packages/post-purchase-ui-extensions/package.json, packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json, yarn.lock
`@remote-ui/core@2.2.0` and `@remote-ui/react@4.6.0` make use of new core APIs for manipulating the remote root. However, the current structure of most remote-ui uses at Shopify has the host owning the version of `@remote-ui/core`, and none of them have support for the new APIs yet. Most developers will get the new version of `@remote-ui/react` because it is only a minor version, but because `@remote-ui/react` assumes it has the correct version of `@remote-ui/core`, it will break when run in a host with an older version.
Until hosts are updated to use the new version of `@remote-ui/core`, this PR pins all versions of remote-ui to the ones before the new APIs were added. This prevents consumers installing these versions of the packages from accidentally getting code depending on …
=> Pin remote UI versions

packages/admin-ui-extensions/README.md
They were added as relative and ending up as `https://github.com/Shopify/ui-extensions/blob/main/packages/admin-ui-extensions/packages/admin-ui-extensions/src/components` when clicked.
Fixes https://github.com/Shopify/ui-extensions/issues/669
Add `/` to the links.
=> fix documentation links #669

scripts/typedoc/shopify-dev-renderer/shared/index.ts
PII callouts were initially manually added to release faster, but now they are getting overridden every time docs are generated.
Closes https://github.com/Shopify/checkout-web/issues/14022
I've added automatic appends until we have a better tool for this.
- pull this branch
- pull the `shopify-dev` repo
- run `yarn docs:checkout` in this repo
- in the `shopify-dev` repo run `dev run`
- check callouts are present in [this page](https://shopify-dev.myshopify.io/api/checkout-extensions/checkout/extension-points/api)
=> Automatically generate PII callouts

.github/workflows/changesets-reminder.yml, .github/workflows/changesets.yml, .github/workflows/deploy.yml, .github/workflows/unstable-snapshot.yml
This PR adds changeset actions to publish versioned branches containing the `@shopify/ui-extensions` package. It covers the three current version branches:
- [2022-10](https://github.com/Shopify/ui-extensions/tree/2022-10)
- [2023-01](https://github.com/Shopify/ui-extensions/tree/2023-01)
- [unstable](https://github.com/Shopify/ui-extensions/tree/unstable)
For the stable branches, the behavior is the following:
- When a PR is made targetting the branch, it will get a warning if it changes source code but does not provide a changeset
- Every merge into the branch will be tracked by changesets, and when there are unmerged changes, it will create a `changeset-release/<VERSION>` branch. That branch will contain a preview of what is ready to be released
- When we are comfortable with a …
=> Add changeset actions

scripts/typedoc/shopify-dev-renderer/extension-points.ts, scripts/typedoc/shopify-dev-renderer/shared/index.ts
[Slack thread](https://shopify.slack.com/archives/C04848YTM0F/p1674169208981939)
I [published an internal change](https://github.com/Shopify/checkout-web/pull/16456) and annotated the field with `@private`, but docs were still generated for the field and it appeared on the docsite:
This PR introduces a new option `excludePrivateFields` that suppresses properties annotated with `@private` in the generated docs.
- Check out shopify/ui-extensions locally
- Check out shopify/shopify-dev locally
- Add a `@private` interface type to any interface in [checkout-ui-extensions/ ... /index.ts](https://github.com/Shopify/ui-extensions/blob/main/packages/checkout-ui-extensions/src/extension-points/api/standard/index.ts). For example:
```ts
interface CartLine {
/** @private */
__lineComponents: <some …
```
=> Added option to exclude @private annotated fields from docgen

packages/customer-account-ui-extensions-react/src/components/Card/Card.ts, packages/customer-account-ui-extensions-react/src/components/Card/index.ts, packages/customer-account-ui-extensions-react/src/components/index.ts, packages/customer-account-ui-extensions/src/components/Card/Card.ts, packages/customer-account-ui-extensions/src/components/Card/index.ts, packages/customer-account-ui-extensions/src/components/index.ts
Main issue: https://github.com/Shopify/core-issues/issues/49805
Required for: 
- https://github.com/Shopify/customer-account-web/pull/1573
- https://github.com/Shopify/buyer-returns/pull/153
[Spinstance](https://buyer-returns-5fkg.brooks-ilg.us.spin.dev/)
1. Go to [Returns extension inside Customer Account →](https://shop1.account.shopify.buyer-returns-5fkg.brooks-ilg.us.spin.dev/e/dev?dev=https://customer-account-web.buyer-returns-5fkg.brooks-ilg.us.spin.dev/proxy?target=https://buyer-returns.buyer-returns-5fkg.brooks-ilg.us.spin.dev/main.js)
2. Log in as `brooks.ilg@shopify.com`
3. Use one-time-passcode from [Identity Mailer →](https://identity.buyer-returns-5fkg.brooks-ilg.us.spin.dev/servic …
=> Make Card component available to ui-extensions

packages/retail-ui-extensions/src/components/Stack/Stack.ts
Typing is broken for Horizontal and Vertical spacing of a stack.
- ...
=> Change import

packages/retail-ui-extensions/src/components/Button/Button.ts
Closes https://github.com/Shopify/pos-next-react-native/issues/19328
- Currently UI Extensions miss loading state on the button to indicate that the associated button action is in progress. We want to update the button props interface to include loading information
- added property `isLoading` to the `ButtonProps` interface
- ...
=> added isLoading to the button props interface

packages/admin-ui-extensions/src/extension-points/identifiers/bundles.ts, packages/admin-ui-extensions/src/extension-points/identifiers/product_configuration.ts, packages/admin-ui-extensions/src/extension-points/index.ts
Adding a new extension point `Admin::Product::Bundles::Render`
We were going to implement this in the new `ui_extensions` spec, but due to time constraints, we're de-pivoting to implement in the old `@shopify/admin-ui-extensions` package (but the `ui_extensions` spec will still be used)
- ...
=> adding bundles extension point

.changeset/angry-rabbits-occur.md, packages/ui-extensions-react/package.json, packages/ui-extensions/package.json
While testing this library using the CLI, I got this error when trying access the esm exports
This PR fixes the exports for Checkout to have the correct paths.
=> Fix checkout surface exports

packages/retail-ui-extensions/src/components/List/List.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/20746
When the List component reaches the end, we have a callback `onEndReached`. Here the developer can fetch more data. We recommend that when this happens, they flip `isLoadingMore` to `true`, so that a loading indicator can happen at the bottom of the list.
=> Added a boolean to trigger animation for lists on load more

packages/customer-account-ui-extensions/src/extension-points/index.ts
Shoutout to @Safi1012 with the eagles eyes for spotting this.
We weren't exporting this type properly, despite needing to use it in the hub (see:https://github.com/Shopify/customer-account-web/pull/1722)
- ...
=> chore(customer-account): export capability type

packages/customer-account-ui-extensions-react/README.md, packages/customer-account-ui-extensions-react/src/context.ts, packages/customer-account-ui-extensions-react/src/errors.ts, packages/customer-account-ui-extensions-react/src/hooks/api.ts, packages/customer-account-ui-extensions-react/src/hooks/index.ts, packages/customer-account-ui-extensions-react/src/hooks/tests/api.test.tsx, packages/customer-account-ui-extensions-react/src/hooks/tests/mount.tsx, packages/customer-account-ui-extensions-react/src/index.ts, packages/customer-account-ui-extensions-react/src/render.tsx, packages/customer-account-ui-extensions/src/extension-points/extension-points.ts, packages/customer-account-ui-extensions/src/extension-points/index.ts, packages/customer-account-ui-extensions/src/extension-points/types.ts
Resolves https://github.com/Shopify/core-issues/issues/43251
Most of the implementation was ~copied~ inspired by the checkout extensions with some minor type adjustments.
The tophat spinstance was created with a local built of the `customer-account-ui-extensions-react` package that uses the custom api hook. Look at [this commit](https://github.com/Shopify/customer-accounts-ui-extension-dev/commit/b54cc77f5298b8c37639d37cc2add32112401b19) for reference.
[Customer accounts on spinstance with working extension deployed](https://development-store-1.account.shopify.splendid-partners.silvio-schmidt.eu.spin.dev/e/f4cc3c44-14d7-4d69-b648-c2f54c929227)
- Go to the …
=> Create a custom hook "useExtensionApi" for the "customer-account-ui-extensions-react" package

.changeset/silent-ligers-know.md, packages/ui-extensions-react/src/surfaces/admin/components.ts, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.tsx, packages/ui-extensions/src/api.ts, packages/ui-extensions/src/surfaces/admin/api.ts, packages/ui-extensions/src/surfaces/admin/api/customer-segmentation-template/customer-segmentation-template.ts, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.ts, packages/ui-extensions/src/surfaces/admin/extension-points.ts, packages/ui-extensions/src/surfaces/checkout/api.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
Fixes https://github.com/Shopify/core-issues/issues/51784
We are building a new rendering UI extension for Customer Segmentation. We're introducing a new component called `CustomerSegmentationTemplate` that will be used to render segmentation templates in the Admin:
This PR adds the required interfaces for `CustomerSegmentationTemplate` in `@shopify/ui-extensions/admin` and `@shopify/ui-extensions-react/admin`. See code examples in PR.
🍏 CI. You can also generate a build (`yarn build`) and consume these new changes in your app extension.
=> Segmentation / Introduce `CustomerSegmentationTemplate` component

.changeset/sweet-ways-hunt.md, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts
Extensions need a way to provide which customer standard metafield they rely on. This PR introduces `standardMetafieldDependencies`. We're currently only supporting one customer standard metafield but this could change in the future.
More context in this [doc](https://docs.google.com/document/d/1Kd42wyOGL7fHIAqAlNbDCFcy2Hh012H2Y1kT08F8mWw/edit#heading=h.21aft6xgv5n4).
=> CustomerSegmentationTemplate / Add `standardMetafieldDependencies` prop

packages/retail-ui-extensions-react/src/render.tsx, packages/retail-ui-extensions/src/extension-points/extension-points.ts
https://github.com/Shopify/pos-next-react-native/issues/21278
- Updated pos ui extension points namespace
- `Retail::SmartGrid::Tile` -> `pos.home.title.render`
-  `Retail::SmartGrid::Modal` -> `pos.home.modal.render`
=> Updated POS UI Extension points namespace

.changeset/odd-bottles-argue.md, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.tsx, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.ts
We currently display a "New" badge for recently introduced templates. Apps can feed us the date of when the template was added and we will display the badge if the date is within a month.
I've made the prop optional because but we could just set it in the past for all existing templates. I'm open to suggestions.
- ...
=> CustomerSegmentationTemplate / Introduce `dateAdded` prop

.changeset/tasty-avocados-sparkle.md, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.tsx, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.ts
- Segmentation templates in web currently accept an array of strings for the `description`. Some templates contain several sentences, and others contain 1 sentence, so this PR allows a union type to facilitate both use cases in a backwards compatible way.
Please refer to background section
- ...
=> [CustomerSegmentationTemplate] Update `description` prop type

packages/retail-ui-extensions/src/components/Screen/Screen.ts
Because the UI Extension's navigator and screens render right away in the UI Extension context, devs can't rely on useEffect firing when the screen is actually presented.
This adds life cycle events to the `Screen` component which will be triggered from the useEffect hook on the host side.
- ...
=> Added life cycle events for screen

packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions/src/components/Modal/Modal.ts, packages/retail-ui-extensions/src/components/Screen/Screen.ts, packages/retail-ui-extensions/src/extension-api/index.ts, packages/retail-ui-extensions/src/extension-api/standard-api.ts, packages/retail-ui-extensions/src/extension-points/extension-points.ts, packages/retail-ui-extensions/src/index.ts
Turns out extending interfaces doesn't work very well in npm land. SMH. I'm also taking the liberty to fix the lacking auto complete for the navigation API and smart grid API. The only thing I can identify is lacking vs the other APIs is that it's not explicitly included in a type. So I've created two types that build on top of the StandardApi:
- SmartGridModalAPI
- SmartGridTileAPI
=> Fix types and extensions

packages/retail-ui-extensions-react/src/components/SearchBar/SearchBar.ts, packages/retail-ui-extensions-react/src/components/SearchBar/index.ts, packages/retail-ui-extensions-react/src/components/index.ts, packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions/src/component-sets/Basic.ts, packages/retail-ui-extensions/src/components/Screen/Screen.ts, packages/retail-ui-extensions/src/components/SearchBar/SearchBar.ts, packages/retail-ui-extensions/src/components/SearchBar/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
After a discussion with UI/UX team, we decided to keep this as a component. The UI on the POS side will get smaller, though. 
- Reverted my previous changes. 
- Removed the barcode parameter for near future until we implement the scanning functionality. 
- ...
=> Inline Search Bar update

packages/customer-account-ui-extensions-react/src/components/shared-components.ts, packages/customer-account-ui-extensions/src/components/shared-components.ts
Allows customer-account ui extensions to make use of the Modal component
[Customer Account Hub PR here](https://github.com/Shopify/customer-account-web/pull/1900) (tophatting instructions also there).
=> feat: expose modal component to customer account ui extensions

.changeset/ten-cooks-fry.md, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.tsx, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.ts
The `dateAdded` property introduced as a Date is not correctly proxied to our Web component. It has the same class instance limitations remote-ui mentions. (Only keeping prototype)
Use ISO 8601 string for dates and updated the examples.
=> change dateAdded to iso string

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@0.46.1
- @shopify/retail-ui-extensions@0.46.1
List didn't have correct props, updating the version to fix it.
Version bump
- ...
=> Retail UI Extensions patch update to fix the List component props

packages/retail-ui-extensions/src/components/List/List.ts
Adds the disclosure indicator to the list row right side. Optional, defaults to false.
=> Made disclosure indicator on right side optional

packages/customer-account-ui-extensions-react/src/components/shared-components.ts, packages/customer-account-ui-extensions/src/components/shared-components.ts
Allows customer account ui extensions to make use of the Popover component
Tophat instructions in accompanying customer account web pr https://github.com/Shopify/customer-account-web/pull/1971
=> Expose Popover component to customer account ui extensions

packages/retail-ui-extensions/src/components/List/List.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/23093
This makes the types resolve better on the extension end. I don't know why.
Make an extension without these changes. Note that hovering looks like this:
Make these changes to your dependency. Note that hovering now looks like this:
=> Use relative import for TagProps in List

packages/retail-ui-extensions/src/components/Banner/Banner.ts
partially_resolves https://github.com/Shopify/pos-next-react-native/issues/23438
Some partners might wish to display a banner but show no action. Zapiet requested this feature as a part of our EA agreement. 
Added a parameter. Added some documentation. 
- ...
=> Added a param to hide a banner action

packages/retail-ui-extensions/src/components/FormattedTextField/FormattedTextField.ts
These text field formatters don't actually work on the POS side, so we are removing them until we get support. This is a deep tech debt issue on POS, and might take some time to get the implementations working properly.
Build an extension and make sure all the remaining inputTypes work properly.
=> Removed unsupported textfield formatting types

packages/checkout-ui-extensions-react/src/hooks/buyer-journey.ts, packages/checkout-ui-extensions/docs/build-docs.sh, packages/checkout-ui-extensions/docs/reference/apis/standard.doc.ts, packages/checkout-ui-extensions/docs/reference/examples/buyer-journey-intercept/extension-banner.example.ts, packages/checkout-ui-extensions/docs/reference/examples/buyer-journey-intercept/extension-banner.example.tsx, packages/checkout-ui-extensions/docs/reference/examples/buyer-journey-intercept/page-level-error.example.ts, packages/checkout-ui-extensions/docs/reference/examples/buyer-journey-intercept/page-level-error.example.tsx, packages/checkout-ui-extensions/docs/reference/examples/buyer-journey-intercept/target-native-field.example.ts, packages/checkout-ui-extensions/docs/reference/examples/buyer-journey-intercept/target-native-field.example.tsx, packages/checkout-ui-extensions/docs/reference/examples/session-token-jwt.example.json, packages/checkout-ui-extensions/docs/reference/examples/session-token.example.ts, packages/checkout-ui-extensions/docs/reference/examples/session-token.example.tsx, packages/checkout-ui-extensions/docs/reference/examples/subscription.example.tsx, packages/checkout-ui-extensions/docs/reference/helper.docs.ts, packages/checkout-ui-extensions/docs/reference/hooks/buyer-journey-intercept.doc.ts, packages/checkout-ui-extensions/docs/reference/hooks/session-token.doc.ts, packages/checkout-ui-extensions/docs/reference/hooks/subscription.doc.ts, packages/checkout-ui-extensions/docs/staticPages/extension-overview.doc.ts, packages/checkout-ui-extensions/src/components/shared.ts, packages/checkout-ui-extensions/src/extension-points/api/index.ts, packages/checkout-ui-extensions/src/extension-points/api/shared.ts, packages/checkout-ui-extensions/src/extension-points/api/standard/index.ts, packages/checkout-ui-extensions/src/extension-points/extension-points.ts, packages/checkout-ui-extensions/src/extension-points/index.ts, packages/checkout-ui-extensions/src/index.ts
Brings the latest from checkout-ui-extension packages from `Shopify/checkout-web`. Primary purpose of this release is for documentation improvements.
Package changes include:
**Features**
- New `Checkout::PaymentMethod::Render` extension point (private preview) 
**Docs**
- Improved buyer journey intercept examples to showcase page-level and targeting validation error messages
- Cleanup of some old doc links
- Fix for link resolution on shopify-dev for anchor links when previewing in spin
- Added example for `useSubscription` hook
- Added examples for `sessionToken`
Upon merging, this commit will be linked to a corresponding [Shopify/shopify-dev](https://github.com/Shopify/shopify-dev/pull/32913) PR that represents the doc update.
You can tophat the packages following these …
=> Checkout-ui-extensions docs patch pre-publish 04-23

packages/web-pixels-extension/src/schemas/pixel-events.jtd.json
following https://github.com/Shopify/web-pixels-manager/pull/330, we want to reintroduce the `pixel-events.jtd.schema` so it [can be consumed](https://github.com/Shopify/ce-customer-behaviour/issues/2479) in the forthcoming code editor autocomplete [feature](https://github.com/Shopify/ce-customer-behaviour/issues/1536) in `/web`
exposes the schema publicly, which is already available in our dev docs so no risk there
...
=> include pixels schema json to be consumed in web

packages/retail-ui-extensions/src/extension-api/scanner-api/scanner-api.ts
Extension will not load if a developer attempts to access the `ScannerSubscriptionResult` interface but the entire  RemoteSubscribable is undefined. We can fix this by just making the interface props optional.
=> Revert scanner data subscribable to not be undefined

packages/web-pixels-extension/src/index.ts, packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/index.ts
followup of https://github.com/Shopify/web-pixels-manager/pull/338
get around web's webpack config by using a ts file here instead
you can see it working in [spin](https://admin.web.pixels-autocomplete-pt.eric-berndt.us.spin.dev/store/shop1/settings/customer_events/pixels/2)
=> web pixels: export schema as ts instead of js

packages/checkout-ui-extensions/docs/build-docs.sh
This brings over the script from `checkout-web` necessary to build API docs for checkout extensibility by API version. 
This has already been tophatted in this [PR in checkout-web](https://github.com/Shopify/checkout-web/pull/20484).
=> support for building checkout extensibility api doc versions

.eslintrc.js, packages/checkout-ui-extensions-react/.eslintrc.js, packages/checkout-ui-extensions-react/src/hooks/tests/translate.test.tsx, packages/checkout-ui-extensions-react/src/hooks/translate.ts
Related to https://github.com/Shopify/checkout-web/issues/19623 and https://github.com/Shopify/checkout-web/pull/20985.
This enables react eslint rules that are present and enforced in `checkout-web` and these rules should also be enforced here.
> Note
This needs to ship AFTER https://github.com/Shopify/checkout-web/pull/20985 and changes are pulled into this repo in order for CI to pass.
Check that this passes CI.
=> Enabled react eslint rules

README.md
Resolves https://github.com/Shopify/pos-next-react-native/issues/24307
Add a line to the README for POS UI Extensions, which links to Shopify.dev docs.
- Verify the link works
=> Add bullet for POS UI Extensions to README.md

packages/retail-ui-extensions/src/extension-api/cart-api/cart-api.ts
https://github.com/Shopify/pos-next-react-native/issues/24327
Adds the ability to add a cart note. This ends up populating the note field on an Order.
=> Added a function to add a cart note

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
As part of https://github.com/Shopify/ce-customer-behaviour/issues/2344
We are adding untranslated title to our WPM api. So our partners can get the untranslated version of the lineItem title!
https://constellation-pppx.henry-zhou.us.spin.dev/
If you go through a checkout flow, you can see that there is now the `untranslated_title` in addition to the regular title
=> add untranslated title to product schema

packages/retail-ui-extensions/src/extension-api/cart-api/cart-api.ts
Turns out we don't want 3P devs to have access to cart note as it could override the one the merchant puts in. The intention is for 3P devs to just use note attributes instead. In addition, I'm also making value optional on the cart discount function, as discount codes do not need this field.
- ...
=> Removed cart note function and made value optional on cart discount

packages/retail-ui-extensions/src/extension-api/cart-api/cart-api.ts
This provides two new functions to attribute staff to line items in the cart.
Here is what the code POS side would look like: 
https://github.com/Shopify/pos-next-react-native/pull/24657
- ...
=> New API functions to set staff to line items

packages/customer-account-ui-extensions/src/components/Card/Card.ts
Part of https://github.com/Shopify/core-issues/issues/55239
Related to https://github.com/Shopify/customer-account-web/pull/2258
Removes the Card props `fillHeight` and `includeDividers` from `customer-account-ui-extensions`. These props are no longer available in `customer-account-web`. They aren't used by the `buyer-returns` or `buyer-subscriptions` extensions so it's safe to remove them.
See https://github.com/Shopify/customer-account-web/pull/2258 for details
=> [Customer Account] Remove unused Card props

packages/retail-ui-extensions/src/extension-api/device-api/device-api.ts, packages/retail-ui-extensions/src/extension-api/device-api/index.ts, packages/retail-ui-extensions/src/extension-api/index.ts, packages/retail-ui-extensions/src/extension-api/standard-api.ts, packages/retail-ui-extensions/src/index.ts
Part of [23437](https://github.com/Shopify/pos-next-react-native/issues/23437)
Creates a DeviceAPI with `name` and `deviceId` properties.
Create the DeviceAPI with `name` and `deviceId` properties and propagate it to the top of the `retail-ui-extensions` package.
- ...
=> Create a DeviceAPI for name and deviceId

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
- @shopify/retail-ui-extensions-react@1.1.3-rc.0
- @shopify/retail-ui-extensions@1.1.3-rc.0
It's named 1.1.3-rc because our CLI doesn't let us use custom identifiers for minor versions, only for patch versions.
- ...
=> Publish release candidate for 1.2.0

packages/retail-ui-extensions/package.json, packages/retail-ui-extensions/src/components/List/List.ts, yarn.lock
https://github.com/Shopify/pos-next-react-native/issues/24526 added react-native dependency. The dependency mis-matches POS which crashes the app. It also is too big for ui-extensions to ingest.
Removed accessibility and tests for now. This should be a separate discussion. 
- ...
=> Remove react native and tests from List

packages/customer-account-ui-extensions/src/components/Card/Card.ts
Fixes two issues with the `Card` spacing props that lead to autocomplete and type check not working.
| Before | After |
| --- | --- |
| <img width="719" alt="Screenshot 2023-06-02 at 1 16 23 PM" src="https://github.com/Shopify/ui-extensions/assets/474248/f8a7b079-1f34-42a9-a917-15c885a793c7"> | <img width="707" alt="Screenshot 2023-06-02 at 1 45 03 PM" src="https://github.com/Shopify/ui-extensions/assets/474248/08fffb48-3e79-442a-ae0e-c51512100bdb"> |
- `SpacingProps` already contains `padding` so assigning it to `padding` didn't work. I checked [how it's used in other components](https://github.com/search?q=repo%3AShopify%2Fui-extensions+SpacingProps&type=code) and applied it similarly.
- The bigger one. `components/shared` doesn't work because TS can't resolve it. `components` isn't a …
=> fix spacing types for Customer Account Card

packages/retail-ui-extensions/src/components/PinPad/PinPad.ts
PinPad's action is not working because Argo under the hood wraps the return in a Promise. 
This PR makes it explicit. 
- ...
=> PinPad fix

packages/post-purchase-ui-extensions/documentation/extension-points.md
- Backports some docs that were updated in `shopify-dev`, but we're never updated in the source repo (`ui-extensions`)
- Relates to https://github.com/Shopify/shopify-dev/pull/34421
=> [Post-purchase extensions API reference]: Backport docs

.changeset/big-oranges-dress.md, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts
Resolves https://github.com/Shopify/core-issues/issues/57311
Adds viewMajor icon for storefront events templates
Add the viewMajor in Source
=> [CustomerSegmentationTemplate] Add viewMajor icon in source

packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts
Reverts [accidental push to unstable to add buyMajor icon](https://github.com/Shopify/ui-extensions/commit/c8fa2cdc8c2a0da892c14b957d211fec337133be)... Not a breaking change, but reverting, then will open a pr to add the icon + add a changeset.
Removes icon.
- ...
=> Revert adding buyMajor icon

.changeset/sixty-kangaroos-smoke.md, .gitignore, package.json, packages/ui-extensions/package.json
Support for generating docs within this repo using `yarn docs:checkout`.
Point to the script, add gitignore for generated files.
1. Run `spin up checkout-web:api-docs`
2. In spin shell `cd ui-extensions && git checkout jkv/generate-docs`
3. `yarn && yarn docs:checkout`
4. Verify the output on the shopify dev link that is shown
https://shopify-dev.ui-extensions-unstable.james-vidler.us.spin.dev/docs/api/checkout-ui-extensions
=> Support building checkout docs in-repo

packages/ui-extensions/src/api.ts, packages/ui-extensions/src/surfaces/admin/api/standard/standard.ts
We need to add the new shared APIs to the StandardAPI.
Add navigation and intents to StandardAPI.
- Use this line in the extensions app that you are testing with: 
```js
const {extensionPoint, navigation: {navigate}, intents} = useApi();
```
- You should see TS errors
- Check out this branch from `ui-extensions` and run `yarn build-consumer <your-app>` (Note that your app should be in the `~/src/github.com/Shopify/` directory for build-consumer to work. I have the Remix template cloned so I used: `yarn build-consumer shopify-app-template-remix`. 
- TS errors should disappear.
=> feat: add navigation and intents to StandardAPI

packages/retail-ui-extensions/src/components/DateField/DateField.ts, packages/retail-ui-extensions/src/components/TimeField/TimeField.ts
This absolute import path is causing problems with resolution in the built packages.
Use relative imports instead.
Tophatted by yalc'ing this package into POS and making sure the issues were resolved.
=> fix relative import issues in DateField and TimeField

packages/retail-ui-extensions/src/components/List/List.ts
In case the image display strategy is always, a Partner can provide a badge with a number even when the source is empty. 
- https://github.com/Shopify/pos-next-react-native/issues/26169
- https://github.com/Shopify/pos-next-react-native/pull/26173#issuecomment-1642783877
Make source optional. 
- ...
=> Make source optional for POS UI extension Lists

packages/retail-ui-extensions-react/src/components/TextField/TextField.ts, packages/retail-ui-extensions-react/src/components/TextField/index.ts, packages/retail-ui-extensions-react/src/components/index.ts, packages/retail-ui-extensions/src/component-sets/Basic.ts, packages/retail-ui-extensions/src/components/TextField/TextField.ts, packages/retail-ui-extensions/src/components/TextField/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Part of https://github.com/Shopify/polaris-for-retail/issues/182
This begins the migration the previous implementation of the original TextField implementation to use the new PFR component instead. Since we are releasing rc versions, we can temporary release a NewTextField and put deprecation comments for the existing TextField until we release version 2.0.0.
=> Add NewTextField component and deprecation comments for old TextField

.changeset/dirty-lizards-explode.md, packages/ui-extensions/src/api.ts, packages/ui-extensions/src/surfaces/admin/api.ts, packages/ui-extensions/src/surfaces/admin/api/block/block.doc.ts, packages/ui-extensions/src/surfaces/admin/api/block/block.ts, packages/ui-extensions/src/surfaces/admin/extension-targets.ts
Adds `data` which was missing from action and block extensions, and also removes `i18n` since that is present in the standard API.
- ...
=> Add data to block and action types

.changeset/kind-carpets-applaud.md, .changeset/little-sheep-join.md, .changeset/neat-vans-heal.md, .changeset/odd-crabs-eat.md, .changeset/pink-poets-confess.md, .changeset/slimy-timers-heal.md, packages/ui-extensions-react/package.json, packages/ui-extensions-react/src/surfaces/admin/hooks/api.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/api.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/extension.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/index.ts, packages/ui-extensions-react/src/surfaces/checkout/render.tsx, packages/ui-extensions-react/src/surfaces/checkout/tests/react-extension.test.tsx, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
This PR is backporting some final changes made to the `unstable`/ `2023-07` branch of UI extensions back to `2023-05`.
=> Backport extension APIs to 2023-04

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts
Fix broken link to extension targets on main page of Admin extensions docs
=> docs: fix link to extension point targets on admin extensions docs

.changeset/unlucky-moose-flash.md, packages/ui-extensions/src/api.ts, packages/ui-extensions/src/surfaces/admin/api.ts, packages/ui-extensions/src/surfaces/admin/api/action/action.ts, packages/ui-extensions/src/surfaces/admin/api/block/block.ts, packages/ui-extensions/src/surfaces/admin/api/shared.ts, packages/ui-extensions/src/surfaces/admin/api/standard/standard.ts
This PR nests a few API types that are only available in the admin. I noticed these while I was bringing in the latest version of these files from checkout, which did not contain the very-generically-named `Data` type. I think nesting these in the admin surface is more appropriate, and we can always move them out as needed later.
=> Nest admin-only API types

packages/retail-ui-extensions-react/.npmignore, packages/retail-ui-extensions/.npmignore
https://github.com/Shopify/pos-next-react-native/issues/26233
tl;dr: Typescript is not resolving prop types correctly after this merged.
@accet-shop and @rtymchyk, @heltisace suggested that this may mess with Stocky tests in some way. If we can find a way to fix the typescript stuff without reverting this, that would be a much better solution. However, we do need to get the typescript working by the release of 1.3.0, which is scheduled for Aug 9.
We spent a lot of time trying to fix this without reverting these changes since they are consistent with other packages in this repository.
Build `retail-ui-extensions-react` and verify that the typescript declaration files can resolve props of components correctly.
=> Revert "Ignore src folder in published packages"

packages/customer-account-ui-extensions/src/extension-points/standard-api/index.ts
Fixes https://github.com/Shopify/core-issues/issues/49897
Just removed the type
=> [CustomerAccount | Extensibility] Remove features type on standardApi

packages/retail-ui-extensions/src/components/List/index.ts, packages/retail-ui-extensions/src/components/Screen/index.ts, packages/retail-ui-extensions/src/components/Section/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/extension-api/index.ts, packages/retail-ui-extensions/src/extension-api/toast-api/index.ts, packages/retail-ui-extensions/src/index.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/25236
Add missing export chains
Yalc and fix imports in POS
=> Add missing exports to index chain

packages/customer-account-ui-extensions-react/src/hooks/extension-editor.ts, packages/customer-account-ui-extensions-react/src/hooks/tests/extension-editor.test.tsx, packages/customer-account-ui-extensions/src/extension-points/index.ts, packages/customer-account-ui-extensions/src/extension-points/standard-api/extension.ts
Part of https://github.com/Shopify/core-issues/issues/58453 
Add UI Extension Editor interface, just like what checkout did to indicate whether it is rendered within an editor so 3rd part developers can simulate data in this case
customer-account-web side: https://github.com/Shopify/customer-account-web/pull/2664 
See tophat in this PR https://github.com/Shopify/customer-account-web/pull/2664
=> Extension editor

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/authenticated-fetch.jsx
Folks kept asking if they could use these with their apps' backends, or if they could get a session token. 
Documented how fetch requests will automatically be authenticated and added a code sample.
- Generate the docs
- Copy them to shopify-dev
- Preview the changes
- [X ] I have :tophat:'d these changes
- [ X, but this one feels like a trick question for this commit] I have updated relevant documentation
=> Admin authentication

.changeset/config.json
When running `yarn changset` it should be using the `unstable` branch as the base branch.
Updates the config.
=> changset should use unstable branch as base

packages/checkout-ui-extensions-react/package.json, packages/checkout-ui-extensions/package.json, packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
Bumps the versions for the packages to be published. Follows the[ PR that merged changes](https://github.com/Shopify/ui-extensions/pull/1204).
The result of running `yarn version-bump:checkout` for a patch for `checkout-ui-extensions`.
=> Publish checkout-ui-extensions version 0.27.2

packages/retail-ui-extensions/src/components/Badge/Badge.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/24563
Adding the optional badge prop that's already supported in PFR.
Add it.
Locally install the package in some project (yalc, pack, etc) and verify that the prop is there. Not really necessary for something this simple.
=> feat(Badge): add optional BadgeStatus to Badge component

packages/web-pixels-extension/src/types/EventBus.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts, scripts/consumer-helper.sh
On all standard events, `data` is an object with some specific data. `'page_viewed'` of type `PixelEventsPageViewed` is the only one that doesn't include any explicit additional data. However, the implementation still provides an empty object.
First, I added `PixelEventsPageViewedData` as an empty object to `page_viewed` event type. Then, I figured that some other types were slightly off, so I moved `custom_event` out of `PixelEvents` and now `CustomEvent` replaces `PixelEventsCustomEvent`.
I then updated `StandardEvents` so that the "all events" keys' possible values were properly typed. Which led me to also update the `EventBus` interface since it's not possible to publish to "all events", it's only possible to subscribe to those.
=> Fix `PixelEvents`, `EventBus` and `StandardEvents` types

packages/customer-account-ui-extensions/src/extension-points/extension-points.ts
Part of this ticket https://github.com/Shopify/core-issues/issues/58896 
add static extension points for customer account web information page
- ...
=> customer account information static extension

packages/ui-extensions/src/surfaces/admin/components/Link/Link.ts
Currently, links can only open in their own context.
- Add `target` prop  to provide a way for links to open in a new tab
- Set up extensions spinstance with `spin up extensions` 
- Create an app and extension
- `yarn create @Shopify/app`
-  `yarn generate extension` (choose action or block)
- Copy your app into your Shopify directory to make sure that the build-consumer script works. `cp -R <app-path> ~/src/github.com/Shopify/<app-folder>`
- In `ui-extensions` on this branch, run:
- `yarn build-consumer <your-app>`  
- `yarn build-consumer-spin web` 
- Restart web after running build consumer script
- Add an external link with `target="_blank"` to your extension (make sure to import `Link`)
- `<Link to='https://google.com' target='_blank'>Google</Link>`   
- Confirm that the `target` …
=> Add target to link

packages/retail-ui-extensions-react/src/index.ts, packages/retail-ui-extensions/src/components/Icon/Icon.ts, packages/retail-ui-extensions/src/components/Icon/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/26549
Add option IconSize to icon component
=> Add IconSize prop to Icon component

.changeset/hip-olives-wave.md, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentTemplate/CustomerSegmentTemplate.ts, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentTemplate/examples/CustomerSegmentTemplate.example.tsx, packages/ui-extensions/src/surfaces/admin/api.ts, packages/ui-extensions/src/surfaces/admin/api/customer-segment-template/customer-segment-template.ts, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentTemplate/CustomerSegmentTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentTemplate/examples/CustomerSegmentTemplate.example.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions/src/surfaces/admin/extension-targets.ts
Resolves https://github.com/Shopify/customer-data-platform/issues/5767
We already have a CustomerSegmentationTemplate ui extension component (see https://github.com/Shopify/ui-extensions/pull/759) that we use to render templates from our [1p app](https://github.com/Shopify/segmentation-templates-app) in the admin. 
However, we want to extend this functionality to other 1p and 3p apps, and we have different requirements for this new public component than the one we use currently (we don't want other 1p/3p apps to be able to pass a custom icon or category, we want to support custom metafields). 
Since web uses the `unstable` version of ui-extensions, we're adding a second component that will be [documented](https://shopify.dev/docs/api/admin-extensions/components) for 1p/3p apps to use, and …
=> Adds `CustomerSegmentTemplate` component

.changeset/tiny-bees-report.md, packages/ui-extensions/src/shared.ts, packages/ui-extensions/src/surfaces/admin/api/standard/standard.ts, packages/ui-extensions/src/surfaces/admin/components/Link/Link.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts, packages/ui-extensions/src/surfaces/customer-account/api/order-status/order-status.ts
Related to https://github.com/Shopify/app-ui/issues/232
Expose the `query` API to Admin extensions.
- Use the CLI to create a new app and generate an Action extension
- In this repo, run `yarn build-consumer ./your-project-dir/extensions/admin-action`
- Update the Action extension's code to the following:
```diff
// The useApi hook provides access to several useful APIs like i18n, close, and data.
-   const {extension: {target}, i18n, close, data} = useApi(TARGET);
+   const {extension: {target}, i18n, close, data, query} = useApi(TARGET);
const [productTitle, setProductTitle] = useState('');
// Use direct API calls to fetch data from Shopify.
// See https://shopify.dev/docs/api/admin-graphql for more information about Shopify's GraphQL API
useEffect(() => {
-   (async function …
```
=> Expose query api for Admin extensions

packages/customer-account-ui-extensions/src/extension-points/extension-points.ts, packages/customer-account-ui-extensions/src/extension-points/index.ts
Part of https://github.com/Shopify/core-issues/issues/58096 
add ActionExtensionApi to customer account web ui
```
export interface ActionExtensionApi {
close(): void;
}
```
- ...
=> add ActionExtensionApi to customer account web ui

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts
Fix the tab names being cut off in the docs and also switch to sentence casing to match convention
**Before**
**After**
=> Fix tab names for Direct API examples

packages/retail-ui-extensions/src/components/Screen/Screen.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/26548
Stocky wants to implement the ability to display a dialog when the back button is pressed resulting in the screen in not navigating back. Currently `onNavigateBack` only performs some sort of logic after the screen is unmounted however we need another callback to run while mounted. 
You can see a draft POS Screen implementation below which adds a secondary action depending if this prop is not undefined:
```ts
<Container
title={title}
inset="none"
scrollViewAsContainer={false}
secondaryAction={
onSecondaryActionPressed
? {
text: i18n.translate('Screen.back'),
onPress: () => {
onSecondaryActionPressed();
},
}
: undefined
}
>
```
Open to discussion about naming and callback type. We need to make it clear on the …
=> Add back button hijacking callback to screen component

.changeset/good-bikes-matter.md, packages/ui-extensions-react/loom.config.ts, packages/ui-extensions-react/src/surfaces/customer-account/render.tsx, packages/ui-extensions/loom.config.ts
Tried to actually import from this package and it failed:
```
ENOENT: no such file or directory, open '/home/spin/src/github.com/[SNIP]/node_modules/@shopify/ui-extensions/build/cjs/surfaces/customer-account.js'
```
Noticed that `customer-account` wasn't properly configured to be emitted.
- include customer-account in build config
I 🎩 locally by building the package and copying it into the consuming `node_modules`. I'm not sure this can be done without much effort. Since nobody is using this yet for customer account (as is apparent by the bug existing in the first place), I'd be ok to ship it like this.
=> fix customer account build

.changeset/good-bikes-matter.md, packages/ui-extensions-react/loom.config.ts, packages/ui-extensions-react/src/surfaces/customer-account/render.tsx, packages/ui-extensions/loom.config.ts
brings https://github.com/Shopify/ui-extensions/pull/1264 to the `2023-07` version.
@vividviolet I just picked all the commits from the other PR, including the changeset. Is that correct or would we need to create a different changeset for the stable version?
=> backport customer account fixes

packages/ui-extensions-react/package.json, packages/ui-extensions/package.json
The `unstable` branch of this repository should have its package.json version as `0.0.0-unstable` and not have a specific stable version identifier.
Change the package.json for both packages.
=> update version to 0.0.0-unstable

.changeset/popular-eggs-remember.md, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts
Right now we are duplicating the icon and category types on web, and this makes 2 sources of truth for template icon sources and categories to maintain. 
Exposing both the array and type publicly will help clean up web, and result in less maintenance in the long term.
=> Expose `CustomerSegmentTemplate` icon and category types

.changeset/five-dancers-poke.md, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentTemplate/examples/CustomerSegmentTemplate.example.tsx, packages/ui-extensions-react/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.tsx, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentTemplate/CustomerSegmentTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentTemplate/examples/CustomerSegmentTemplate.example.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/CustomerSegmentationTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/CustomerSegmentationTemplate/examples/CustomerSegmentationTemplate.example.ts
- Close https://github.com/Shopify/customer-data-platform/issues/5836
We are cleaning up the `CustomerSegmentTemplate` prop names to make them more stream lined before we expose the API to partners. 
Renaming the following props: 
- `templateQuery` -> `query`
- `templateQueryInsert` -> `queryInsert`
- `dateAdded` -> `createdOn`
Marking the previous as deprecated until we add support for the new props in web and in our 1P application: segmentation-templates-app.
=> Update `CustomerSegmentTemplate` prop names

.github/workflows/deploy.yml, documentation/versions-and-deploys.md
Backports the [same change](https://github.com/Shopify/ui-extensions/pull/1271) that was merged into `2023-07`.
It adds the 'latest' NPM dist tag when the latest stable version is being published. The 'latest' dist tag will never be applied when `unstable` is being deployed for two reasons:
1. The `deploy.yml` workflow is not enabled for the `unstable` branch
2. Even if it was, the `LATEST_STABLE_VERSION` does not equal "unstable"
Its important this change is applied to the unstable branch, so that when we cut future stable versions from this, this workflow is included.
Backport the change already applied in https://github.com/Shopify/ui-extensions/pull/1271.
> **Note**: This change is not necessary to implement in the previous `2023-04` version because that should never apply the latest …
=> Applies the latest dist tag deploy step into `unstable` branch

.changeset/fifty-pens-carry.md, packages/ui-extensions/src/surfaces/admin/components.ts, packages/ui-extensions/src/surfaces/admin/components/InternalCustomerSegmentTemplate/InternalCustomerSegmentTemplate.ts
Exporting the constants and types for template icons and categories so that it doesn't create long import path in the admin.
=> Cleanup exports for exposed constants and types for icons and categories

packages/customer-account-ui-extensions/src/extension-points/extension-points.ts
The account information section is being renamed to "profile" and thus the target extension names have also been accordingly updated. 
Renaming dynamic extension targets as described in the following figma: https://www.figma.com/file/5Op17XqUmqj8dCSI5RZvo6/Extensibility-Dev-Preview?type=design&node-id=1656-12269&mode=design&t=rhwyvX5uTcEgqSkz-4
Also, confirmed with @joao-quintino that the static extension names will also be renamed to `profile`
=> profile dynamic extension for customer accounts

packages/customer-account-ui-extensions-react/package.json, packages/customer-account-ui-extensions/package.json
This PR is updating the extension target names for customer account profile extensions
Tags:
- https://github.com/Shopify/ui-extensions/tree/%40shopify/customer-account-ui-extensions-react%400.0.63
- https://github.com/Shopify/ui-extensions/tree/%40shopify/customer-account-ui-extensions%400.0.61
=> Publish Customer Accounts Profile Extension Targets

package-lock.json, package.json, packages/ui-extensions/package.json, yarn.lock
A newer version of `generate-docs` enforces example patterns that we aren't following.
- Downgrade `generate-docs` for now
- Fix examples soon. Issue [here](https://github.com/Shopify/app-ui/issues/416)
- Run `yarn docs:admin` and confirm that there are no build errors.
=> chore: downgrade generate-docs version to avoid error for inline examples

packages/customer-account-ui-extensions/src/extension-points/extension-points.ts
Update customer account staff permissions target name
Figma: https://www.figma.com/file/5Op17XqUmqj8dCSI5RZvo6/Extensibility-Dev-Preview?type=design&mode=design&t=MsohghyKJ088FV1X-0 
Part of this ticket https://github.com/Shopify/core-issues/issues/58896 
- ...
=> Update customer account staff permissions target name

packages/ui-extensions/docs/surfaces/admin/staticPages/examples/direct-api-fetch.jsx, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/direct-api-query.jsx
A partner tried to use the `query` API as well as `fetch` and noticed that our docs were wrong
=> Fix Direct API query example for Admin

packages/retail-ui-extensions/src/components/Screen/Screen.ts, packages/retail-ui-extensions/src/components/Screen/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/27009
As part of stocky work for M2, we need to expose `secondaryAction` for the screen component. The component itself already exists. 
Let me know if the typing or documentation is correct.
- ...
=> Expose secondary action on screen component

packages/ui-extensions/docs/surfaces/checkout/reference/examples/order-status/default.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/order-status/default.example.tsx
Targets in examples for OSP were not correctly updated with the latest extension point target at edition.
Fixes on unstable for now.
This mirrors the changes made in https://github.com/Shopify/checkout-web/pull/25584 and https://github.com/Shopify/shopify-dev/pull/37062
* Should I also update the 2023-04 and 2023-07 versions ? How do we manage changes like those ? I don't think there's any release needed for any of those changes.
=> Fix osp examples

packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts
Part of https://github.com/Shopify/core-issues/issues/60098
Add come sample comments for customer account navigation API. Most of the comments come from https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API directly. 
- Navigation doc: https://shopify-dev.doc.brian-shen.us.spin.dev/docs/api/customer-account-ui-extensions/apis/navigation 
- CustomerAccountCard doc: https://shopify-dev.doc.brian-shen.us.spin.dev/docs/api/customer-account-ui-extensions/components/structure/customeraccountcard
=> Add sample comments for customer account navigation

packages/ui-extensions/src/surfaces/customer-account/targets.ts
Part of https://github.com/Shopify/core-issues/issues/57077 
Update B2B profile extension targets and full page extension target name. 
For location related extension targets, we will provide a `locationId` parameter. 
Figma: 
https://www.figma.com/file/5Op17XqUmqj8dCSI5RZvo6/Extensibility-Dev-Preview?type=design&node-id=1656-12268&mode=design&t=0T2ytBkSPUm64hj4-0 
- ...
=> Update B2B profile extension targets

packages/ui-extensions/src/surfaces/checkout/components/Image/Image.ts
Clarify that the path is to the file on the Shopify store
The documentation is not clear that path refers to the path to the image on the Shopify store, and not the path to the local image. This was causing confusion for developers.
Update the docs.
- ...
- [] I have :tophat:'d these changes
=> Update Image src prop description

packages/ui-extensions/src/surfaces/customer-account/targets.ts
Add ODP static extension targets:
1. customer-account.order-status.delivery-details.render-after 
2. customer-account.order-status.payment-details.render-after
Figma: 
https://www.figma.com/file/5Op17XqUmqj8dCSI5RZvo6/Extensibility-Dev-Preview?type=design&node-id=1656-16556&mode=design&t=w1XfdbDu7fkk8DQN-0
- ...
=> Add ODP static extension targets

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json
Part of https://github.com/Shopify/pos-next-react-native/issues/27744
Changes:
- @shopify/retail-ui-extensions-react: 1.5.0-rc.0 => 1.5.0-rc.1
- @shopify/retail-ui-extensions: 1.5.0-rc.0 => 1.5.0-rc.1
=> Publish 1.5.0-rc.1

.changeset/curvy-turkeys-leave.md, packages/ui-extensions/src/surfaces/admin/api/customer-segment-template/customer-segment-template.ts, packages/ui-extensions/src/surfaces/admin/components/InternalCustomerSegmentTemplate/InternalCustomerSegmentTemplate.ts, packages/ui-extensions/src/surfaces/admin/components/InternalCustomerSegmentTemplate/examples/InternalCustomerSegmentTemplate.example.ts
Resolves https://github.com/Shopify/core-issues/issues/60600 (more context in https://github.com/Shopify/core-issues/issues/58095)
We want to have a template in customer segmentation that only appears in shops on the plus plan. 
- Adds b2bEnabled `enabledFeature` to our API
- Removes other enabledFeatures we are no longer using. The beta flags for these features have been removed.
- Cleans up InternalCustomerSegmentTemplate example to use b2bEnabled enabledFeature instead of productPurchasedOnTags
- Cleans up icon list as buyButtonMajor was listed twice
- Nothing to tophat. We aren't even using enabledFeatures in our [1p app](https://github.com/search?q=repo%3AShopify%2Fsegmentation-templates-app%20enabledFeatures&type=code) or in …
=> Adds b2bEnabled enabledFeature on CustomerSegmentTemplateApi

packages/ui-extensions/src/surfaces/customer-account/api.ts, packages/ui-extensions/src/surfaces/customer-account/api/order-status/order-status.ts
Bring APIs that were added to unstable here https://github.com/Shopify/ui-extensions/pull/1372 to our internal package so we don't lose them when we replace unstable with internal soon again.
=> backport new unstable checkout apis to internal

packages/ui-extensions-react/src/surfaces/customer-account/components/Page/Page.ts, packages/ui-extensions-react/src/surfaces/customer-account/components/Page/index.ts, packages/ui-extensions-react/src/surfaces/customer-account/components/index.ts, packages/ui-extensions/src/surfaces/customer-account/components/Page/Page.ts, packages/ui-extensions/src/surfaces/customer-account/components/Page/index.ts, packages/ui-extensions/src/surfaces/customer-account/components/index.ts
Contributes to https://github.com/Shopify/core-issues/issues/59115
RFC: https://github.com/Shopify/ui-api-design/discussions/146
Expose Page component and its Props.
Page Being used in extension: 
[Spin](https://development-store-1.account.shopify.page-component-tophat.oleksandr-oliynyk.eu.spin.dev/pages/dev-651cadbd-9a98-4c76-b0e0-a007766590a4/) - dev@shopify.com
=> Add Page component

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/src/surfaces/admin/api/action/action.doc.ts, packages/ui-extensions/src/surfaces/admin/api/block/block.doc.ts, packages/ui-extensions/src/surfaces/admin/api/extension-targets/extension-targets.doc.ts, packages/ui-extensions/src/surfaces/admin/api/standard/standard.doc.ts, packages/ui-extensions/src/surfaces/admin/components/AdminAction/AdminAction.doc.ts, packages/ui-extensions/src/surfaces/admin/components/AdminBlock/AdminBlock.doc.ts, packages/ui-extensions/src/surfaces/admin/components/BlockStack/BlockStack.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Box/Box.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Button/Button.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Checkbox/Checkbox.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Divider/Divider.doc.ts, packages/ui-extensions/src/surfaces/admin/components/EmailField/EmailField.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Form/Form.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Heading/Heading.doc.ts, packages/ui-extensions/src/surfaces/admin/components/HeadingGroup/HeadingGroup.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Icon/Icon.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Image/Image.doc.ts, packages/ui-extensions/src/surfaces/admin/components/InlineStack/InlineStack.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Link/Link.doc.ts, packages/ui-extensions/src/surfaces/admin/components/NumberField/NumberField.doc.ts, packages/ui-extensions/src/surfaces/admin/components/PasswordField/PasswordField.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Pressable/Pressable.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Select/Select.doc.ts, packages/ui-extensions/src/surfaces/admin/components/Text/Text.doc.ts, packages/ui-extensions/src/surfaces/admin/components/TextArea/TextArea.doc.ts, packages/ui-extensions/src/surfaces/admin/components/TextField/TextField.doc.ts, packages/ui-extensions/src/surfaces/admin/components/URLField/URLField.doc.ts
admin_extensibility feature flag wasn't removed from source, so it's being [reintroduced to the reference docs when they're regenerated](https://github.com/Shopify/shopify-dev/pull/37689). Because the flag has been removed from Shopify.dev, we need to rm the flag in this repo so that reference docs display as expected on prod.
Remove `admin_extensibility` from the `.ts` files for reference objects. 
- ...
=> Remove admin_extensibility feature flag

.changeset/silent-wolves-brake.md, packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts
I did this backwards :) 
PR with docs changes: https://github.com/Shopify/shopify-dev/pull/37092
This PR mirrors those back to ui-extensions so they don't get overwritten.
- ...
=> Persist changes to ui-extensions

package.json, packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/deploy.sh, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/fetch-data.js, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/link-to-action.jsx, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/link-to-product-page.jsx, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/link-to-route.jsx, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/link-to-settings.jsx, packages/ui-extensions/package.json, yarn.lock
This fixes a mismatch where checkout UI extensions must be generated with version `0.10.13` and admin UI must be generated with `0.10.10` otherwise code within accordions don't show correctly.
This updates the `@shopify/generate-docs` package to a known stable release version of `0.10.13` that checkout UI extensions has been using for some time. This fixes a previous issue where code within an accordion would be inlined as opposed to using a code file. 
Use files for code examples as intended and bump the version to `0.10.13` where this was fixed.
- ...
=> fix inline code bug

packages/ui-extensions/src/surfaces/customer-account/targets.ts
Renaming was updated as specified in the following issue: 
https://github.com/Shopify/core-issues/issues/58559
=> Rename order action menu item ui extension

packages/ui-extensions-react/src/surfaces/checkout.ts
There are 3 components that are exported from `ui-extensions` package but not from `ui-extensions-react`. Aiming to get both packages symmetrical, this PR is exporting them in the `react` package too
- Green CI
=> Expose missing components to the react package

packages/ui-extensions/src/surfaces/customer-account/components/shared-checkout-components.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Part of https://github.com/Shopify/core-issues/issues/60107 
A fix for https://github.com/Shopify/customer-account-web/pull/3094 
Mainly when we import form checkout parent folder directly, we load almost all the types from `surface/checkout` , which will cause many type conflicts while generating documentations. 
Update some import so that types are correct in documentations. 
Green CI
=> Fix type mismatch issue for documentations

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/EventBus.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts, packages/web-pixels-extension/src/types/PublicApi.ts, packages/web-pixels-extension/src/types/VisitorApi.ts
Updates our web pixels extension api! Changes include:
- payment gateway 
- screenX/screenY
- appClientID renamed to appID
=> update web pixels extensions with payment gateway

.changeset/serious-cheetahs-smash.md, packages/ui-extensions-react/src/surfaces/admin/components.ts
The new Badge component isn't exported from `@shopify/ui-extensions-react`.
Export it.
- ...
=> feat: export Badge from ui-extensions-react

.changeset/long-doors-sell.md, packages/ui-extensions-react/src/surfaces/customer-account/components/PolicyModal/PolicyModal.ts, packages/ui-extensions-react/tsconfig.json, packages/ui-extensions/tsconfig.json
Not stripping the internal fields caused clashes in an app. 
I missed moving this over. We already had this setting in internal: https://github.com/Shopify/ui-extensions/pull/1399/files#diff-256b5258d7b08eedfba647de7d28bae26f13f08d985b93f5c1ddb456644857d2R7
I also changed how the type is constructed. I have honestly no idea how/why this worked before 🤔 
We never combined the Component with its types. We're now passing the props so that the type is complete. 
🎩 will be done in said app, after merge.
=> fix policy modal

packages/ui-extensions-react/src/surfaces/customer-account/hooks/authenticated-account.ts, packages/ui-extensions-react/src/surfaces/customer-account/hooks/extension.ts, packages/ui-extensions/src/surfaces/customer-account/api/docs.ts
Part of https://github.com/Shopify/core-issues/issues/60108
Please also have a review of this PR on customer account web side https://github.com/Shopify/customer-account-web/pull/3214 
adding standard api docs: https://github.com/Shopify/ui-extensions/blob/add-customer-account-standard-api-doc-types/packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts#L15-L86
- extension targets ( deprecated 2023-07, not adding this )
- extension
- authenticatedAccount
- version
- localization
- i18n
- i18n sample
- router ( deprecating, not adding this )
- authenticatedRedirect
- storage
- ui
refer to tophat instructions in this PR …
=> add customer account standard api doc types

packages/ui-extensions/src/surfaces/checkout/components/shared.ts
This update is related to this https://github.com/Shopify/checkout-web/pull/26499 and got missed in https://github.com/Shopify/ui-extensions/pull/1437. Need these values for exposing the background prop in the customer account surface.
It should have been part of [this changeset](https://github.com/Shopify/ui-extensions/blob/lsit/fix-background-type/.changeset/big-pets-drop.md) so I don't think I need to add another. Let me know if I do.
https://shopify-dev.checkout-web-api-docs-6bhk.lianne-sit.us.spin.dev/docs/api/checkout-ui-extensions/unstable/components/structure/view#viewprops-propertydetail-background
=> Update Background type values

packages/ui-extensions/src/surfaces/customer-account/api/docs.ts, packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts
Part of Shopify/core-issues#61073
Please also have a review of customer account web side PR https://github.com/Shopify/customer-account-web/pull/3246 
Support storefront api for standard customer account ui extension api 
Please see the tophat here https://github.com/Shopify/customer-account-web/pull/3246
=> Support storefront api for customer account api

packages/ui-extensions/src/surfaces/customer-account/targets.ts
This extension point was never used in prod and will never be used. We can hence remove it.
=> remove obsolete extension point

packages/retail-ui-extensions/src/extension-api/cart-api/cart-api.ts, packages/retail-ui-extensions/src/extension-api/index.ts, packages/retail-ui-extensions/src/index.ts
PriceOverride is no longer supported. Code discounts are only supported at the Cart level.
Deprecate existing DiscountType and create new, correct types
- ...
=> patch: deprecate DiscountType

.changeset/small-phones-visit.md, packages/ui-extensions/src/surfaces/customer-account/api/docs.ts, packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
remove deprecated fields from doc in customer account ui extensions
Please also have a review of this PR customer account web side https://github.com/Shopify/customer-account-web/pull/3318 
- `standradApi.router`
- `fullpageApi.location` 
Spin: https://shopify-dev.pic.brian-shen.us.spin.dev/docs/api/customer-account-ui-extensions/unstable/targets/full-page/customer-account-page-render
Staging4: https://shopify-dev-staging4.shopifycloud.com/docs/api/customer-account-ui-extensions/unstable/targets/full-page/customer-account-page-render#fullpageapi-propertydetail-location
=> Remove deprecated fields from doc

packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts
fix deprecated comment for router.navigate
=> fix deprecated comment for router.navigate

.changeset/big-pumpkins-enjoy.md, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Removing a legacy extension target name
Part of https://github.com/Shopify/core-issues/issues/62713
=> removing legacy extension target

packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts
Checkout branding has been redone. This updates a link to that section.
https://shopify-dev.update-branding-link1.ren-chaturvedi.us.spin.dev/docs/api/checkout-ui-extensions#security
=> Update link and text to styling tutorials

packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts
We're updating the domain for the `load.html` file in Web to the new `https://extensions.shopifycdn.com/`. If apps have a custom CORS policy in their server, they need to add this new domain to the allow list.
This change will be done in https://github.com/Shopify/web/pull/107284. However, we need to send out messaging to Partners first in case they have a different CORS policy already set.
Add documentation for this for extension developers. This is consumed in `shopify-dev` in https://github.com/Shopify/shopify-dev/pull/38519.
https://shopify-dev.shopify-dev-9ncp.charlie-dobson.us.spin.dev/docs/api/admin-extensions#security
=> fix(security): add CORS policy section to Admin UI Extensions docs

packages/ui-extensions/src/surfaces/customer-account/api/docs.ts
Updating docs for Docs_Page_Button_PrimaryAction and Docs_ResourceItem_Button_Action to include overlay prop
[ResourceItem ButtonProps action](https://shopify-dev.overlay-docs.joe-keohan.eu.spin.dev/docs/api/customer-account-ui-extensions/unstable/components/resourceitem#buttonprops%20action)
[Page ButtonProps PrimaryAction](https://shopify-dev.overlay-docs.joe-keohan.eu.spin.dev/docs/api/customer-account-ui-extensions/unstable/components/page#buttonprops%20primaryaction)
=> added overlay to Page and ResourceItem props

packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts
- We updated our figma community files and the links changed, and since we removed the old ones they were leading to an 404 page.
- Talking to UX, the new link will not be updated to a different one in future releases.
- https://shopify-dev.figma-links-update.igor-deoliveiramartins.us.spin.dev/docs/api/checkout-ui-extensions
=> [UI Components]: Adding updated figma link to `2023-07`

packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts
- We updated our figma community files and the links changed, and since we removed the old ones they were leading to an 404 page.
- Talking to UX, the new link will not be updated to a different one in future releases.
- https://shopify-dev.figma-links-update.igor-deoliveiramartins.us.spin.dev/docs/api/checkout-ui-extensions
=> [UI Components]: Adding updated figma link to `2023-10`

packages/ui-extensions-react/src/surfaces/checkout/hooks/buyer-journey.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.block.render.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.cart-line-item.render-after.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.cart-line-list.render-after.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.customer-information.render-after.doc.ts, packages/ui-extensions/docs/surfaces/checkout/staticPages/extension-overview.doc.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts, packages/ui-extensions/src/surfaces/checkout/targets.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Partial fix for https://github.com/Shopify/shopify-dev/issues/38918
- **Thank you** page
- **Order status** page
🌀: https://shopify-dev.checkout-web-api-docs-ugwx.ren-chaturvedi.us.spin.dev/docs/api/checkout-ui-extensions/extension-targets-overview#supported-osp-locations (for e.g.)
=> Typ osp naming UI extensions 2023 10

.changeset/tasty-cheetahs-help.md, packages/ui-extensions/src/surfaces/customer-account/api/docs.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Fixes https://github.com/Shopify/core-issues/issues/62603
=> Remove location api

.changeset/lazy-chairs-join.md, packages/ui-extensions-react/src/surfaces/admin/components/Tooltip/Tooltip.ts, packages/ui-extensions-react/src/surfaces/admin/components/Tooltip/examples/basic-tooltip.example.tsx, packages/ui-extensions/src/surfaces/admin/components/Button/Button.ts, packages/ui-extensions/src/surfaces/admin/components/Text/Text.ts, packages/ui-extensions/src/surfaces/admin/components/Tooltip/README.md, packages/ui-extensions/src/surfaces/admin/components/Tooltip/Tooltip.docs.ts, packages/ui-extensions/src/surfaces/admin/components/Tooltip/Tooltip.ts, packages/ui-extensions/src/surfaces/admin/components/Tooltip/examples/basic-Tooltip.example.ts
Adds the Tooltip component
This also updates the Text and Button interfaces to include `interestTarget` which triggers the tooltip
=> feat: Tooltip

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json, packages/retail-ui-extensions/src/components/CameraScanner/CameraScanner.ts, packages/retail-ui-extensions/src/components/CameraScanner/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts, yarn.lock
Part of https://github.com/Shopify/pos-next-react-native/issues/28204
Updated the names to more closely match we currently do with Polaris, based on @NathanJolly and @vctrchu's suggestion.
- ...
=> Update camera scanner props names

packages/retail-ui-extensions-react/package.json, yarn.lock
Part of https://github.com/Shopify/pos-next-react-native/issues/28204
Missed updating a dependency to point to `1.6.0-rc.1`
- ...
=> Update missing dependency for retail ui extension

packages/retail-ui-extensions-react/package.json, packages/retail-ui-extensions/package.json, packages/retail-ui-extensions/src/components/CameraScanner/CameraScanner.ts, packages/retail-ui-extensions/src/components/CameraScanner/index.ts, packages/retail-ui-extensions/src/components/index.ts, packages/retail-ui-extensions/src/index.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/28204
From @NathanJolly 's [suggestions](https://github.com/Shopify/ui-extensions/pull/1626/files#r1440567589), I've gone ahead and removed the `BannerType` definitions and instead to use `BannerProps`.
Also bumped the version to `1.6.0-rc.2`
- ...
=> update CameraScannerBannerProps to use BannerProps

packages/ui-extensions-react/loom.config.ts
When we migrated over point-of-sale code to unified package we forgot to include an entry in the loom config for react package. Lack of this entry causes a module resolution error when the package is used in the POS UI extension app:
```
✘ [ERROR] Could not resolve "@shopify/ui-extensions-react/point-of-sale"
```
Adding missing entry to the loom config generates necessary `esnext`, `js` and `mjs` needed to correctly resolve the module inside UI extension apps.
- on this branch you can `cd packages/ui-extensions-react`
- install generated tarball in UI extension app that is using components from `@shopify/ui-extensions-react/point-of-sale` package
- run `yarn dev`
- verify that the build doesn't throw `✘ [ERROR] Could not resolve "@shopify/ui-extensions-react/point-of-sale"`
=> Add missing point-of-sale entry to loom config

.changeset/lemon-beds-speak.md, packages/ui-extensions/src/surfaces/point-of-sale/api/product-search-api/product-search-api.ts, packages/ui-extensions/src/surfaces/point-of-sale/components/CameraScanner/CameraScanner.ts
The expected changes for retail-ui-extensions 1.6 need to get merged into `unstable`
I took the diff from https://github.com/Shopify/ui-extensions/compare/4ff6441a46501734d92cc11f088107d93167c799..51f8c509dd0ed97cfea8bdd2e5b314940fb87ac9 and applied the changes here. Updated imports where needed.
=> Updates from retail-1.6.0 main branch

.changeset/sharp-houses-rest.md, packages/ui-extensions/src/surfaces/checkout/components/shared.ts, packages/ui-extensions/src/surfaces/checkout/style/style.ts, packages/ui-extensions/src/surfaces/checkout/style/types.ts
complete https://github.com/Shopify/checkout-web/issues/23677 fix, that wasn't included in all versions
- For `NonPresentationalAccessibilityRole` I took JF's suggestion and just duplicated a bit of code since generate-docs cannot handle `Exclude` property right, and to avoid future errors I opted to not use Pick property as well.
- For conditional styles I end up simplifying some of the types along with @ncardeli, and created a simplified version for docs only, that way we were able to avoid the infinite loop when trying to access the property on the docs.
https://shopify-dev.conditional-styles-doc-fixes.igor-deoliveiramartins.us.spin.dev/docs/api/checkout-ui-extensions
Before
After
-8ad4-d909d41d3da3">
=> [UI components]: Update style helper docs for unstable

.changeset/unlucky-pandas-travel.md, packages/ui-extensions/src/surfaces/checkout/components/shared.ts, packages/ui-extensions/src/surfaces/checkout/style/style.ts, packages/ui-extensions/src/surfaces/checkout/style/types.ts
complete https://github.com/Shopify/checkout-web/issues/23677 fix, that wasn't included in all versions
- For `NonPresentationalAccessibilityRole` I took JF's suggestion and just duplicated a bit of code since generate-docs cannot handle `Exclude` property right, and to avoid future errors I opted to not use Pick property as well.
- For conditional styles I end up simplifying some of the types along with @ncardeli, and created a simplified version for docs only, that way we were able to avoid the infinite loop when trying to access the property on the docs.
https://shopify-dev.conditional-styles-doc-fixes.igor-deoliveiramartins.us.spin.dev/docs/api/checkout-ui-extensions
Before
After
-8ad4-d909d41d3da3">
=> [UI components]: Update style helper docs for 2023-10

.changeset/lucky-beds-care.md, packages/ui-extensions/src/surfaces/customer-account/extension.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Part of step 4 ( have to do it in ui-extension  side as well ) of this ticket https://github.com/Shopify/core-issues/issues/63160
Please also review customer account web side PR: https://github.com/Shopify/customer-account-web/pull/3701 
1. customer account repo: support render customer-account.order.action.menu-item.render if it is within return extension https://github.com/Shopify/customer-account-web/pull/3679 
2. return repo: add an customer-account.order.action.menu-item.render  target extension and remove the CustomerAccount::Returns::Initiate target extension  ( after step 1 is deployed ) https://github.com/Shopify/buyer-returns/pull/372 
3. customer account repo: remove requestReturn logic  https://github.com/Shopify/customer-account-web/pull/3699 
4. customer account repo: remove …
=> drop runExtension support for customer account ui extension

packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.checkout.footer.render-after.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.footer.render-after.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.header.render-after.doc.ts
Default code examples for these header/footer targets were accidentally removed in the latest 2024.1.1 patch. This will add them back. This does not require a package release since this is only documentation related.
Re-add the missing default code.
=> Re-add example code def for header/footer targets

.changeset/nine-points-deny.md, packages/ui-extensions/src/surfaces/customer-account/api/order-status/order-status.ts
Part of https://github.com/Shopify/core-issues/issues/65428 
Add requireLogin for customer account order status api
customer account web side PR: https://github.com/Shopify/customer-account-web/pull/3779 
Please see tophat in this PR: customer account web side PR: https://github.com/Shopify/customer-account-web/pull/3779
=> add requireLogin for customer account order status api

.changeset/warm-spiders-smell.md, packages/ui-extensions-react/src/surfaces/admin/render.tsx
As per [this comment](https://github.com/Shopify/ui-api-design/issues/227#issuecomment-1900860778) in https://github.com/Shopify/ui-api-design/issues/227 we want to lift where an extension can fetch data to the extension callback
This solution mirrors the [implementation from checkout ](https://github.com/Shopify/ui-extensions/blob/unstable/packages/ui-extensions-react/src/surfaces/checkout/render.tsx#L44-L62).
You can try out my spin instance which has both async and sync rendering react and js extensions, lemme know if my dev server isn't running.
https://admin.web.arbok.thomas-marcucci.us.spin.dev/store/development-store-1/products/2
Otherwise if you want to test it on your own:
`spin up checkout-ui-extension-dev`
`git clone git@github.com:Shopify/ui-extensions.git`
`cd` into …
=> Adds support for async react renders for admin extensions

.changeset/tall-ladybugs-join.md, packages/ui-extensions/src/surfaces/admin/api.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/launch-options.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/metafields.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/validation-settings.ts, packages/ui-extensions/src/surfaces/admin/extension-targets.ts
Resolves https://github.com/Shopify/checkout-web/issues/18126
spec'ed here https://github.com/Shopify/ui-api-design/pull/197
_tl;dr: a task-specific extension target that configures only validation functions._
=> Validation settings Admin UI Extension target

.spin/constellation.yml
After [this PR](https://github.com/Shopify/ui-extensions/pull/1686), we can build our ui-extensions docs in spin. But first we need a constellation to use :)
- ...
=> Add a constellation for building dev docs

packages/ui-extensions/src/surfaces/customer-account/api/docs.ts
Part of https://github.com/Shopify/core-issues/issues/65925
export requireLogin  doc type so that we can use it in dev docs
customer account web side PR: https://github.com/Shopify/customer-account-web/pull/3887 
https://shopify-dev.doc.brian-shen.us.spin.dev/docs/api/customer-account-ui-extensions/unstable/apis/order-status-api/require-login
=> export requireLogin  doc type

packages/web-pixels-extension/package.json
Publishing a new version of the `@shopify/web-pixels-extension` package
- @shopify/web-pixels-extension@1.0.0
Closes https://github.com/Shopify/ce-customer-behaviour/issues/4213
Bump the version and publish the changes done in https://github.com/Shopify/ui-extensions/pull/1725
Went through the normal version bump process outlined [here](https://github.com/Shopify/web-pixels-manager/blob/main/help-docs/updating-events.md#updating-ui-extensions)
A major version felt appropriate, since we are removing something, but definitely up for changing if people feel differently.
Tag is at: https://github.com/Shopify/ui-extensions/releases/tag/%40shopify%2Fweb-pixels-extension%401.0.0
=> Publish `@shopify/web-pixels-extension@1.0.0`

packages/ui-extensions/src/surfaces/point-of-sale/components.ts, packages/ui-extensions/src/surfaces/point-of-sale/components/Actiontem/ActionItem.ts, packages/ui-extensions/src/surfaces/point-of-sale/components/Tile/Tile.ts
Resolves part of https://github.com/Shopify/pos-next-react-native/issues/31843
The new UI Extension architecture will introduce a generic component called `ActionItem`, which can be manifested as a Tile or list row. 
🎩
~~- [ ] I have :tophat:'d these changes~~
~~- [ ] I have updated relevant documentation~~
=> deprecating Tile and creating the ActionItem interface

packages/retail-ui-extensions-react/src/components/List/List.ts
Similar to ui-extensions/checkout [`Link`](https://github.com/Shopify/ui-extensions/blob/unstable/packages/ui-extensions-react/src/surfaces/checkout/components/Link/Link.ts#L8)
Change to `unstable` made in #1764 
- ...
=> Add fragmentProps to retail-ui-extensions-react List

.changeset/nine-laws-switch.md, packages/ui-extensions-react/src/surfaces/checkout.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/buyer-journey.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/buyer-journey.test.ts, packages/ui-extensions/docs/surfaces/checkout/reference/apis/buyer-journey.doc.ts, packages/ui-extensions/src/surfaces/checkout.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
This PR syncs the latest content for the buyer journey and some small changes pending in checkout-web. 
Original issue with PRs linked https://github.com/Shopify/checkout-web/issues/29336
Ran `yarn prepare-package-release`
Tophatted with local extension by syncing the files over to my local app. 
Both activeStep and steps are defined from using the hook
=> [Unstable] add buyer journey api to unstable

dev.yml
Web Pixels API is still on branch `main` and we've migrated to isospin version 2, but this repo was only migrated on the `unstable` branch.
Added the missing `dev.yml` based on the `unstable` version of that same file.
Checkout the branch locally and spin an instance on branch `main`.
```
spin up .spin/constellation.yml --metadata isospin_version=2 -c ui-extensions.branch=main
```
=> Migrate to isospin 2

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts, packages/web-pixels-extension/src/types/index.ts
Give merchants/devs access to the customer ID associated with an order, on `checkout_completed`.
Depends on Shopify/web-pixels-manager#601. Related to Shopify/ce-customer-behaviour/issues/4187.
As discussed in [the issue](https://github.com/Shopify/ce-customer-behaviour/issues/4187#issuecomment-1955195962), we're adding a new `OrderCustomer` type rather than just a `customerId` field on `Order`. This will allow us to add more customer data in the future, like `ordersCount` without having to prefix everything with `customer`.
We're going with a new `OrderCustomer` rather than the existing `Customer` type to simplify things. Having a full customer profile type inside `Order` raises lots of questions that are hard to answer, like if the order hasn't been created yet but the customer is …
=> Add OrderCustomer to Web Pixels checkout.order object

.github/workflows/snapit.yml
This PR adds support for the `/snapit` command to generate snapshot versions of the packages using the [GH action that powers the functionality for Polaris](https://github.com/Shopify/snapit).
See this [WxM post](https://shopify.workplace.com/groups/896033601551400/permalink/1120763079078450/) for additional context.
- ...
=> Add support for "snapit" command

packages/ui-extensions/src/surfaces/point-of-sale/components.ts, packages/ui-extensions/src/surfaces/point-of-sale/components/SectionHeader/SectionHeader.ts
Part of https://github.com/Shopify/polaris-for-retail/issues/438
Add new `SectionHeader` component so that the PFR component can be exposed in POS UI extensions.
Add `SectionHeader.ts` based on a subset of the [component interface in PFR](https://github.com/Shopify/polaris-for-retail/blob/main/src/components/List/components/SectionHeader.tsx#L29) (i.e. without list-specific props).
- ...
~- [ ] I have updated relevant documentation~
=> Add SectionHeader to point-of-sale

.changeset/new-lobsters-invent.md, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/launch-options.ts
We've released the wrong type on the function ID.
Fixing the attribute name from `uuid` to `id`.
=> Fix shopifyFunction type for Checkout Rules

.changeset/breezy-bikes-brush.md, packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/launch-options.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/metafields.ts
Instead of using Direct API to load the validation with its metafields inside an Admin UI extension to build the configuration experience, which involves adding an extra `fetch` call and soon an additional app access scope to be able to read those metafields, we're simplifying the experience.
We are now exposing metafields in the type of the Admin UI extensions registration callback `api` parameter, following the release of the implementation that makes them available.
=> Update ValidationData to include metafields

README.md, documentation/how-extensions-work.md, packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts, packages/ui-extensions/src/surfaces/admin/extension-targets.ts, packages/ui-extensions/src/surfaces/checkout/targets.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Renaming `remote-ui` links and applying this change to previous stable versions.
See change in unstable: https://github.com/Shopify/ui-extensions/pull/1800
- ...
=> update remote-ui-links 2023-10

README.md, documentation/how-extensions-work.md, packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts, packages/ui-extensions/src/surfaces/admin/extension-targets.ts, packages/ui-extensions/src/surfaces/checkout/targets.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts, packages/ui-extensions/src/surfaces/point-of-sale/targets.ts
Renaming `remote-ui` links and applying this change to previous stable versions.
See change in unstable: https://github.com/Shopify/ui-extensions/pull/1800
- ...
=> update remote-ui links 2024-01

.changeset/little-seals-punch.md, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/launch-options.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/metafields.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/validation-settings.doc.ts, packages/ui-extensions/src/surfaces/admin/api/checkout-rules/validation-settings.ts
Types were not getting generated which hindered use of the new Cart and Checkout Validation settings in Admin UI extensions.
Refactored types so that they can be included in the generated docs.
[ask for internal link]
=> Redefine types for validations in a way that works for doc generation

packages/ui-extensions/src/surfaces/point-of-sale/api.ts
This export was missing.
Add it.
`yalc` this onto your POS and verify that the type can be imported: https://github.com/Shopify/pos-next-react-native/blob/deb616f6c3668a84e64bf1d883529e5e969e05ce/src/components/UIExtensions/versions/unstable/api/useProductSearchApi.ts#L2
If you're unsure how to `yalc` this, you can use this script: https://github.com/Shopify/pos-next-react-native/pull/34077
=> Retail: Add PaginationParams to exported types

.changeset/tidy-coins-retire.md, packages/ui-extensions/src/surfaces/admin/extension-targets.ts
closes https://github.com/Shopify/app-ui/issues/835
https://shopify-dev.ui-extensions-026v.josh-white.us.spin.dev/docs/api/admin-extensions/unstable/api/extension-targets
Adding type definitions for the [new extension targets being added](https://github.com/Shopify/app-ui/issues/834). 
Targets being added:
=> add new extension targets for action extensions everywhere

.changeset/beige-lions-invent.md, .changeset/breezy-bikes-brush.md, .changeset/dirty-crabs-taste.md, .changeset/lazy-pillows-invent.md, .changeset/lemon-beds-speak.md, .changeset/little-seals-punch.md, .changeset/loud-houses-press.md, .changeset/lucky-beds-care.md, .changeset/lucky-days-learn.md, .changeset/new-lobsters-invent.md, .changeset/nine-laws-switch.md, .changeset/nine-points-deny.md, .changeset/purple-weeks-doubt.md, .changeset/sharp-houses-rest.md, .changeset/shiny-buttons-join.md, .changeset/sixty-rocks-collect.md, .changeset/smart-vans-serve.md, .changeset/tall-ladybugs-join.md, .changeset/tidy-coins-retire.md, .changeset/warm-spiders-smell.md, .changeset/weak-maps-sparkle.md, packages/ui-extensions-react/CHANGELOG.md, packages/ui-extensions/CHANGELOG.md
Removes changesets that have already shipped in the [2024-04 release](https://github.com/Shopify/ui-extensions/pull/1856/files). This also updates the changelog in `unstable` to include this stable release's notes.
As per the [deployment instructions](https://github.com/Shopify/ui-extensions/blob/unstable/documentation/versions-and-deploys.md#creating-new-stable-versions):
> For any changes from unstable that have been incorporated into the new version, delete their changeset files on the unstable branch and replace the existing CHANGELOG.md files in unstable with what was just shipped.
N/A
=> Post 2024-04 release cleanup

packages/ui-extensions/docs/surfaces/checkout/reference/apis/customer-privacy.doc.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
This PR updates the `2024-04` branch of the packages with the recent Customer Privacy API docs updates done as part of [#31538](https://github.com/Shopify/checkout-web/issues/31538).
No new functionality is being introduced, but this update will help to maintain consistency with the dev docs.
[Docs](https://shopify-dev.customer-privacy-docs.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/2024-04/apis/customer-privacy)
- ...
=> Update Customer Privacy API docs — 2024-04

packages/ui-extensions/src/surfaces/admin/api/checkout-rules/validation-settings.doc.ts
Just a typo.
Fixed the typo!
🫴🎩
=> Fix a typo in the validation settings docs

.changeset/yellow-lions-behave.md, packages/ui-extensions-react/src/surfaces/checkout/components/Sheet/Sheet.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/purchase.address-autocomplete.suggest/default.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/helper.docs.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.address-autocomplete.suggest.doc.ts, packages/ui-extensions/src/extension.ts, packages/ui-extensions/src/surfaces/checkout.ts, packages/ui-extensions/src/surfaces/checkout/api/address-autocomplete/address-autocomplete.ts, packages/ui-extensions/src/surfaces/checkout/api/address-autocomplete/standard.ts, packages/ui-extensions/src/surfaces/checkout/api/checkout/checkout.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts, packages/ui-extensions/src/surfaces/checkout/components/Icon/Icon.ts, packages/ui-extensions/src/surfaces/checkout/components/Sheet/Sheet.ts, packages/ui-extensions/src/surfaces/checkout/targets.ts
This PR will update `unstable` packages with the latest changes
generated by running `pnpm prepare-package-release`
tophatted on my prod store with the snapshot and an address-autocomplete extension.
=> Unstable Release (checkout) for address-autocomplete.suggest

package.json, packages/ui-extensions-react/src/surfaces/admin/render.tsx, packages/ui-extensions-react/src/surfaces/checkout/render.tsx, packages/ui-extensions-react/src/surfaces/customer-account/render.tsx, yarn.lock
The checkout-dev dynamic [docs generation action fails](https://github.com/Shopify/shopify-dev/actions/runs/8696119801/job/23848671756) on the `2023-07` version of `ui-extensions-react` because of TypeScript issues.
The three `render.tsx` files in this version have not been changed in more recent versions, but the action succeeds. 
This PR ignores the TypeScript errors and wraps the return of `children` props in `ErrorBoundary` in a fragment.
- ...
=> Addresses TypeScript errors blocking dynamic docs generation

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/getting-started/app-dev-npm.bash, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/getting-started/app-dev-yarn.bash, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/getting-started/generate-extension.bash, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/getting-started.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pos-overview.doc.ts
This is the first pass at adding a static page. This one covers https://shopify.dev/docs/apps/pos/ui-extensions/getting-started and should have the same content, just in the new format.
I went with 'Generic' sections, which support markdown and code blocks on the side. It seems to look and feel correct for the type of page it is. I also updated the links on the placeholder overview page.
Compare it here:
https://shopify.dev/docs/apps/pos/ui-extensions/getting-started
https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/pos-ui-extensions/unstable/getting-started
=> Add POS UI extension getting started static page.

packages/ui-extensions/docs/surfaces/point-of-sale/build-docs.sh, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/action.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/action.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/menu-item.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/menu-item.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/modal.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/modal.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/tile.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/tile.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.home.modal.render.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.home.tile.render.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.purchase.post.action.menu-item.render.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.purchase.post.action.render.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/extension-targets.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pos-overview.doc.ts
Closes https://github.com/Shopify/pos-next-react-native/issues/36431
This adds the extension target pages in the same method as checkout. It adds the following pages: 
https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/pos-ui-extensions/unstable/extension-targets-overview
https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/pos-ui-extensions/unstable/targets
As well as the four pages you can navigate to from there.
Compare the new pages linked above with how checkout does it:
https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview
https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/checkout-ui-extensions/unstable/targets
=> Add extension targets pages for pos-ui-extensions

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
EPIC: https://github.com/Shopify/ce-customer-behaviour/issues/4868
ISSUE: https://github.com/Shopify/ce-customer-behaviour/issues/4869 
All PRs:
- https://github.com/Shopify/web-pixels-manager/pull/735
- https://github.com/Shopify/ui-extensions/pull/1969
- https://github.com/Shopify/checkout-web/pull/34002
Adding buyer accepts sms marketing as generated from wpm
- ...
=> Added buyer_accepts_sms_marketing to wpm

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/server-communication/modal.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/server-communication/tile.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/server-communication.doc.ts
Closes https://github.com/Shopify/pos-next-react-native/issues/36270
This adds the page for communicating with servers
Old: https://shopify.dev/docs/apps/pos/ui-extensions/authentication
New: https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/pos-ui-extensions/unstable/server-communication
=> Add page for pos-ui-extensions for server communication

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/api-component-not-working.txt, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/cannot-be-used-as-jsx.txt, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/could-not-resolve.txt, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/site-unreachable.txt, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/troubleshooting/unable-to-access.txt, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/troubleshooting.doc.ts
Closes https://github.com/Shopify/pos-next-react-native/issues/36267
- Creates static page for troubleshooting.
https://github.com/Shopify/ui-extensions/assets/81783308/86628dc4-3409-42c3-a1d3-444d792003d3
- Utilizing a generic component with examples in codeblocks separates the content in a logical and readable way that is consistent with other static pages.
- Visit [THIS SPINSTANCE](https://shopify-dev.ui-extensions-90tx.marco-yip.us.spin.dev/docs/api/pos-ui-extensions/unstable/troubleshooting)
- Compare it with the [old docs](https://shopify.dev/docs/apps/pos/ui-extensions/troubleshooting)
- Click through the troubleshooting sections
- Take note of formatting, word choices, and layout
=> Add troubleshooting doc and examples

.changeset/happy-kings-shop.md, packages/ui-extensions-react/src/surfaces/checkout.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/customer-privacy.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/customer-privacy.test.ts, packages/ui-extensions/docs/surfaces/checkout/reference/apis/customer-privacy.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/customer-privacy/default.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/customer-privacy/default.example.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/examples/customer-privacy/sheet-consent-banner-with-form.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/customer-privacy/sheet-consent-banner-with-form.example.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/examples/ui-components/sheet-consent.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/ui-components/sheet-consent.example.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/examples/ui-components/sheet-description-preferences.example.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/examples/ui-components/sheet-icon-button-preferences.example.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/examples/ui-components/sheet-layout-content.example.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/helper.docs.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
This PR introduces examples for the Customer Privacy API, adds the `useCustomerPrivacy` hook, and optimizes the `Sheet` component examples.
[Sheet examples](https://shopify-dev.rc-package-patches.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/unstable/components/overlays/sheet#examples)
[Customer Privacy API examples](https://shopify-dev.rc-package-patches.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/unstable/apis/customer-privacy#examples)
[useCustomerPrivacy hook](https://shopify-dev.rc-package-patches.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/unstable/apis/customer-privacy#useCustomerPrivacy)
- ...
=> adds useCustomerPrivacy hook and updates Sheet and Customer Privacy examples

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/versions.doc.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/36268
This adds the Versioning page to the new docs. I removed versions before 1.0 as they are no longer supported, and the historical reference is not useful. I removed the note on RC's because that's not a part of the unified process any more.
Old: https://shopify.dev/docs/api/pos-extensions/ui-extensions-reference/versions
New: https://shopify-dev.ui-extensions-70k7.nathan-oliveira.us.spin.dev/docs/api/pos-ui-extensions/unstable/versions
=> Add Versions staticPage for pos-ui-extensions

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/debugging.doc.ts
Closes https://github.com/Shopify/pos-next-react-native/issues/36271
- Creates Static page for debugging.
https://github.com/Shopify/ui-extensions/assets/81783308/a7c0f668-39a0-4563-af08-359eafabfd19
- Utilizing a generic component  in a logical and readable way that is consistent with other static pages, and the original debugging page.
- Visit [THIS SPINSTANCE](https://shopify-dev.ui-extensions-90tx.marco-yip.us.spin.dev/docs/api/pos-ui-extensions/unstable/debugging)
- Compare it with the [old docs](https://shopify.dev/docs/apps/pos/ui-extensions/debugging)
- Click through the debugging sections
- Take note of formatting, word choices, and layout
=> Add debugging doc

.changeset/lovely-pots-scream.md, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
Metafields were added to `PickupLocationOption`.
Adds types for metafields in `PickupLocationOption`.
https://shopify-dev.checkout-web-api-docs-53fq.alessandro-dalgrande.us.spin.dev/docs/api/checkout-ui-extensions/unstable/apis/delivery
=> Add metafields to `PickupLocationOption`

packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/Tile.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/tile/default.example.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/tile/default.example.tsx, packages/ui-extensions/src/surfaces/point-of-sale/components/Tile/Tile.ts
Adds some documentation and code examples for the `Tile` component.
Skipping the asset for now, since we're going to be adding fresh ones later.
https://shopify-dev.ui-extensions-7t4u.jeansebastien-goupil.us.spin.dev/docs/api/pos-ui-extensions/unstable/components/tile
=> Added docs and example for tile

packages/ui-extensions/docs/surfaces/checkout/reference/examples/customer-privacy/sheet-consent-banner-with-form.example.tsx
`handleConsentChange` is called from the accept and reject buttons in addition to the form submission. The form's onSubmit logic was updated in the [JS example](https://github.com/Shopify/checkout-web/blob/main/packages/ui-extensions/docs/surfaces/checkout/reference/examples/customer-privacy/sheet-consent-banner-with-form.example.ts#L158), but the react example was passing the method as the prop, which means it would receive the submit event, but it expects an optional visitor consent object.
[Customer Privacy API example](https://shopify-dev.checkout-web-api-docs-dmx2.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/unstable/apis/customer-privacy#examples)
=> updates sheet consent banner with form example

.changeset/calm-crabs-run.md, packages/ui-extensions-react/src/surfaces/checkout/render.tsx, packages/ui-extensions-react/src/surfaces/customer-account/render.tsx, packages/ui-extensions-react/src/surfaces/point-of-sale/render.tsx, packages/ui-extensions/docs/surfaces/checkout/reference/targets/customer-account.order-status.block.render.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.checkout.block.render.doc.ts, packages/ui-extensions/docs/surfaces/checkout/reference/targets/purchase.thank-you.block.render.doc.ts, packages/ui-extensions/docs/surfaces/checkout/staticPages/extension-overview.doc.ts, packages/ui-extensions/docs/surfaces/checkout/staticPages/overview.doc.ts, packages/ui-extensions/src/surfaces/checkout/targets.ts, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Part of https://github.com/Shopify/core-issues/issues/70723
- ...
=> Renames locations to placement in developer documentation

packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/Badge.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/Banner.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/badge/default.example.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/badge/default.example.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/banner/default.example.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/banner/default.example.tsx, packages/ui-extensions/src/surfaces/point-of-sale/components/Badge/Badge.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/36292
Adds Badge and Banner examples, descriptions for props and guidelines.
- [Badge](https://shopify-dev.ui-extensions-psgn.victor-chu.us.spin.dev/docs/api/pos-ui-extensions/unstable/components/badge)
- [Banner](https://shopify-dev.ui-extensions-psgn.victor-chu.us.spin.dev/docs/api/pos-ui-extensions/unstable/components/banner)
=> POS UI Ext: add badge and banner examples to docs

packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/EmailField.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/NumberField.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/email-field/email-input.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/email-field/email-input.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/number-field/number-input.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/number-field/number-input.tsx, packages/ui-extensions/src/surfaces/point-of-sale/components/NumberField/NumberField.ts
closes https://github.com/Shopify/pos-next-react-native/issues/36298
- Updated docs for NumberField and added examples in react and vanilla typescript.
- Omitted inputMode, max, and min props due to the fact that they were not working in Storybook and in Ui extensions. I will revisit this in a future PR.
- Updated docs for EmailField and added examples in react and vanilla typescript. 
https://github.com/Shopify/ui-extensions/assets/81783308/1f8988d1-3cc1-4989-8fd2-15b8ab7f79b1
- Visit [THIS SPINSTANCE](https://shopify-dev.ui-extensions-snq3.marco-yip.us.spin.dev/docs/api/pos-ui-extensions/unstable/components/numberfield)
- Compare it with the old docs [NumberField](https://shopify.dev/docs/api/pos-extensions/ui-extensions-reference/components/number-field) …
=> update number and email field docs

packages/ui-extensions/docs/surfaces/point-of-sale/reference/apis/navigation-api.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/apis/scanner-api.doc.ts, packages/ui-extensions/src/surfaces/point-of-sale/targets.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/37280
The ScannerAPI and the NavigationAPI do work for the post purchase action target, however we were not adding it to the type in the package. This fixes the problem, and will allow developers to see that these APIs do exist on these targets. I also updated our docs. 
- ...
=> Added navigation and scanner APIs to PP action

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
Part of https://github.com/Shopify/ce-customer-behaviour/issues/2815
Ran `yarn schema:publish` in the WPM repo
- Can't tophat reliably, checkout-web uses the internal package.
=> Add localization to Web Pixels checkout object

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
Part of https://github.com/Shopify/ce-customer-behaviour/issues/4994
WPM PR: https://github.com/Shopify/web-pixels-manager/pull/769
Adds `orderCount` to `OrderCustomer` type
https://shop1.shopify.orders-count-v5.james-calverley.us.spin.dev/
For detailed instructions on manually adding orders please look at this [WPM PR](https://github.com/Shopify/web-pixels-manager/pull/769)
=> Add ordersCount to Web Pixels checkout.order.customer 

.changeset/rich-chicken-repeat.md, packages/ui-extensions-react/src/surfaces/checkout.ts, packages/ui-extensions/src/surfaces/checkout/components.ts, packages/ui-extensions/src/surfaces/checkout/components/BlockLayout/BlockLayout.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/BlockStack/BlockStack.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/BlockStack/BlockStack.ts, packages/ui-extensions/src/surfaces/checkout/components/Grid/Grid.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/Grid/Grid.ts, packages/ui-extensions/src/surfaces/checkout/components/GridItem/GridItem.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/GridItem/GridItem.ts, packages/ui-extensions/src/surfaces/checkout/components/InlineLayout/InlineLayout.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/InlineStack/InlineStack.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/InlineStack/InlineStack.ts, packages/ui-extensions/src/surfaces/checkout/components/Pressable/Pressable.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/Pressable/Pressable.ts, packages/ui-extensions/src/surfaces/checkout/components/ScrollView/ScrollView.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/ScrollView/ScrollView.ts, packages/ui-extensions/src/surfaces/checkout/components/View/View.doc.ts, packages/ui-extensions/src/surfaces/checkout/components/View/View.ts, packages/ui-extensions/src/surfaces/checkout/components/shared.ts, packages/ui-extensions/src/surfaces/checkout/style/examples/hiding.example.tsx, packages/ui-extensions/src/surfaces/checkout/style/style.doc.ts, packages/ui-extensions/src/surfaces/checkout/style/types.ts
Part of https://github.com/Shopify/checkout-web/issues/34173
Publish the display property on supported components
Docs:
- `Grid`: https://shopify-dev.checkout-web-api-docs-3xx8.nicolas-cardelino.us.spin.dev/docs/api/checkout-ui-extensions/unstable/components/structure/grid#gridprops-propertydetail-display
- `View`: https://shopify-dev.checkout-web-api-docs-3xx8.nicolas-cardelino.us.spin.dev/docs/api/checkout-ui-extensions/unstable/components/structure/view#viewprops-propertydetail-display
`checkout-web` PR: https://github.com/Shopify/checkout-web/pull/34507
=> [UI Components]: Publish display property

packages/ui-extensions/docs/surfaces/point-of-sale/reference/apis/action-api.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/apis/customer-api.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/apis/product-api.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/customer-api/id.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/customer-api/id.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/product-api/id.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/customer-details-action.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/customer-details-action.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/customer-details-menu-item.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/examples/targets/customer-details-menu-item.tsx, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.customer-details.action.menu-item.render.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.customer-details.action.render.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/types/ExtensionTargetType.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/extension-targets.doc.ts, packages/ui-extensions/src/surfaces/point-of-sale/api.ts, packages/ui-extensions/src/surfaces/point-of-sale/api/customer-api/customer-api.ts, packages/ui-extensions/src/surfaces/point-of-sale/targets.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/37677
Adds the customer detail's apis, targets and documentation
https://shopify-dev.ui-extensions-ttt9.victor-chu.us.spin.dev/docs/api/pos-ui-extensions/unstable/targets
=> Add CustomerAPI to POS UI ext

packages/ui-extensions/src/surfaces/point-of-sale/targets.ts
Adds missing CartAPI to Draft Order Action Menu Item api extensions.
- [Spinstance](https://shopify-dev.ui-extensions-xyt4.marco-yip.us.spin.dev/docs/api/pos-ui-extensions/unstable/targets)
=> add cartapi to draft order action menu item

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
Part of https://github.com/Shopify/ce-customer-behaviour/issues/4217
Depends on https://github.com/Shopify/web-pixels-manager/pull/815
Add more details to the payment methods used at checkout
Ran `yarn schema:publish` in wpm
=> Add paymentMethod to Web Pixel's checkout.transactions object

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
Part of https://github.com/Shopify/ce-customer-behaviour/issues/5069
WPM PR: https://github.com/Shopify/web-pixels-manager/pull/817
Add `properties` to `CheckoutLineItem`
https://shop1.shopify.checkout-line-item.james-calverley.us.spin.dev/
View product
Add additional information in the custom properties
Add product to cart
Checkout
Ensure that the properties you have added are captured in the checkout_started and checkout_completed events.
=> Add line item properties to Web Pixel checkout data

packages/web-pixels-extension/src/types/ExtensionApi.ts, packages/web-pixels-extension/src/types/WebPixelsManager.ts
EPIC: https://github.com/Shopify/ce-customer-behaviour/issues/4868
ISSUE: https://github.com/Shopify/ce-customer-behaviour/issues/5357
The final step to release our new types is update the wpm ui-extensions packages so our new types can be seen.
Ran `yarn schema:publish`
We can see code completion showing our new types in the web pixels test app and not complaining about the callback type signature
- ...
=> Wpm 1.10 update

.github/workflows/changesets-reminder.yml, .github/workflows/deploy.yml
Background
This adds the `2024-07` to the changeset reminder and deploy actions in `unstable` which are added in the `2024-07` branch.
=> Updates github actions in for 2024-07

packages/ui-extensions/docs/surfaces/customer-account/build-docs.sh
Even if we have said that the type input should only come from `src/surfaces/customer-account` , we can still get types from checkout.  ( for example the hooks )
Do not include any react version types from other folders. 
1. with this branch there is no warning saying there are more than 1 definitions for `UseShippingAddressGeneratedType` when generating the doc
unstable branch:
this branch:
2. The docs still have correct and clickable types
https://shopify-dev.typetype.brian-shen.us.spin.dev/docs/api/customer-account-ui-extensions/unstable/apis/order-status-api/addresses
=> avoid duplicated types from checkout when generating docs

.changeset/warm-tigers-sin.md, packages/ui-extensions/src/surfaces/checkout/components/View/View.ts
The `position` property documentation is difficult to read.
Fix `View` component's `position` property documentation.
Docs: https://shopify-dev.checkout-web-api-docs-q8qm.nicolas-cardelino.us.spin.dev/docs/api/checkout-ui-extensions/unstable/components/structure/view#viewprops-propertydetail-position
=> [UI Components]: Fix View position property documentation

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts
EPIC: https://github.com/Shopify/ce-customer-behaviour/issues/4868
ISSUE: https://github.com/Shopify/ce-customer-behaviour/issues/5369
Ran `yarn schema:publish` but reverted the wildcard type updates
- ...
=> added sms marketing phone to web pixels

packages/ui-extensions/docs/surfaces/checkout/build-docs.sh
- We've been facing issues where the generate docs script gets duplicate documentation. and adds mentions of build files on docs, like seen on [this PR](https://github.com/Shopify/shopify-dev/pull/46425)
- Removing the ui-react packages from the generation fixes the issue.
- ...
=> [Docs]: Removing react types from docs generation

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/migrating/setup.npm.bash, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/examples/migrating/setup.yarn.bash, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/migrating.doc.ts
We added a new step in the deploy process for the CLI. I updated the migration docs to reflect this.
You should be able to view the changes here https://shopify-dev.ui-extensions-y1g3.jeansebastien-goupil.us.spin.dev/docs/api/pos-ui-extensions/2024-04/migrating
=> Added CLI step to pos migration docs

packages/ui-extensions/src/surfaces/customer-account/components/Menu/Menu.ts
- checkout PR adding the props to Menu: https://github.com/Shopify/checkout-web/pull/36308
- customer account web PR allowing the props: https://github.com/Shopify/customer-account-web/pull/5056
I am just documenting and adding types for `onClose` and `onOpen` on Menu.
The two new props should be visible on https://shopify-dev.customer-account-web-shopify-dev-2fja.sylvain-hamann.us.spin.dev/docs/api/customer-account-ui-extensions/unstable/components/menu
Resume: 
https://spin-control.shopify.io/instances/customer-account-web-shopify-dev-2fja.sylvain-hamann.us.spin.dev/resume
=> expose more Menu props

packages/web-pixels-extension/package.json
Bump WPM public package after shipping [this PR](https://github.com/Shopify/ui-extensions/pull/2242) to update Checkout schema.
Check that a tag with a matching commit hash was created [here](https://github.com/Shopify/ui-extensions/tags).
Following from step 4 of [this guide](https://github.com/Shopify/web-pixels-manager/blob/main/help-docs/updating-events.md#updating-the-public-package) to update the WPM public package
=> Bump WPM public package after making Checkout schema changes

packages/ui-extensions-react/src/surfaces/point-of-sale.ts, packages/ui-extensions/src/surfaces/point-of-sale/components.ts
This export is missing from the chain so it can't be imported in extensions.
Add the export
=> POS: Add missing BadgeStatus export

packages/ui-extensions/src/surfaces/point-of-sale/components/POSBlock/POSBlockRow.ts, packages/ui-extensions/src/surfaces/point-of-sale/targets.ts
As we discovered, implementing custom selectable rows by removign insets and using a Selectable plus Stack with the correct insets is tedious and will likely result in 3P devs using the wrong padding.
This will guarantee the correct padding.
Should we also remove Selectable from the allowable components list? I'm leaning on yes.
- ...
=> Added an onPress handler for block row

packages/ui-extensions/docs/surfaces/customer-account/staticPages/overview.doc.ts
https://shopify.dev/docs/api/customer-account-ui-extensions#tutorials is missing a link to the metafields tutorial.
Add a link
https://shopify-dev.doc-update.jr-rafols.us.spin.dev/docs/api/customer-account-ui-extensions#tutorials
[resume](https://spin-control.shopify.io/instances/doc-update.jr-rafols.us.spin.dev/resume)
=> Link to the Metafields tutorial from Customer Account UI extension page

packages/ui-extensions/src/surfaces/point-of-sale/components/FormattedTextField/FormattedTextField.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/27757
It seems that callbacks for extensions cannot be defined with a return value other than void. I'm not exactly sure why extensions can't return values from callbacks but to resolve this issue lets deprecate and remove this for 2025-01 since it was never working in the first place.
You can find my investigations in the ticket issue description. Open to solutions.
If the team is fine with this, I will close the original issue and open a new one to track removal of this callback after 2024-10 gets released.
=> Deprecate custom validator from formatted text field

.changeset/light-dancers-pump.md, packages/ui-extensions/src/surfaces/admin/components/NumberField/NumberField.ts, packages/ui-extensions/src/surfaces/admin/components/TextField/TextField.ts, packages/ui-extensions/src/surfaces/admin/components/shared/index.ts
Add the ability to add a suffix to TextFields and NumberFields
=> Add suffix to textfield and numberfield apis

packages/ui-extensions/docs/surfaces/checkout/build-docs.sh
- revert changes added [here](https://github.com/Shopify/ui-extensions/pull/2297/files#diff-2d8e23187e91310e596a2241803ca7eb4d2411d06b9c630b2540344c48a901fb) causing the docs generation to break.
- reverting files
- https://shopify-dev.revert-docs-script.igor-deoliveiramartins.us.spin.dev/docs/api/checkout-ui-extensions
=> revert build-docs.sh script

package.json, packages/ui-extensions/package.json, yarn.lock
To solve the issue of `Extension` and `Location` not correctly linking to their APIs we need to update the `generate-docs` version in 2024-04. This is the checkout-web part of https://github.com/Shopify/checkout-web/issues/37106
This is the PR for it being updated in `unstable` : https://github.com/Shopify/ui-extensions/pull/2313
It is also being updated in `2024-07`
spin link for extension: https://shopify-dev.regenerate-verison.hayley-dixon.us.spin.dev/docs/api/checkout-ui-extensions/2024-04/apis/extension
spin link for location: https://shopify-dev.regenerate-verison.hayley-dixon.us.spin.dev/docs/api/checkout-ui-extensions/2024-04/apis/localization
- ...
=> update generate-doc version for 2024-04

packages/web-pixels-extension/src/schemas/pixel-events.ts, packages/web-pixels-extension/src/types/PixelEvents/index.ts, packages/web-pixels-extension/src/types/RegisterInit.ts, packages/web-pixels-extension/src/types/index.ts
Part of https://github.com/Shopify/core-issues/issues/73165
Code auto generated from running `yarn schema:publish` in `web-pixels-manager` https://github.com/Shopify/web-pixels-manager/pull/869
Contains only changes related to the addition of the purchasingCompany object to the web-pixels-manager. I've removed any generated unrelated changes.
https://development-store-1.shopify.ui-extension-test.tiger-cao.us.spin.dev/
⚠️ We need to be on development-store-1 instead of store 1
Ping me to start the web pixels extension locally `@tiger` on slack to ensure the fields are properly exposed on the web pixels public API
1. Login as `b2b-customers-e2e@shopify.com` in the storefront
2. If prompted for 6-digit code, go to Identity Mailer under `customer-account-web` to grab the login code
3. In …
=> [Web Pixels] Generate purchasing company in ui-extensions

packages/ui-extensions/package.json
...by using `bash` rather than `sh` because it properly supports double square brackets.
Docs building is broken in Spin right now because we're running scripts with `sh` rather than `bash` or `zsh`. I don't know why it doesn't fail in MacOS. Maybe `sh` is a different version?
Previous attempts: e.g. #2319 #2296
=> Fix docs building in Spin

packages/ui-extensions/src/surfaces/checkout/targets.ts
It was decided to rename the previously generic `purchase.checkout.overlay.render` and `purchase.thank-you.overlay.render` to a feature specific name. In our case, its for the Chat feature.
New:
- `purchase.checkout.chat.render`
- `purchase.thank-you.chat.render`
=> Checkout: rename `overlay` target to `chat`

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/debugging.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/migrating.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/versions.doc.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/41823
We recently added the ability to debug on iOS for UI Extensions. This is the accompanying documentation.
Checkout this link: 
https://shopify-dev.ui-extensions-5cav.jeansebastien-goupil.us.spin.dev/docs/api/pos-ui-extensions/unstable/debugging#debugging-on-ios
=> Added iOS debugging docs for POS UI Extensions

.changeset/new-badgers-mix.md, packages/ui-extensions/src/surfaces/customer-account/targets.ts
Part of this ticket https://github.com/Shopify/core-issues/issues/76913 
resolves https://github.com/Shopify/core-issues/issues/76861 
Add full page extension API to order full page extension target. 
The PR itself is just adding the interface, if you want to test the real function, follow tophat here: 
https://github.com/Shopify/customer-account-web/pull/5449
=> add full page navigation api to order full page

package.json, scripts/generator.js
Fixes https://github.com/Shopify/app-ui/issues/1479
Create a generator script that can take existing TS interfaces for the component props and generate definitions that can be used for calling `createRemoteElement` on remote-dom.
This is an internal-only tool and should not affect any end users.
=> Definition generator

packages/ui-extensions/src/surfaces/point-of-sale/api/navigation-api/navigation-api.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/42158
- While working on the [NavigationAPI](https://github.com/Shopify/pos-next-react-native/pull/41613), it was identified that wording for the `dismiss` prop needed clarification.
|Before|After|
|--|--|
|<img width="709" alt="image" src="https://github.com/user-attachments/assets/65448e11-5448-41bf-b6ef-690346e0e13a">|<img width="691" alt="image" src="https://github.com/user-attachments/assets/4a7513a6-ddfd-4dad-93a3-4ec4172436ec">|
- The description was updated.
- https://shopify-dev.ui-extensions-479f.marco-yip.us.spin.dev/docs/api/pos-ui-extensions/unstable/apis/navigation-api
=> update dismiss prop description

.changeset/tasty-coats-shave.md, packages/ui-extensions-react/src/surfaces/customer-account/hooks/live-navigation.ts, packages/ui-extensions-react/src/surfaces/customer-account/hooks/tests/live-navigation.test.tsx
update error message for `useNavigationCurrentEntry`.
This hook can also be used when the extension target is `customer-account.order.page.render` . 
Content confirmed with @deannatron
=> update error message for useNavigationCurrentEntry

.changeset/eight-peas-buy.md, packages/ui-extensions-react/src/surfaces/checkout/components/Modal/Modal.ts, packages/ui-extensions/src/surfaces/checkout/components/Modal/Modal.ts
- Export new primary and secondary actions for modal component
- Exporting the properties
- [Docs](https://shopify-dev.primary-secondary-modal-actions.igor-deoliveiramartins.us.spin.dev/docs/api/checkout-ui-extensions/unstable/components/overlays/modal)
=> [Modal]: Primary and Secondary actions

.changeset/old-zebras-exist.md, packages/ui-extensions/docs/surfaces/admin/staticPages/admin-extensions.doc.ts, packages/ui-extensions/docs/surfaces/admin/staticPages/examples/custom-authenticated-fetch.jsx, packages/ui-extensions/src/surfaces/admin/api/standard/standard.ts
Fixes https://github.com/Shopify/app-ui/issues/1507
RE: https://github.com/Shopify/app-ui/issues/1619
Admin UI extensions have an API for fetching an OpenID Connect ID token for the currently authenticated user, but we forgot to document it. We patch `fetch` to the app developer's origin to automatically include the `Authorization` header. 
However, a developer may wish to call additional third-party domains and will require access to this Authorization token. 
This PR outlines how they can leverage the existing undocumented `auth` API to do so.
=> Document missing `auth.idToken.get()` API

packages/ui-extensions/src/surfaces/customer-account/api.ts, packages/ui-extensions/src/surfaces/customer-account/api/standard-api/standard-api.ts
To make it consistent [with checkout](https://github.com/Shopify/ui-extensions/blob/unstable/packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts#L240)
=> rename RendererVersion to Version and type as string

packages/ui-extensions/docs/surfaces/customer-account/reference/targets/customer-account.order.page.render.doc.ts, packages/ui-extensions/docs/surfaces/customer-account/reference/targets/customer-account.page.render.doc.ts, packages/ui-extensions/docs/surfaces/customer-account/staticPages/examples/custom-protocols/extension-link.example.tsx, packages/ui-extensions/docs/surfaces/customer-account/staticPages/extension-targets-overview.doc.ts, packages/ui-extensions/docs/surfaces/customer-account/staticPages/overview.doc.ts
Big shout-out to @deannatron for her great work!
Add docs for `customer-account.order.page.render` target together with updating existing `customer-account.page.render` extension 
Figma here https://www.figma.com/board/RmPHPRlPNZT9vLSncNZW4C/Order-full-page-extension?node-id=0-1&node-type=canvas&t=73kBLjfn2hOxVWU9-0 
And I attached all the figma and spin link for each updated file.
=> Add doc for `customer-account.order.page.render`

packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
Partially solves https://github.com/Shopify/checkout-web/issues/37877
Provides a fast fix for removing `acceptsMarketing` from customer profiles. This was depricate. The removal from `checkout-web` will need to be fast follow up after the release tomorrow. 
- ...
=> removes acceptsMarketing from customer profile

packages/ui-extensions/docs/surfaces/customer-account/categories/components.doc.ts
Link currently always points to prod and unstable.
It should work in all envs and go to the currently used version not be hardcoded to prod.
=> use proper link for components

packages/ui-extensions/docs/surfaces/customer-account/reference/examples/navigation/default-react.example.tsx, packages/ui-extensions/docs/surfaces/customer-account/reference/examples/navigation/event-listeners.example.tsx, packages/ui-extensions/docs/surfaces/customer-account/reference/examples/navigation/navigating-to-customer-account-page.example.tsx, packages/ui-extensions/docs/surfaces/customer-account/reference/examples/navigation/use-current-entry.example.tsx
Resolves https://github.com/Shopify/shopify-dev-feedback/issues/5507
Resolves https://github.com/Shopify/core-issues/issues/67196
Examples were using `render` instead of `reactExtension`
I'll hold off on generating the docs for `shopify-dev` until the `2024-10` release goes out to avoid interfering with some larger doc release work
Update the code. Also use `useApi` instead of passing the `api` prop
Trying out local dev with this so no instance. Since these are just code examples, I think code review should be sufficient, but I'll include some screenshots of what the rendered content looks like:
(Not sure why this isn't doing any code highlighting, but it was like this before my change as well)
=> Update navigation examples to use `reactExtension`

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/versions.doc.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/43365
Add a mention of windowed modals to the versions page.
=> Add mention of windowed modals

packages/ui-extensions-react/src/surfaces/admin/render.tsx, packages/ui-extensions-react/src/surfaces/point-of-sale/render.tsx, packages/ui-extensions-react/src/utilities/remoteRootRender.ts, packages/ui-extensions/src/extension.ts
Currently all of our teardown functionality does not work. For example, the return method from a useEffect does not work in UI Extensions for POS (and I think on the other surfaces it's also broken?).
This replaces the deprecated render call with the `createRoot` function, which returns a root which has a `render` function, and an `unmount` function. We are passing the unmount method into the `Promise.resolve`, which means that it can be used on the host side to properly `unmount` everything when POS unmounts the `UIExtensionContainer`.
You can tophat this on POS with the following POS Branch:  https://github.com/Shopify/pos-next-react-native/pull/42289
1. Pull this branch to your machine.
2. Run yarn build, and go to the build directory for ui-extensions-react, and find the …
=> Update POS render function to use createRoot

.changeset/bright-lemons-knock.md, packages/data-extensions/README.md, packages/data-extensions/loom.config.ts, packages/data-extensions/package.json, packages/data-extensions/src/api.ts, packages/data-extensions/src/extension.ts, packages/data-extensions/src/index.ts, packages/data-extensions/src/surfaces/admin.ts, packages/data-extensions/src/surfaces/admin/api.ts, packages/data-extensions/src/surfaces/admin/api/standard/README.md, packages/data-extensions/src/surfaces/admin/api/standard/standard.ts, packages/data-extensions/src/surfaces/admin/extension-targets.ts, packages/data-extensions/src/surfaces/admin/extension.ts, packages/data-extensions/src/surfaces/admin/globals.ts, packages/data-extensions/src/utilities/registration.ts, packages/data-extensions/tsconfig.json, packages/ui-extensions-react/README.md, packages/ui-extensions/README.md, tsconfig.json
Related to new type of extension: [data extension](https://docs.google.com/document/d/14Y9EoL0b9M8x1K2yEdugBqjrwFeB1vXUXbjOVcMrj74/edit?tab=t.0#heading=h.vqkbcd97wgda)
Closes https://github.com/Shopify/app-ui/issues/1699
- Add targets for conditional rendering action extensions in admin
- Expose `dataExtension` registration function
- Copy existing patterns from ui-extensions
Latest snapshot: `"@shopify/data-extensions": "0.0.0-snapshot-20241018231554",`
- Add a data extension that looks like this:
```ts
import {dataExtension} from '@shopify/data-extensions/admin';
export default dataExtension("admin.product-details.action.should-render", () => {
return {display: false};
});
```
- Use the snapshot build in your data extension
- Make sure to update the target in the toml file too.
- …
=> Add data extensions package with conditional action targets

.changeset/hot-shirts-clean.md, packages/ui-extensions/src/surfaces/point-of-sale/api/print-api/print-api.ts
Resolves https://github.com/Shopify/pos-next-react-native/issues/45380
Part of https://github.com/Shopify/pos-next-react-native/issues/41454
This switches the interface return type from `void` to `Promise<void>`. We have validated the implementation using Yalc.
https://github.com/user-attachments/assets/94fe13d3-caac-40d5-ac6c-2309944a36b4
=> Make print api print action async

packages/ui-extensions/src/surfaces/admin/components/InternalCustomerSegmentTemplate/InternalCustomerSegmentTemplate.ts
We are adding a few templates that require this `walletMajor` icon
- ...
=> Add wallet icon for Template Icons

packages/ui-extensions/src/surfaces/admin/components/InternalCustomerSegmentTemplate/InternalCustomerSegmentTemplate.ts
Reverts Shopify/ui-extensions#2463
Originally missing the changelog
=> Revert "Add wallet icon for Template Icons"

.changeset/clever-actors-cry.md, packages/ui-extensions/src/surfaces/admin/components/InternalCustomerSegmentTemplate/InternalCustomerSegmentTemplate.ts
We are adding a few templates that require this `walletMajor` icon (adding changeset)
- ...
=> Add wallet icon for Template Icons (fixed with changeset)

.changeset/rotten-donuts-clap.md, packages/ui-extensions/src/surfaces/admin/components/AdminBlock/AdminBlock.ts
Adding a new prop for dev to add summary text when the Block Extension has no content.
- ...
=> add collapsedSummary prop to AdminBlock 

.changeset/spicy-mugs-drop.md, packages/ui-extensions/src/surfaces/admin.ts, packages/ui-extensions/src/surfaces/admin/globals.ts, packages/ui-extensions/src/surfaces/checkout/globals.ts, packages/ui-extensions/src/surfaces/customer-account/globals.ts, packages/ui-extensions/src/surfaces/point-of-sale/globals.ts
The `shopify` global declaration was incorrect all along. With these changes doing `shopify.extend` inside an extension now works to pick up the types. 
Try this out by consuming the snapshot build and inside an extension either use the `/// <reference types="@shopify/ui-extensions/admin" />` or import the `extension` function.
=> Fix missing global shopify type for Admin

packages/ui-extensions/docs/surfaces/admin/staticPages/targets-overview.doc.ts
Add references to `should-render` targets. 
Related docs PR: https://github.com/Shopify/shopify-dev/pull/51338
Extend descriptions in existing action extension targets.
- See docs [PR](https://github.com/Shopify/shopify-dev/pull/51338)
=> Update action target descriptions to include should-render

packages/ui-extensions/src/surfaces/admin/api/should-render/should-render.doc.ts
We moved the target-specific APIs around, now under "API -> Target APIs". ShouldRender missed the cutoff.
See: https://shopify-dev.docs.mitch-lillie.us.spin.dev/docs/api/admin-extensions/unstable/api/target-apis/shouldrender-api
- ...
=> Nest shouldrender under target APIs

packages/ui-extensions/src/surfaces/admin/api/action/action.ts, packages/ui-extensions/src/surfaces/admin/api/picker/picker.doc.ts, packages/ui-extensions/src/surfaces/admin/api/print-action/print-action.ts, packages/ui-extensions/src/surfaces/admin/api/resource-picker/resource-picker.doc.ts
**Do Not Merge:** Will need to rebase after https://github.com/Shopify/ui-extensions/pull/2379 ships so we can update this PR to include the `GenericPicker` being available in `ActionExtensionsApi`
Related to https://github.com/Shopify/app-ui/issues/1756
Should ship after https://github.com/Shopify/web/pull/146520 and https://github.com/Shopify/ui-extensions/pull/2379
Follow up `shopify-dev` PR https://github.com/Shopify/shopify-dev/pull/50766
Add `resourcePicker` and `genericPicker` Api to Action Extension Api to support the new Resource Picker availability in action extensions.
Update the `ActionExtensionApi` interface to include the `ResourcePickerApi` and `GenericPickerApi`
**NOTE**: Will need to check on https://github.com/Shopify/shopify-dev/pull/49753 to see if there's verbage …
=> [Admin Extension Docs] Add `resourcePicker` to Action Extension Api docs

.changeset/curly-bugs-suffer.md
As a follow up PR for P[OS Image sizing and Box component implementation](https://github.com/Shopify/ui-extensions/pull/2524), This PR adds the required changesets for the Image and Box component to be published with the POS UI Extensions Packages.
Publish Unstable
- ...
=> Add Changeset for Image and Box Component Updates

packages/ui-extensions/src/surfaces/point-of-sale/render/components/shared/inner-layouts.ts
Adds [row and column gap ](https://github.com/Shopify/ui-api-design/blob/177092940cd7202d5d3a81973ef9781f6eb6c53d/ui-api-design/shared/inner-layout.ts#L24-L33) overrides for the Stack component. 
This is a really useful addition for when a Stack wraps to another line as it allows the dev to customize spacing along both axis.
- ...
=> Adds row and column gap for POS stack

packages/ui-extensions/docs/surfaces/checkout/reference/examples/localized-fields/default.example.ts, packages/ui-extensions/docs/surfaces/checkout/reference/examples/localized-fields/default.example.tsx
This PR optimizes comments in the localized field API examples.
There's no change log entry for this because the update pertains to docs only and not anything exported from the package.
[Localized Fields API docs](https://shopify-dev.unstable-release.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/unstable/apis/localized-fields)
=> [Checkout UI extensions] Optimizes localized field example comments

.changeset/chatty-mugs-appear.md, .changeset/clever-actors-cry.md, .changeset/curly-bugs-suffer.md, .changeset/famous-parents-punch.md, .changeset/fluffy-rules-burn.md, .changeset/fuzzy-trainers-work.md, .changeset/gorgeous-zebras-trade.md, .changeset/healthy-cups-wash.md, .changeset/hot-insects-float.md, .changeset/hot-shirts-clean.md, .changeset/hot-years-relate.md, .changeset/itchy-readers-think.md, .changeset/kind-flowers-dress.md, .changeset/lemon-dots-rhyme.md, .changeset/many-ways-leave.md, .changeset/moody-rings-call.md, .changeset/neat-paws-smile.md, .changeset/orange-baboons-grab.md, .changeset/rotten-donuts-clap.md, .changeset/rude-suns-type.md, .changeset/slimy-knives-decide.md, .changeset/spicy-mugs-drop.md, .changeset/stale-planes-wonder.md, .changeset/sweet-toes-taste.md, .changeset/unlucky-cows-vanish.md, packages/ui-extensions-react/CHANGELOG.md, packages/ui-extensions/CHANGELOG.md
- **removes changelog files for released 2025-01 changes**
- **updates ui-extensions and ui-extensions-react changelog files with 2025.1.0 entries**
- ...
=> Updates unstable changelogs with 2025-01 changes

packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/Stack.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/Text.doc.ts
We changed the behaviour of Text and Stack to solve a bug where Text was not truncating properly on POS. The new behaviour is as such:
- Stacks always wrap content to the next column or row (in alignment with other extension surfaces).
- Text will always take up the most that it can horizontally, however, wrapping it in a Box will make it take only the amount that it needs. You can also use a Box to set a maximum width. In both of those cases, the Text will wrap to the second line (max 2 lines) and truncate if it's even longer than that.
- ...
=> Documented Text and Stack changes

packages/ui-extensions/docs/surfaces/point-of-sale/reference/components/PrintPreview.doc.ts
There are rendering limitations with the PrintPreview component. This PR adds a note which epxlicity tells developers to use it directly as a child of the Screen component
https://shopify-dev.ui-extensions-pp9g.victor-chu.us.spin.dev/docs/api/pos-ui-extensions/unstable/components/printpreview
=> Add note for print preview

.changeset/rude-cheetahs-invite.md, packages/ui-extensions-react/src/surfaces/checkout.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/localized-fields.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/localized-fields.test.ts, packages/ui-extensions/docs/surfaces/checkout/reference/apis/localized-fields.doc.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
This PR optimizes the `useLocalizedFields` hook and introduces the `useLocalizedField` hook. It also updates the related docs.
[Unstable localized field API docs](https://shopify-dev.checkout-web-api-docs-es7w.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/unstable/apis/localized-fields)
=> Updates localized field hooks in `Unstable`

.changeset/grumpy-crabs-buy.md, packages/ui-extensions-react/src/surfaces/checkout.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/localized-fields.ts, packages/ui-extensions-react/src/surfaces/checkout/hooks/tests/localized-fields.test.ts, packages/ui-extensions/docs/surfaces/checkout/reference/apis/localized-fields.doc.ts, packages/ui-extensions/src/surfaces/checkout/api/standard/standard.ts
This PR optimizes the useLocalizedFields hook and introduces the useLocalizedField hook. It also updates the related docs.
[Localized field API docs](https://shopify-dev.update-2025-01.rick-caplan.us.spin.dev/docs/api/checkout-ui-extensions/2025-01/apis/localized-fields) for `2025-01` version
=> Update localized field hooks in `2025-01`

.changeset/funny-walls-flash.md, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.cash-tracking-session-cancel.event.observe.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.cash-tracking-session-complete.event.observe.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.cash-tracking-session-start.event.observe.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/targets/pos.transaction-complete.event.observe.doc.ts, packages/ui-extensions/docs/surfaces/point-of-sale/reference/types/ExtensionTargetType.ts, packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/versions.doc.ts, packages/ui-extensions/src/surfaces/point-of-sale/event/input/CashTrackingSessionInput.ts, packages/ui-extensions/src/surfaces/point-of-sale/event/targets.ts
Part of, https://github.com/Shopify/pos-next-react-native/issues/51030
- Rename event-initiated extension targets per https://github.com/Shopify/pos-next-react-native/issues/51181
- Add 3 cash tracking session targets for POS Compliance.
- `pos.cash-tracking-session-start.event.observe`
- `pos.cash-tracking-session-cancel.event.observe`
- `pos.cash-tracking-session-complete.event.observe`
- Added preliminary inputs for Cash session object.
- Add to docs.
- TODO: how?
=> Add cash tracking session event targets for POS Compliance

.changeset/ten-goats-wink.md, packages/ui-extensions/src/surfaces/point-of-sale/types/shipping-line.ts
TS on the POS side is having a hard time reconciling the idea that methodType only exists on one of the types. Let's just unified the type, and make methodType optional, in the case of custom. Much simpler interface and we can document it easily.
- ...
=> Unified type for shipping line

.changeset/mean-glasses-burn.md, packages/ui-extensions/src/surfaces/point-of-sale/event/input/TransactionCompleteInput.ts
Turns out this thing isn't really a GID. Just a UUID string
- ...
=> Made draftOrderId a string

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
=> [2023-10] Update Payment documentation 

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
=> [2024-01] Update Payment Option Documentation 

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
=> [2024-04] Update Payment Api Documentation

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
=> [2024-07]Fix payment options documentation

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
=> [2024-10] Fix Payment Options Documentation 

packages/ui-extensions/docs/surfaces/checkout/reference/apis/payment-options.doc.ts
=> [2025-01] Fix Payment API documentions 

.changeset/lovely-keys-compare.md
According to this PR: https://github.com/Shopify/ui-extensions/pull/2602/files#diff-e80441d67ba95ef3601f023a0ef3600aa055368fb53c8b147bc1daaf30f32fc5
Ui-extension version is `2025.1.1`
Ui-extensions-react version is `2025.1.2`
This PR is to make them the same.
Anything I miss?
- ...
=> Bump `ui-extension` to 2025.1.2

.changeset/strange-terms-rule.md, .github/workflows/ci.yml, packages/ui-extensions/src/surfaces/point-of-sale/render/components/Badge/Badge.ts
Part of https://github.com/Shopify/pos-next-react-native/issues/32885
Badge has a prop called status that is optional. Typically, removing this prop should hide the icon, but something about the extensibility bridge retains the last-known value instead. This workaround allows partners to hide the icon, and is already in use per Shopify guidance.
This adds null as an officially supported badge status type so that folks know it's OK to use.
Set a Badge's status prop to something other than undefined or null.
Verify the status icon appears.
Set the Badge's status prop to null.
Verify the status icon disappears.
=> Officially add null as Badge status option

packages/ui-extensions/docs/surfaces/customer-account/reference/targets/customer-account.order.page.render.doc.ts, packages/ui-extensions/docs/surfaces/customer-account/reference/targets/customer-account.page.render.doc.ts
Fixes: https://github.com/Shopify/core-issues/issues/71854
Docs needed to be updated regarding customer account and full page extensions
Following the work done by UX
Link: https://github.com/Shopify/shopify-dev/pull/53184
- ...
=> Updated doc for extension limits for full page 1 add per extension

packages/ui-extensions/src/surfaces/point-of-sale/event/input/PrepareReceiptInput.ts
Minor fix.
Add `extends BaseInput` to `PrepareReceiptInput`
No need to update docs, this is a new interface
- ...
=> Minor fix: PrepareReceiptInput extends BaseInput

packages/ui-extensions/docs/surfaces/point-of-sale/staticPages/pages/versions.doc.ts
Fixing some annoying typos
Companion: https://github.com/Shopify/shopify-dev/pull/53411
=> Fix typos in version doc

.changeset/silent-plants-cheat.md, packages/ui-extensions-react/package.json, packages/ui-extensions/package.json, yarn.lock
The latest version of `remote-ui/core` - `2.2.5` - has a small bug fix with `removeChild`.
probably also bump `remote-ui/react` - `5.0.6` and `remote-ui/async-subscription` - `2.1.16`
Just updates the package version
=> Bumps @remote-ui dependency versions
